asdf-format/asdf

pyasdf/asdftypes.py
pyasdf/tags/__init__.py
pyasdf/tags/core/constant.py
pyasdf/tags/core/tests/test_ndarray.py
pyasdf/tags/transform/__init__.py
pyasdf/tags/transform/basic.py
pyasdf/tags/transform/compound.py
pyasdf/tags/transform/projections.py
pyasdf/tags/transform/tests/test_transform.py
pyasdf/tags/wcs/__init__.py
pyasdf/tags/wcs/wcs.py
pyasdf/tests/test_schema.py
pyasdf/yamlutil.py

This is a work-in-progress to get the generalized WCS stuff serializing to/from ASDF.
All of this is written against embray/astropy@9307fbafe741 (the compound modeling branch).
There's a few things in modeling that I either don't understand or need improvement:

WIP: Generalized WCS -- try #3

---

pyasdf/tags/transform/basic.py
pyasdf/tags/transform/tests/test_transform.py

In response to @nden's question in #56.

Make explicit inverse transforms work.

---

pyasdf/tags/transform/__init__.py
pyasdf/tags/transform/polynomial.py

This PR goes with #49 in asdf-standard.

add polynomial implementation

---

pyasdf/tags/transform/__init__.py
pyasdf/tags/transform/polynomial.py
pyasdf/tags/transform/tests/test_transform.py

@mdboom Submitting this as a new PR. Also added tests and they all pass locally.

Add polynomials

---

pyasdf/tags/transform/basic.py
pyasdf/tags/transform/tests/test_transform.py

Round-trip the transform name

---

docs/pyasdf/examples.rst
pyasdf/asdf.py
pyasdf/block.py
pyasdf/commands/exploded.py
pyasdf/generic_io.py
pyasdf/tests/test_generic_io.py

Rather than `exploded=True` which doesn't really scale to other things.

Change API for setting all array storage

---

pyasdf/block.py
pyasdf/util.py

Part of #51 that I've pulled out so I can move on with other things.

Use a class to manage structs

---

docs/index.rst
pyasdf/commands/__init__.py
pyasdf/commands/exploded.py
pyasdf/commands/tests/test_exploded.py
pyasdf/commands/tests/test_to_yaml.py
pyasdf/commands/to_yaml.py
pyasdf/tests/helpers.py

This command takes an ASDF file and makes it 100% YAML by inlining all of the data.

Add to_yaml command

---

docs/pyasdf/examples.rst
pyasdf/asdf.py
pyasdf/compression.py
pyasdf/tests/test_compression.py

Add support for bzip2 compression

---

pyasdf/tags/transform/projections.py

Goes with spacetelescope/asdf-standard#75 and addresses #72.

make corresponding affince changes

---

pyasdf/tags/transform/projections.py
pyasdf/tags/transform/tests/test_transform.py

Some rotations parameter names have changed in modeling.

fix rotations

---

pyasdf/treeutil.py

In response to @nden's performance concerns in #91.

Don't let seen set get out of control

---

.continuous-integration/appveyor/install-miniconda.ps1
.continuous-integration/appveyor/windows_sdk.cmd
.travis.yml
appveyor.yml
docs/pyasdf/extensions.rst
pyasdf/block.py
pyasdf/extension.py
pyasdf/generic_io.py
pyasdf/resolver.py
pyasdf/tests/test_asdftypes.py
pyasdf/tests/test_generic_io.py
pyasdf/tests/test_low_level.py
pyasdf/tests/test_reference.py
pyasdf/tests/test_schema.py
pyasdf/tests/test_suite.py

MS Windows fixes

---

pyasdf/__init__.py

`python setup.py install` will fail before it has a chance to install the dependencies.

Fix the automatic installation of dependencies

---

pyasdf/asdf.py
pyasdf/extern/atomicfile.py
pyasdf/generic_io.py
pyasdf/tests/test_low_level.py

This should address #100, though I haven't tested it on Windows.

Do atomic writing

---

pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/test_ndarray.py

Handle inline masked arrays

---

pyasdf/asdf.py
pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/test_ndarray.py
pyasdf/tests/test_low_level.py

Support copying of AsdfFile objects

---

docs/sphinxext/example.py

Fix for Sphinx 1.3

---

pyasdf/reference.py
pyasdf/schema.py
pyasdf/tests/data/self_referencing.yaml
pyasdf/tests/test_schema.py

Resolve references in schema

---

docs/pyasdf/extensions.rst
pyasdf/asdftypes.py
pyasdf/extension.py
pyasdf/schema.py
pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/data/datatype.yaml
pyasdf/tags/core/tests/data/ndim.yaml
pyasdf/tags/core/tests/setup_package.py
pyasdf/tags/core/tests/test_ndarray.py

And implements the new validators related to ndarray.

Add support for custom validators

---

pyasdf/schema.py

This is useful for `jwst_lib.models`, and otherwise doesn't change existing API or functionality in `pyasdf`.

Refactor: Separate validator creation from running

---

.travis.yml
README.rst

Upgrade to containers on Travis

---

pyasdf/block.py

Prevents deeply nested recursion when there are lots of blocks -- probably faster, too.

Bugfix for #144

---

pyasdf/schema.py
pyasdf/tags/core/ndarray.py
pyasdf/tests/test_schema.py

Related to spacetelescope/asdf-standard#104

Validate the size of integer literals in the YAML

---

pyasdf/tests/helpers.py
pyasdf/tests/test_schema.py
pyasdf/tests/test_suite.py

Support extensions in assert_roundtrip_tree

---

pyasdf/tags/transform/projections.py
pyasdf/tags/transform/tests/test_transform.py

Requires astropy/astropy#4021 in order to pass.

Support all of the FITS WCS projections

---

pyasdf/asdf.py
pyasdf/tags/core/__init__.py
pyasdf/tags/core/ndarray.py
pyasdf/tags/core/table.py
pyasdf/tags/core/tests/test_table.py

Cc: @astrofrog, @embray 
As mentioned in astropy/astropy#3733, and related to spacetelescope/asdf-standard#83.

Add table support

---

pyasdf/fits_embed.py
pyasdf/tests/helpers.py
pyasdf/tests/test_fits_embed.py

In response to astropy/astropy#4097

Changes to FITS mmap management.

---

docs/pyasdf/examples.rst
pyasdf/asdftypes.py
pyasdf/setup_package.py
pyasdf/tags/core/tests/data/datatype-1.0.0.yaml
pyasdf/tags/core/tests/data/ndim-1.0.0.yaml
pyasdf/tags/core/tests/test_complex.py
pyasdf/tags/core/tests/test_ndarray.py
pyasdf/tags/unit/tests/test_unit.py
pyasdf/tests/helpers.py
pyasdf/tests/test_asdftypes.py
pyasdf/tests/test_low_level.py
pyasdf/tests/test_schema.py
pyasdf/tests/test_yaml.py
pyasdf/versioning.py
setup.py

Tagging will happen later -- this is just to test everything is working.

Version 1.0.0

---

setup.py

as the hard astropy dependency was lifted a while ago

Adding numpy dependency to setup.py 

---

asdf/tags/transform/tabular.py

Changes corresponding to asdf-standard/#132

fix tabular mdoel

---

asdf/tags/transform/tabular.py

Implement `Tabular.points` as a tuple.
Merge after astropy/astropy#5417 and spacetelescope/asdf-standard#133

improve tabular model

---

CHANGES.rst
asdf/generic_io.py

Hopefully fixes the tests in generic_io that recently started failing.

fix http tests

---

asdf/tags/unit/quantity.py
asdf/tags/unit/tests/test_quantity.py
asdf/tags/unit/tests/test_unit.py
asdf/tags/wcs/wcs.py

Updated Quantity schema to use `ndarray`, along with additional unit tests and other relatively minor changes. This addresses issue #263.

Quantity update

---

asdf/fits_embed.py
asdf/tags/unit/tests/test_quantity.py
asdf/tests/test_low_level.py

Addresses a variety of warnings currently occurring on master branch, including those described in issue #268.

Fix warnings

---

docs/asdf/extensions.rst

This fixes #288 and updates documentation to reflect the changes that were made in #272.

Update extensions documentation with new schema versioning info

---

asdf/tests/test_low_level.py

This attempts to reproduce the issue reported in #100. Since we are running on AppVeyor again, hopefully it will either reproduce the issue or demonstrate that it no longer exists.

Add test to reproduce overwrite bug in issue #100

---

CHANGES.rst
asdf/asdf.py
asdf/asdftypes.py
asdf/tests/test_asdftypes.py
asdf/yamlutil.py

Display filename in supported version warning

---

docs/asdf/examples.rst

This adds a new example to the streaming section of the documenation. Thanks to @yuvallanger for providing this use case.
This closes #278.

Add new example to streaming section

---

CHANGES.rst
setup.py

Relax requirement on semantic_version version to 2.3.1

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_low_level.py

Fix retrieval of file format version

---

CHANGES.rst
asdf/commands/__init__.py
asdf/commands/extension.py
asdf/commands/main.py

Add command-line tool for querying installed extensions

---

asdf/tags/core/tests/test_ndarray.py
asdf/tests/helpers.py
asdf/tests/test_yaml.py

Add a way of customising the comparison used in assert_roundtrip_tree

---

asdf/conftest.py

The test suite has been hanging on my local OSX machine for some time now, and it just recently started hanging on OSX on Travis as well. There haven't been any problems observed on Linux.
The problem appears to be due to the use of a temporary local HTTP server during testing. This PR makes some changes to the server implementation that _should_ prevent the test suite from hanging.

Fix hanging test suite on OSX

---

asdf/asdftypes.py

**TL; DR**: This fixes #430.
Each ASDF tag implementation names the types that it serializes. The ASDF type index automatically uses each tag type to serialize not only the types explicitly named, but also any subclasses of those types. This is all well and good.
It is possible for multiple types within the same type hierarchy to each be serialized by different tags. For example, the class `Animal` might be serialized by `AnimalType`, but the class `Dog`, which is a subclass of `Animal`, should be serialized by `DogType`.
ASDF was not careful about the way that it overrode tags associated with a particular subclass. The result ended up being dependent on the order in which the tags were added to the index, which is non-deterministic on certain versions of Python. In concrete terms, …

Fix bug that incorrectly overwrites subclasses in the write type index

---

asdf/fits_embed.py
asdf/tests/test_fits_embed.py

This partially addresses #451.

NAXIS1 in AsdfHDU should reflect data length, not padded length

---

.travis.yml
appveyor.yml
asdf/conftest.py
asdf/tests/helpers.py
asdf/tests/httpserver.py
asdf/tests/test_remote_data.py

This allows the test suite to pass when running against the latest version of Astropy.

Minor testing-related changes to v1.3.x

---

README.md

Add appveyor build status badge to README

---

README.md

Fix minor (but significant) typo in README

---

asdf/commands/tests/test_defragment.py

See if lz4 test failure on Windows has resolved itself

---

asdf/tests/schema_tester.py

See https://github.com/spacetelescope/asdf-standard/pull/160.

Update asdf-standard to reflect new multiply schema

---

docs/_static/custom.css
docs/asdf/extensions.rst
docs/conf.py
docs/index.rst
docs/sphinxext/example.py

@perrygreenfield I haven't yet found anything about making the code blocks larger, but I'll keep digging.

Documentation improvements based on feedback

---

CHANGES.rst
asdf/asdf.py
asdf/tags/core/tests/test_history.py

Add API function for retrieving history entries

---

CHANGES.rst
asdf/block.py
asdf/tests/test_compression.py

Fix bug with array compression settings

---

.travis.yml
appveyor.yml

Update CI scripts to test against Python 3.7

---

asdf/tests/test_schema.py

Add test for schema reference encoded as file URL

---

asdf/versioning.py

Better error message for incompatible standard versions

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_generic_io.py

Add option to generic_io to close underlying file handles

---

asdf/block.py
asdf/tests/test_low_level.py

Fix warning caused by potential comparison with NaN arrays

---

asdf/tests/test_asdftypes.py

This is now possible (albeit with a warning) thanks to #571.

Add test for serializing/deserializing type without schema

---

.travis.yml

https://blog.travis-ci.com/2013-11-27-fast-finishing-builds

Fast finish Travis jobs

---

CHANGES.rst
asdf/exceptions.py
asdf/tests/helpers.py
asdf/tests/test_helpers.py
asdf/yamlutil.py

Add custom warning class for failure to convert into custom types

---

CHANGES.rst
asdf/asdftypes.py
asdf/tests/test_asdftypes.py
asdf/versioning.py

This fixes a bug that was first reported in astropy/astropy#8064.

Make sure core tags are added to type index first

---

asdf/block.py
asdf/commands/diff.py
asdf/commands/main.py
asdf/compression.py
asdf/extension.py
asdf/fits_embed.py
asdf/generic_io.py
asdf/resolver.py
asdf/tagged.py
asdf/tags/core/constant.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/httpserver.py
asdf/tests/test_asdftypes.py
asdf/tests/test_generic_io.py
asdf/tests/test_yaml.py
asdf/type_index.py
asdf/types.py
asdf/util.py
asdf/versioning.py

Remove all old-style class declarations

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_api.py

This resolves #616.
cc @Cadair

Support pathlib with asdf.open and AsdfFile.write_to

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_api.py

Define the "in" operator for top-level AsdfFile objects

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_api.py

This fixes a bug (and adds a test) for an issue that was reported by @jdavies-st.

Fix extension version check

---

CHANGES.rst
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py

Make NDArrayType.__len__() a method, not a property

---

asdf/tests/test_schema.py

This is to try to debug a problem on Windows.
https://github.com/astropy/astropy/issues/8683

Add test for schema url_mapping via entry points

---

licenses/LICENSE.rst

But really, I want to check new bot behavior. Still, this is a real PR.

Update license year

---

CHANGES.rst
asdf/versioning.py

- Updated the supported versions 
- Updated to the latest asdf-standard (to pick up ortho-polynomial)

Updated to the latest asdf-standard

---

asdf/tests/test_asdftypes.py

fix gwcs import of WCSType tag, changed in 0.12.0

---

CHANGES.rst
README.rst

simplify example

---

CHANGES.rst
asdf/asdf.py
asdf/commands/tests/data/frames0.asdf
asdf/commands/tests/data/frames1.asdf
asdf/schema.py
asdf/tests/test_asdftypes.py
asdf/tests/test_schema.py
asdf/yamlutil.py

Test failures in astropy made it clear that this isn't feasible.  We're going to investigate deprecating the defaults feature entirely.
Resolves #795

Revert #793

---

asdf/__init__.py

Just a little thing that's been bugging me.

Alias open_asdf --> open in a more normal way

---

CHANGES.rst
asdf/config.py
asdf/resource.py
asdf/tests/test_resource.py

This makes comparing them simpler.

Add __eq__ and __hash__ implementations to ResourceMappingProxy

---

.gitmodules
CONTRIBUTING.md
asdf/asdf.py

also update gitmodules path to asdf-format GitHub org

remove duplicate docs line in AsdfFile.set_array_compression

---

asdf/resource.py
asdf/tests/test_resource.py
setup.py

This is just to make the extension_manifest-1.0 schema available.

Add the asdf-format.org resources directory

---

docs/asdf/developer_overview.rst

This just removes trailing spaces from `developer_overview.rst` so that the diff of my forthcoming updates to that document will be cleaner.

Remove trailing spaces from developer overview documentation

---

docs/asdf/developer_overview.rst
docs/asdf/developer_versioning.rst

Here are some developer overview updates to reflect changes that we've merged for 2.8.  Let me know if I'm missing any topics you'd like to see or if I should expand more on any of what I have.
Resolves #861

Update developer documentation to reflect upcoming 2.8 changes

---

CHANGES.rst

Oops, I forgot about this until just after I hit that merge button...

Add changelog entry for asdftool edit

---

.travis.yml

- Add names to Travis CI jobs
- ~Add Python 3.9 to the matrix, and fix the bug found~

Add user-friendly names to Travis CI jobs

---

docs/asdf/extensions.rst

Fix broken link in readthedocs based on issue #892

Fix broken link in extensions.rst

---

.github/workflows/asdf_ci.yml

Adding a basic github action workflow that does a `flake8` check and runs `pytest`.

Adding a basic github action workflow.

---

.github/workflows/asdf_ci.yml
.github/workflows/downstream.yml
README.rst

The badge in `README` still references `Travis`. This PR adds all GA CI badges.

add GA badges

---

CHANGES.rst

Fix year typo in changelog

---

.github/workflows/downstream.yml

This is similar to #960 but adds a new parameter to the job matrix to allow custom test commands.
Resolves #946

Test weldx downstream

---

.github/workflows/downstream.yml

update for test refactor over at weldx

update weldx test path

---

.github/workflows/downstream.yml

our master should be ready for 2.8 now 🚀

set weldx branch to master in downstream CI

---

asdf/extension/_converter.py

found this little documentation discrepancy while going through the code

fix from_yaml_tree docstring parameter name

---

.github/workflows/downstream.yml

we have changed the schema file location with a recent release, can you update this @eslavich ?

update weldx downstream workflow

---

.github/workflows/ci.yml

Add python 3.10 to CI test matrix.

Add python 3.10 to CI test matrix

---

README.rst

Fixes some command bugs in readme for users using zsh.

Fixed bugs zsh in readme

---

CHANGES.rst
asdf/search.py

The previous PR didn't handle obtaining values for searches properly.

fixed search for __asdf_traverse__ capability

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_asdf.py

Seems easy enough?
If this is merged, it would really be lovely if it could be backported to 2.8 :wink:

Add uri to SerializationContext

---

.github/workflows/ci.yml
.github/workflows/downstream.yml
tox.ini

Fixes #1072 by adding asdf-astropy testing

Add CI for asdf-astropy

---

.github/workflows/publish-to-pypi.yml

Missing a required field in the publish workflow...

Add user to publish workflow

---

.github/workflows/ci.yml
.github/workflows/downstream.yml
setup.cfg
tox.ini

Add asdf-standard to the CI workflows

Add asdf-standard to the CI

---

asdf/extension/__init__.py

I missed the codestyle failures and merged #1092 prematurely.

Fix style issues from #1092

---

.github/workflows/ci.yml

Update warnings job to python 3.10

---

.github/workflows/s390x.yml

Update the s390x CI to support python 3.8 (as python 3.7 is no longer supported).

Update s390x CI

---

docs/sphinxext/example.py

Bug fixes for the documentation.
Fixes #1110

Bugfixes for sphinx

---

.github/workflows/ci.yml

Update CI so it can be run manually and schedule it to run once a week

Update CI run options

---

docs/asdf/extending/resources.rst

docs build: https://readthedocs.org/projects/asdf/builds/17390619/

update docs to include correct usage of `package-data` when including YAML resources

---

.pre-commit-config.yaml
asdf/extension/_legacy.py
asdf/resource.py
asdf/tagged.py
asdf/tests/test_config.py
docs/conf.py

Enables autoflake8 in pre-commit, which removes unused imports and unused variables automatically.

Add autoflake8

---

CHANGES.rst

Adds the change notes from release 2.11.1 back into master changelog.

Add 2.11.1 changes to changelog

---

asdf/extension/_converter.py

This reverts #1192, as these changes are not needed

Revert #1192 from WilliamJamieson/bugfix/obj

---

pyproject.toml

Fixes #1122 based on this https://github.com/pytest-dev/pytest/issues/9765#issuecomment-1236232498

Remove pytest pin for windows

---

docs/conf.py

Fix the copyright at the bottom of asdf docs

Fix typo in docs

---

CHANGES.rst
pyproject.toml

restrict setuptools.packages.find to asdf and pytest_asdf

---

.github/workflows/ci.yml

Attempt to use the released version of python 3.11

Use released python 3.11 runner

---

asdf/asdf.py
asdf/block.py
asdf/commands/edit.py
asdf/commands/extension.py
asdf/commands/extract.py
asdf/entry_points.py
asdf/extension/_converter.py
asdf/extension/_legacy.py
asdf/extension/_manager.py
asdf/fits_embed.py
asdf/resource.py
asdf/schema.py
asdf/tags/core/external_reference.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_history.py
asdf/tests/test_api.py
asdf/tests/test_array_blocks.py
asdf/tests/test_asdf.py
asdf/tests/test_entry_points.py
asdf/tests/test_fits_embed.py
asdf/tests/test_helpers.py
asdf/tests/test_resource.py
asdf/tests/test_schema.py
asdf/tests/test_stream.py
asdf/tests/test_types.py
asdf/tests/test_yaml.py
asdf/treeutil.py
asdf/types.py
asdf/yamlutil.py

I noticed reviewing some code that some of the fixed strings in ASDF needed some cleanup. This PR performs this maintenance.

Cleanup some strings

---

requirements-dev.txt

Add jsonschem to devdeps

---

.github/workflows/ci.yml
compatibility_tests/test_file_compatibility.py

applied fix for missing distdir, likely will see other failures which this PR will test for

update tox.ini for 4

---

CHANGES.rst
pyproject.toml

Bump min version to 0.3.0
Fixes #1277

Bump asdf-transform-schemas version

---

.github/workflows/s390x.yml

Attempt to fix s390x build.
Changes based on astropy/astropy#13940 and this part of the astropy CI: https://github.com/astropy/astropy/blob/5b2915e22de504280bdaf573464b2e99f49f7ab6/.github/workflows/ci_cron_weekly.yml#L91-L145

TST fix s390x build

---

.pre-commit-config.yaml
pyproject.toml

Apply [`pyproject-fmt`](https://pyproject-fmt.readthedocs.io/en/latest/) to ASDF.

Apply automatic formatter to pyproject.toml

---

asdf/__init__.py
asdf/asdf.py
asdf/block.py
asdf/commands/defragment.py
asdf/commands/exploded.py
asdf/commands/main.py
asdf/commands/to_yaml.py
asdf/fits_embed.py
asdf/generic_io.py
asdf/resolver.py
asdf/schema.py
asdf/search.py
asdf/tests/test_info.py
asdf/tests/test_search.py
asdf/versioning.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1303.
It enables `ruff` to explicitly check `flake8-builtins` style checks.

Add `flake8-builtins` check to `ruff`

---

CHANGES.rst
asdf/block.py
asdf/tests/test_array_blocks.py

Revert #1280

---

tox.ini

add media extra install option to weldx
This PR https://github.com/BAMWelDX/weldx/pull/727
added new requirements for the weldx tests

fix weldx ci job

---

CHANGES.rst
asdf/entry_points.py
asdf/tags/core/tests/test_history.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/__init__.py
asdf/tests/objects.py
asdf/tests/test_deprecated.py
asdf/tests/test_extension.py
asdf/tests/test_helpers.py
asdf/tests/test_schema.py
asdf/tests/test_types.py
asdf/types.py
pyproject.toml
tox.ini

CustomType is deprecated. This PR adds a warning and test for the warning.

add deprecation to CustomType

---

.github/workflows/label.yml

Check the label for @meeseeksdev and auto-magically apply the correct milestone to the PR.

Add label checker CI

---

CONTRIBUTING.rst

Add note to contributing guide about backport labels

---

asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_types.py
asdf/types.py
tox.ini

Backport PR #1365: Make the warning only issue on the very first subclass of `CustomType`

---

CONTRIBUTING.rst

Document how to use the meeseeks bot and enable a "rebase and merge" test for backporting.

Document how to use the meeseeks bot

---

asdf/compat/numpycompat.py
asdf/tests/test_yaml.py

remove asdf.compat

---

.github/workflows/ci.yml
tox.ini

consolidates toxenvs to use common keywords and reduce configuration complexity, and updates keywords to Tox 4 snake case versions

Consolidate toxenvs

---

tox.ini

testing speed of jwst tests run in parallel

run jwst downstream tests in parallel

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_generic_io.py

respect umask when determining file permissions

---

.readthedocs.yaml
CHANGES.rst

Backport PR #1504 on branch 2.15.x (update changelog for 2.15.0 release)

---

CHANGES.rst
docs/asdf/whats_new.rst

Update changelog and docs page in prepration for 2.15.1 release

update main for 2.15.1 release

---

CHANGES.rst
docs/asdf/whats_new.rst

pull updated changelog from main for 2.15.1 release

backpart changelog updates for 2.15.1 release from main to 2.15.x

---

.github/workflows/downstream.yml
tox.ini

Add asdf-zarr and asdf-compression to downstream CI

add asdf-zarr and asdf-compression to downstream CI

---

.pre-commit-config.yaml
asdf/_block/callback.py
asdf/_block/external.py
asdf/_block/io.py
asdf/_convenience.py
asdf/_display.py
asdf/_tests/tags/core/tests/test_ndarray.py
asdf/_tests/test_api.py
asdf/_tests/test_asdf.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_file_format.py
asdf/_tests/test_generic_io.py
asdf/_tests/test_history.py
asdf/_tests/test_integration.py
asdf/_tests/test_reference.py
asdf/_tests/test_schema.py
asdf/commands/diff.py
asdf/commands/exploded.py
asdf/commands/extension.py
asdf/commands/tags.py
asdf/commands/to_yaml.py
asdf/config.py
asdf/extension/__init__.py
asdf/extension/_converter.py
asdf/reference.py
asdf/resource.py
asdf/search.py

update pre-commit hooks

---

CHANGES.rst

Starting 3.1.0 release.
Will re-milestone all open issues/PRs for 3.1.0 to 3.2.0 before release. This PR will test s390x and regtests are running (using asdf main) for:
JWST: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1232/
romancal: https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FRoman-Developers-Pull-Requests/detail/Roman-Developers-Pull-Requests/612/pipeline/210
both regtests passed without errors

update changelog for 3.1.0

---

CHANGES.rst

update changelog for 3.2.0 release

---

CHANGES.rst

Regtests:
- Roman all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/10236483410
- JWST show only unrelated failures: https://github.com/spacetelescope/RegressionTests/actions/runs/10236486971

add release date to 3.4.0 in changelog

---

.github/workflows/changelog.yml
changes/1828.misc.rst

only check for issue number, to accomodate `misc` category

---

.github/workflows/ci.yml

TEST: python 3.13 without calls to gc.collect
