asdf-format/asdf

pyasdf/asdf.py
pyasdf/block.py
pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/test_ndarray.py

Previously, auto-inlining only affected ndarrays that were explicitly a
part of the custom tree -- not on arrays that get created implicitly by
other types in the tree, such as transform matrices.  This makes these
global block type settings apply even on newly-created ndarrays.
In response to @nden's comment: https://github.com/spacetelescope/pyasdf/pull/68#issuecomment-76194873

Fix bug in auto-inlining

---

docs/pyasdf/examples.rst
docs/sphinxext/example.py
pyasdf/asdf.py
pyasdf/block.py
pyasdf/compression.py
pyasdf/generic_io.py
pyasdf/tests/test_compression.py

This is a replacement for the much more complex approach in #51.  This just does simple compression of the block using only `zlib` compression.
The plan is to use transforms to do more complex lossy compression at a later date and just get the simplest possible thing that can work in now.

Implement simple compression approach.

---

pyasdf/asdf.py
pyasdf/block.py
pyasdf/tests/test_low_level.py
pyasdf/tests/test_suite.py

@embray I'd appreciate your comments on this.
Right now it's using MD5 hashes.  Should we consider a different/longer hash?  Any strong argument in favor of storing the hash type in the file (and thus opening this up to multiple hash algorithms in the future)?
This implementation only validates the checksums when an explicit flag is passed to `read`, to avoid unnecessarily reading the entire file.  It always writes checksums to the file, unless the data was memmapped and never accessed at all, since in that case we can assume the existing checksum is still valid.  This does mean that updating the file in place will result in streaming in the entire contents of any data that was accessed (it would be nice to do that only if *writes* were made, but I don't think there's a way to get that …

Add checksum support

---

pyasdf/tests/test_low_level.py
pyasdf/yamlutil.py

I wasn't aware that pyyaml doesn't use the C libyaml-based parser/dumper by default.

Use C yaml parser

---

pyasdf/__init__.py
pyasdf/asdf.py
pyasdf/asdftypes.py
pyasdf/schema.py
pyasdf/tagged.py
pyasdf/tests/data/custom.yaml
pyasdf/tests/test_schema.py
pyasdf/treeutil.py
pyasdf/yamlutil.py

This will now validate and recurse the tree only once per YAML tag.  It still may recurse multiple times over the same parts of the tree, but I don't see a way around that given how JSON schema works.
This is about a 15% improvement in JSON schema validation.

Improve performance of schema validation

---

pyasdf/tests/test_low_level.py

The `assert` statements in test_low_level checksum tests fail for 32-bit computers.

Fix checksum tests for 32-bit machines

---

docs/sphinxext/example.py

This fixes an encoding error that appears when building the docs with python 3.4. However I think that this may not be portable to other python versions. I have not tried it with python 2 yet.

Fix error when building docs witn python 3

---

pyasdf/asdf.py
pyasdf/block.py
pyasdf/reference.py
pyasdf/schema.py
pyasdf/tags/transform/tests/test_transform.py
pyasdf/tests/data/custom.yaml
pyasdf/tests/test_schema.py
pyasdf/util.py
pyasdf/yamlutil.py

Also updates the schema checker to make sure the default values in the schema are valid in their own context.

Automatically fill-in default values

---

pyasdf/generic_io.py

I tried running the following example:
```python
from pyasdf import AsdfFile
import numpy as np
tree = {
'author': 'John Doe',
'my_array': np.random.rand(8, 8)
}
ff = AsdfFile(tree)
with ff.write_to("example.asdf"):
pass
```
and I get the following exception:
```
Traceback (most recent call last):
File "test.py", line 25, in <module>
with ff.write_to("example.asdf"):
File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev425-py3.4.egg/pyasdf/asdf.py", line 609, in write_to
self._serial_write(fd, pad_blocks)
File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev425-py3.4.egg/pyasdf/asdf.py", line 428, in _serial_write
self.blocks.write_internal_blocks_serial(fd, pad_blocks)
File …
```

Example failing on MacOS X

---

pyasdf/tags/core/ndarray.py

Before this change, it was not easy to know if an unloaded array was masked or not, and this now outputs:
```
<masked_array (unloaded) shape: [3] dtype: int64>
```
I'd be happy to add a test but I wasn't sure where this should be done?

Make it clear from repr/str when unloaded array is masked

---

pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/test_ndarray.py

If a memmap'd array is used as a mask in a numpy MaskedArray, that
memmap is never free'd.  Using a view on the memmap'd array seems to
workaround this without copying the mask array.

Fix #111: Workaround reference-counting bug.

---

docs/index.rst
docs/pyasdf/examples.rst
docs/sphinxext/example.py
pyasdf/__init__.py
pyasdf/asdf.py
pyasdf/block.py
pyasdf/commands/defragment.py
pyasdf/commands/exploded.py
pyasdf/commands/tests/test_defragment.py
pyasdf/commands/tests/test_exploded.py
pyasdf/commands/tests/test_to_yaml.py
pyasdf/commands/to_yaml.py
pyasdf/generic_io.py
pyasdf/reference.py
pyasdf/stream.py
pyasdf/tags/core/tests/test_complex.py
pyasdf/tags/core/tests/test_ndarray.py
pyasdf/tags/unit/tests/test_unit.py
pyasdf/tests/helpers.py
pyasdf/tests/test_asdftypes.py
pyasdf/tests/test_compression.py
pyasdf/tests/test_generic_io.py
pyasdf/tests/test_low_level.py
pyasdf/tests/test_reference.py
pyasdf/tests/test_schema.py
pyasdf/tests/test_stream.py
pyasdf/tests/test_yaml.py

This is an alternative to #116.  Fix #107, fix #109.
This is an attempt to fix up context manager usage at the expense of:
- the streaming API which is now a little less convenient (since it relies on having a raw file handle).  But that's advanced usage anyway
- It's no longer possible to `write_to` and then `update` -- one must `open` and then `update`. 
@astrofrog: Your thoughts?

Simplify write_to and context manager usage.

---

docs/pyasdf/examples.rst

Replace reference to `write_to_stream`  in documentation.

Fix comment in streaming data example

---

docs/index.rst

This fixes some warnings when building the docs.

Remove merge conflict in docs/index.rst

---

docs/index.rst
docs/pyasdf/examples.rst
docs/sphinxext/example.py
pyasdf/asdf.py
pyasdf/fits_embed.py
pyasdf/tests/helpers.py
pyasdf/tests/test_fits_embed.py
pyasdf/tests/test_reference.py

This saves an ASDF file as an extra "ASDF" extension inside of a FITS file.  That ASDF file can refer to binary arrays in other extensions in the FITS file.

ASDF-in-FITS embedding

---

pyasdf/schema.py
pyasdf/tests/data/default.yaml
pyasdf/tests/test_schema.py
pyasdf/yamlutil.py

Previous to this, default values on anything but the top-level of the schema were not being handled.

Fix default handling

---

pyasdf/tests/test_low_level.py
pyasdf/treeutil.py

`walk_and_modify` shouldn't add a key/value pair if the functor returns `None`.

Remove none keys on modify

---

pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/test_ndarray.py

This ensures that the deferred loading of the arrays will happen when using a numeric operator on them.

Operations on ndarray proxies

---

pyasdf/block.py
pyasdf/fits_embed.py
pyasdf/tags/core/ndarray.py
pyasdf/tests/test_fits_embed.py

Needs a little hack to make sure the endianness of FITS extensions is always "big".

Fix endian problems in FITS-in-ASDF when creating FITS file based on tree

---

pyasdf/asdf.py
pyasdf/generic_io.py
pyasdf/yamlutil.py

No longer need to read the entire YAML content into memory just to parse it.

Pass a reader directly to PyYAML

---

pyasdf/fits_embed.py
pyasdf/tests/helpers.py
pyasdf/tests/test_fits_embed.py

The `AsdfInFits` class should not be closing the FITS file, since it's passed in and it doesn't "own" it.
Ideally `HDUList.close()` would close and flush all of it's mmap handles, but it doesn't.  Fixing that is sort of a `astropy.io.fits` issue that is sort of non-trivial to fix (see astropy/astropy#3827), and `pyasdf` shouldn't be trying to patch around that with magic.
Here, the magic is moved to the testing functions only just to get `setup.py test --open-files` to not complain.

Fix FITS file close handling

---

docs/pyasdf/extensions.rst
pyasdf/asdf.py
pyasdf/extension.py
pyasdf/generic_io.py
pyasdf/reference.py
pyasdf/resolver.py
pyasdf/schema.py
pyasdf/tags/__init__.py
pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/test_ndarray.py
pyasdf/tags/time/__init__.py
pyasdf/tags/time/tests/test_time.py
pyasdf/tags/time/time.py
pyasdf/tags/transform/basic.py
pyasdf/tests/test_asdftypes.py
pyasdf/tests/test_generic_io.py
pyasdf/tests/test_low_level.py
pyasdf/tests/test_reference.py
pyasdf/tests/test_schema.py
pyasdf/treeutil.py
pyasdf/util.py
pyasdf/yamlutil.py

This is the implementation of spacetelescope/asdf-standard#87.
Adds a time type that can represent various kinds of time formats and scales.

Add support for time type

---

pyasdf/asdf.py
pyasdf/block.py
pyasdf/tags/core/ndarray.py
pyasdf/tags/core/tests/test_ndarray.py
pyasdf/tests/test_low_level.py
pyasdf/tests/test_schema.py
pyasdf/tests/test_stream.py

The current behavior is to find all blocks in the ASDF file by "skipping" along their headers immediately upon opening the file.  While it isn't reading (or even memmapping) all of the data, it is skipping along the file to read the block headers, and if there's a lot of blocks, that overhead could be significant (particularly over a network file system or HTTP with Range headers).
This changes things so the block headers are read lazily when a particular block is requested.  This still isn't random access, since all block headers leading up to a particular block must still be read.  For example, if block 9 of 20 is requested, block headers 0-9 will be read (and cached along the way for later use, so requesting block header 4 afterward wouldn't even hit the disk).
The first block header …

Deferred block finding

---

pyasdf/generic_io.py
pyasdf/tests/helpers.py
pyasdf/tests/test_generic_io.py

To avoid redundant requests to the server, it creates a local copy in a tempfile, and copies over blocks as needed.  This actually greatly simplifies the code and optimizes the network bandwidth at the expense of disk space.

Change how HTTP Range connections are handled

---

pyasdf/schema.py
pyasdf/tags/core/tests/test_history.py
pyasdf/tags/time/time.py

This fixes a problem where datetime objects were not roundtripped as
datetime objects.  This also removes a dependency on astropy for time if
you don't care about all the complexities that astropy.time supports.

Roundtrip datetime as datetime

---

pyasdf/tags/transform/compound.py
pyasdf/tags/transform/tests/test_transform.py

This fixes two problems:
- In the case of dropping an axis, e.g. `models.Mapping((0, 1), n_inputs=3),  the original model was not restored because `n_inputs` was not written out to file.
- `mapping` of type tuple was not accepted.

fix problems with remap_axes

---

pyasdf/schema.py

I found it super confusing in debugging that the Validator looks to be coming from jsonschema, when in fact it's being created in asdf.schema, and the iter_errors method being overwritten.
This should make the situation a little less confusing.  I was also thinking of adding a custom metaclass to the validator with a more informative `__repr__` telling us exactly what metaschema this validator is for, as well as displaying the `validators` mapping.

Rename generated Validator class as ASDFValidator

---

pyasdf/schema.py

Per the discussion [here](https://github.com/spacetelescope/gwcs/pull/19/files#r37652995), pyyaml will already write out tuples using the YAML sequence type.  However, jsonschema does *not* accept tuples for `type: array`.  In fairness a tuple really isn't like a JavaScript array, but for purposes of *output* validation I feel like it should pass muster (it will never be read back in as a tuple, which is fine).
This PR is built on top of #170, but could just as easily be cleaved apart from it.
Still needs tests.

Validate Python tuples as `type: array` under YAML Schema

---

appveyor.yml

Just fixes a typo that should get the appveyor builds going again on top of #180

Should be '--init' not 'init'

---

.travis.yml

Remove support for python 2.6 .

stop support for python 2.6 as astropy does not support it any more

---

.travis.yml
asdf/tags/transform/basic.py
asdf/tags/transform/projections.py

This PR reflects changes made in astropy/modeling v.1.2.
- `Model._custom_inverse` was renamed to `Model._user_inverse` in astropy 1.2.
- Sky rotations were implemented as subclasses of `EulerAngleRotations`. This had the side effect that the model parameters now are the Euler angles `phi`, `theta` ,`psi` and the user parameters which initialize the rotations `lon`, `lat`, and `lon_pole` are returns by properties and are numbers. This is unfortunate but I don't see a simple way around it.
This also removes `numpy 1.6` from the CI matrix.

Bring transforms up-to-date with astropy 1.2

---

.travis.yml
ah_bootstrap.py
asdf/__init__.py
asdf/_internal_init.py
asdf/conftest.py
asdf/tags/transform/polynomial.py
docs/asdf/examples.rst
setup.py

There were a few remaining mentions of pyasdf, this PR changes those.
Also the ``asdf-standard`` submodule wasn't updated to the one with the rename changes (as there wasn't a release, I used the hash of the current master and not a release tag).
And as a "bonus", this updates to the latest astropy-helpers, too.

Fixing rename remnants

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_generic_io.py

While my previous fix for the memory leak problem fixed that issue, other code in generic_io.py and its tests expects that the returned object be an ndarray. Since using the frombuffer call followed by a copy to break the reference achieves the same result as using array, I've replaced my previous change to MemoryIO with this new change.

Replace array class code with ndarray class plus copy

---

asdf/versioning.py
setup.py

Fix a bug in reporting versions from  #210.
Changed the VERSION string to `1.1.1.dev` with next release set to be `1.1.1` for now.

fix a bug in versioning, change package version to 1.1.1.dev

---

docs/rtd-pip-requirements

sometheing the docs are doing requires sphinx>=1.4.2.  There
was a bug in 1.4.1 that caused an error if a caption was not
supplied to TOC.  https://github.com/sphinx-doc/sphinx/issues/2465
added other requirements such that local build worked installing just
from rtd-pip-requirements from a blank conda env.

update rtd-pip-requirements to allow doc build

---

docs/index.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

asdf/block.py

The code in asdf assumes a block will be a contiguous block of memory. But recent versions of numpy have used views more heavily and now there are cases when an object instantiated as a bock is not contiguous, which leads to errors when the block is used. The modified code calls numpy.ascontiguousarray to make sure the block memory is contiguous.
This is a revised version of the branch, as several other irrelevant changes were put in the previous version of the branch.

Force new blocks to be contiguous

---

CHANGES.rst
asdf/asdftypes.py
asdf/tagged.py
asdf/tags/transform/basic.py
asdf/tags/transform/compound.py
asdf/tests/test_generic_io.py
asdf/tests/test_tagged.py

Part of the validation of an asdf tree against a schema is checking
tags in the schema against tags embedded in the data. Function
tagged.tag_objects has code supplies these tags, but orignally was
only coded to handle dctionaries, lists, and strings. This proved a
problem when checking the tags of times in the asdf tree, as times are
none of these types. I previously wrote a function specifically to
handle times, but his code had two problems. First, it created an
extra dependency on the astropy time code and second, the fix was
limited to time fields.
After becoming more familiar with the code I saw that the
functionality for handling more complex data objects was already in
asdf, in yamlutil.custom_tree_to_tagged_tree. So I removed the code I
had written to handle Time objects and …

Rewrite code which tags complex objects

---

asdf/versioning.py

Asdf throws an error message when it fails to read the version map file. The error message includes the version being searched for in the form of an undefined variable, version_string. I added a line defining this variable so that the exception doesn't throw another exception.
Please note that the most likely reason for the version map file not to be found is that the asdf-standard package has not been installed, as that is where the file is found in the distribution.

Fix version error message

---

.travis.yml
CHANGES.rst
asdf/tags/transform/__init__.py
asdf/tags/transform/basic.py
asdf/tags/transform/tabular.py
asdf/tags/transform/tests/test_transform.py

Allow ASDF to run with older astropy versions by conditionally enabling parts which require newer versions. 
- In astropy 1.2 `Model._custom_inverse` was renamed to `Model._user_inverse`.
- astropy 1.3 will release a `Tabular` model which is already in asdf and is conditionally imported.
Also added testing with two older astropy versions on travis.

make astropy use conditional to include old versions of astropy

---

CHANGES.rst
asdf/tags/transform/basic.py
asdf/tags/transform/tests/test_transform.py
asdf/tests/data/missing-1.1.0.yaml
asdf/tests/helpers.py
asdf/tests/test_schema.py
asdf/versioning.py

This resolves spacetelescope/asdf-standard#137.  Should be merged after spacetelescope/asdf-standard#138
[ ] Add tests for `bounding_box` and reading/writing different versions.
[ ] Update the pointer to the asdf-standard

Implements v 1.1.0 and bounding_box

---

CHANGES.rst
asdf/asdf.py
asdf/generic_io.py
asdf/tests/test_generic_io.py

Added a function which checks if the input is an ASDF file.
There was a check in `AsdfFile.open_impl` before. However, the approach there was to read until `\n` character and then check for the existence of the ASDF magic constant. This approach fails in some cases. In the case which  prompted this change, the input was a large FITS file which led to Memory Error after it took a long time to read the entire file.
The new `is_asdf_file` function reads only the first 5 bytes.

add is_asdf test

---

CHANGES.rst
asdf/asdf.py
asdf/fits_embed.py
asdf/tests/test_fits_embed.py

Issue #182 proposed more intelligent handling of FITS files with ASDF extensions. This branch allows ``AsdfInFits.open`` to handle URIs, open file handles, and HDULists, whereas previously it only handled HDULists. Also, ``AsdfFile.open`` now attempts to handle FITS files with ASDF extensions if the given file-like object is not obviously ASDF. Comments on implementation, code style, documentation, etc. welcome.

Better handling of AsdfInFits

---

asdf/tags/wcs/tests/test_wcs.py
asdf/tests/test_generic_io.py
asdf/tests/test_schema.py
setup.cfg

There were quite a few issues that were causing warnings when running pytests (see issue #243). Some of these were due to deprecated functionality in pytests itself. Others indicate potential issues that need to be addressed, but can be suppressed for the time being.
This addresses issue

Mitigate and/or suppress pytest warnings

---

CHANGES.rst
asdf/asdftypes.py
asdf/tags/unit/__init__.py
asdf/tags/unit/quantity.py
asdf/tags/unit/tests/test_quantity.py
asdf/tags/unit/unit.py
asdf/tags/wcs/tests/test_wcs.py
asdf/tags/wcs/wcs.py
asdf/tests/helpers.py
asdf/tests/test_asdftypes.py

This update addresses issue #212. Astropy updated the representation of the ``obsgeoloc`` and ``obsgeovel`` fields of WCS frames to be ``CartesianRepresentation`` objects where previously they were ``Quantity`` objects. This update brings the ASDF WCS frame implementation in line with   those changes. It relies on a change to the schema of WCS frames in ``asdf-standard`` (currently pending pull request: https://github.com/spacetelescope/asdf-standard/pull/142).
**Note**: The ``CartesianRepresentation`` class from ``astropy`` does not currently define equality. Our unit tests depend on being able to compare an original object with the object resulting from a round-trip tree operation, so they currently will not pass with these changes. I was able to test the changes in the interim by …

Asdf frame update

---

asdf/asdf.py
asdf/block.py
asdf/compression.py
asdf/tests/test_compression.py
asdf/tests/test_low_level.py
docs/sphinxext/example.py

See test_recompression() in asdf/tests/test_compression.py
So we should distinguish the input compression type from the output one. Otherwise, loading a file with zlib-ed arrays and saving it with bzip2-ed arrays fails, as the compression is overridden.
This involves careful observation of every `Block.compression` usage and deciding if it should be "input" or "output". Besides, i removed the ambiguous property `is_compressed`. So yeah, this breaks the public API.
Another notice is that opening a zlib file and saving it with `write_to` without specifying `all_array_compression` changed it's behavior. Before: file is saved with the same output compression codec as the input one. After: file is saved without any compression.

Fix changing the compression codec

---

.travis.yml
appveyor.yml
asdf/asdf.py
asdf/commands/defragment.py
asdf/commands/tests/test_defragment.py
asdf/compression.py
asdf/tests/helpers.py
asdf/tests/test_compression.py
setup.py

Fixes #254
Using [python-lz4](https://github.com/python-lz4/python-lz4) here. I had to implement the custom stream wrapper as we read the file in blocks of fixed, small size and need to accumulate them. Unfortunately, `lz4` does not contain the stream implementation yet.
Additional notes:
* The default block size is in bytes now, not in numpy array rows (wtf? I guess it was a bug), and I set it to 4 MiB. Does not change anything for zlib and bzip2 (we use streams), but improves the efficiency of lz4.
* I increased the data size in test_defragment(), otherwise bzip2 does not pass - likely because of the headr overhead.
* I allowed compression objects to miss the `flush()` method.

Add lz4 compression type

---

asdf/asdf.py
asdf/tests/test_fits_embed.py
asdf/tests/test_low_level.py

Addresses issue #264. The `accept_asdf_in_fits` parameter was provided for backwards compatibility with older behavior. However it is no longer needed by the only client that ever used it, which was the jwst pipeline.

Remove unused parameter from asdf.open

---

asdf/__init__.py
asdf/asdf.py
asdf/asdftypes.py
asdf/extension.py
asdf/tags/wcs/tests/test_wcs.py
asdf/tags/wcs/wcs.py
asdf/tests/data/custom_flow-1.1.0.yaml
asdf/tests/test_asdftypes.py
asdf/yamlutil.py
docs/asdf/extensions.rst

As it stands, this is a fairly naive implementation of backwards compatibility for `CelestialFrame`s. More than anything it's meant to demonstrate how backwards compatibility might be implemented for future tag classes where it is actually required. It's also meant to expose functionality that needs to be added/modified in order to support backwards compatibility. I will continue to update this PR with improvements until it seems mature enough to merge.
This is an attempt to address issue #249, and also may be related to #252.

WIP: Schema backwards compatibility

---

asdf/commands/tests/test_defragment.py

The test fails on AppVeyor. It seems to be unable to import the `lz4` module even though the logs show that it was installed in the virtual environment. This also means that the `pytest.importorskip('lz4')` doesn't appear to be working in this environment.
Since this functionality is not critical, it seems reasonable to skip the tests in Windows environments for now.

Skip failing lz4 test on windows systems

---

CHANGES.rst
asdf/commands/__init__.py
asdf/commands/tags.py
asdf/commands/tests/test_tags.py

Add command to display tags

---

CHANGES.rst
asdf/tags/core/__init__.py
asdf/tags/core/tests/test_ndarray.py
asdf/tags/transform/compound.py
asdf/tests/__init__.py
asdf/tests/helpers.py
asdf/tests/test_asdftypes.py
asdf/tests/test_schema.py
asdf/yamlutil.py

This fixes #13. It also fixes unit tests that were producing warnings once this feature was added.
It's possible that later we will want to add an option to suppress this warning.

Issue warnings for unrecognized tags

---

CHANGES.rst
asdf/schema.py
asdf/tests/data/example_schema.json
asdf/tests/setup_package.py
asdf/tests/test_schema.py

This fixes #314 (and fixes #242 which is a duplicate). The JSON module in Python 3.5 doesn't accept `bytearray` as input, but 3.6 does. This PR adds a test and a workaround.

Fix reading json schema in Python 3.5

---

.travis.yml
appveyor.yml

This resolves #316. Instead of hard-coding the latest stable versions of `numpy` and `astropy`, use the `stable` flag provided by [astropy/ci-helpers](https://github.com/astropy/ci-helpers).
Also add a new test to the matrix covering `astropy-1.3.2` since that is now the previous stable version, not the latest.

Update travis test matrix

---

.travis.yml
docs/sphinxext/example.py

This fixes #321 by addressing the error that was preventing sphinx builds. It also updates the travis build to make sure that we build sphinx documentation in a Python 3.6 environment.
This also closes #192 since the reported warning no longer appears. It seems reasonable to assume that this has been fixed. It's also reasonable to close the issue since there have been [numerous sphinx releases](http://www.sphinx-doc.org/en/stable/changes.html) since version 1.3.5.

Fix sphinx build errors, update sphinx builds on travis

---

asdf/tests/test_schema.py
asdf/tests/test_suite.py

After a little bit of random poking around I realized that there was a set of tests that haven't been running at all. These tests run against the ASDF and YAML reference files in `asdf-standard`. They have now been cleaned up and reactivated.

Reactivate reference file tests

---

asdf/stream.py
asdf/tests/test_stream.py

These were missing, which caused problems since `Stream` inherits from `tags.core.ndarray.NDArrayType`, but does not implement all of the attributes that are used by the `__repr__` and `__str__` methods of the parent class.

Override repr and str methods in Stream

---

asdf/tests/helpers.py
asdf/tests/test_generic_io.py
asdf/tests/test_remote_data.py

This fixes #328. There are many tests in the suite that create HTTP servers of various types behind the scenes and attempt to access ASDF files from them. Prior to this PR these tests had no awareness of astropy's attempt to disable internet access when `--remote-data` is not explicitly given.
This PR allows the tests to pass without hanging. However, I'm not entirely sure why this only happened on darwin and not on linux. It makes me wonder whether there's a deeper issue, maybe even upstream in astropy.

Fix hanging tests on darwin related to remote data access

---

.travis.yml

This closes #331 by adding an OSX test to the travis test matrix. Unfortunately, since travis doesn't technically support Python builds on OSX, this required some fairly substantial changes to the config file. Thankfully, [astropy/ci-helpers](https://github.com/astropy/ci-helpers) makes it fairly easy to work around this restriction.

Add osx test to the travis test matrix

---

.travis.yml
asdf/block.py
asdf/generic_io.py
asdf/schema.py
asdf/yamlutil.py

This is necessary especially given the upcoming deprecation of Py2.

Update coverage test to run in Py3.6 instead of Py2.7

---

CHANGES.rst
asdf/asdf.py
asdf/asdftypes.py
asdf/fits_embed.py
asdf/tests/helpers.py
asdf/tests/test_asdftypes.py
asdf/tests/test_fits_embed.py
asdf/tests/test_schema.py
asdf/yamlutil.py

This PR does two things:
1. It makes version mismatch warnings silent by default
2. It enables warnings for unrecognized tags to be silenced
@nden, this seems like the right way to handle the large number of version mismatch warnings in jwst in the long term. However, I think that unrecognized tag warnings should be enabled by default, and there are a few other more serious warnings which are still not possible to silence at all.
Also, while this resolves #313 for the most part, it does not add a module-level configuration mechanism. There are too many questions about precedence that make it a little too complicated to implement without sufficient motivation. Please let me know if you disagree.

Configure warnings

---

asdf/tests/test_asdftypes.py

Title says it all. This is a minor change, although it's possible that other commits could be added here before merge.

Remove unnecessary warning capture for supported_versions test

---

.travis.yml
appveyor.yml

This also removes a test against astropy-1.3.2 using Python 3.5 from the appveyor matrix since it seems redundant.
This resolves #345.

Remove astropy-1.1.2 from test matrix, add 1.3.3

---

asdf/tags/wcs/tests/test_wcs.py
asdf/tags/wcs/wcs.py

This addresses the bugs that were revealed when updating the test matrix in #346. It fixes #347.

Fix WCS test failures in astropy v1.3.3

---

CHANGES.rst
asdf/asdftypes.py
asdf/tests/helpers.py
asdf/tests/test_schema.py

There were several issues with the type index used for writing ASDF file. These bugs were causing issues that were exposed in PR #343. This PR fixes those issues. 
One of the main problems was that items in the type index for earlier versions of the standard (i.e. `1.0.0`) were being overwritten by more recent version of the same type. This meant that files that used the earlier version of the standard were not being validated properly.
Also, this PR make sure that all of the tests of examples in schema files run against the appropriate version of the ASDF standard. It is not enough to assume in all cases that the examples can be tested against the latest version of the standard.

Fix issues with the type index for writing

---

CHANGES.rst
asdf/commands/tests/data/frames0.asdf
asdf/commands/tests/data/frames1.asdf
asdf/tags/time/tests/test_time.py
asdf/tags/time/time.py
asdf/tags/wcs/tests/test_wcs.py

This fixes #341. Time objects from astropy are now serialized correctly when they have an `EarthLocation` attribute. The proper way to implement this fix was to update the time schema to `v1.1.0`, so this PR requires https://github.com/spacetelescope/asdf-standard/pull/147 to be merged first.
This change also supports backwards compatible writing with `time-1.0.0` in order to support tests for WCS to ensure backwards compatibility with the old frame format.

Fix bug with astropy.time location, update time schema

---

.travis.yml

This will allow us to take advantage of some magic like `skip travis`, or `docs only`, or cron, etc.

Use generic setup_conda script from ci-helpers for travis

---

CHANGES.rst
asdf/asdf.py
asdf/block.py
asdf/tests/test_low_level.py

This resolves #226 and allows callers to optionally specify that underlying data blocks should not be memory mapped. Memory mapping is not possible under all circumstances (e.g. when an array is compressed), but is enabled by default if it is possible. Using `copy=True` will ensure that the array is **not** memory mapped, even if it is possible.
This does not affect ASDF-in-FITS since apparently memory mapping of FITS files depends on the HDUs and keywords that are present, so it is out of our control.

Add copy option to asdf.open

---

asdf/asdftypes.py
asdf/tests/test_schema.py

Instead of directly issuing a warning and passing the raw node back in this case, raise an exception that will be handled by `tagged_tree_to_custom_tree`, which will then use the existing warning mechanism to indicate a failure to convert the tree. This is much cleaner since it reuses mechanisms that were recently improved; and it avoids some issues that occurred when running tests against older versions of astropy.
This also helps address an issue that was uncovered by PR #343 when running against older versions of astropy.

Fix mechanism used to handle missing requirements for tag classes

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_low_level.py

This provides a convenient shortcut for accessing the ASDF tree:
```python
import asdf
tree = {'a': 10, 'b': 'foo'}
af = asdf.AsdfFile(tree)
assert af['a'] == af.tree['a']
```
This resolves #339.

Allow ASDF tree to be accessed from top-level AsdfFile object

---

.travis.yml
appveyor.yml

Start to scale back tests against Py2. Also run tests against development version of `numpy`. These tests are allowed to fail.

CI script update

---

asdf/tests/test_asdf_schemas.py
asdf/tests/test_schema.py

One file contains tests that are used for testing the schema module itself, and the other file contains tests used for testing actual ASDF schemas.

Refactor schema tests into separate files

---

CHANGES.rst
asdf/block.py
asdf/tags/core/tests/test_ndarray.py

This makes sure that inline arrays are handled properly by `get_block`, so that they can be duplicated within a file and written out properly. This fixes #368. Thanks @bobpepin for the bug report.

Fix bug when duplicating inline arrays

---

CHANGES.rst
asdf/resolver.py
asdf/schema.py
asdf/tests/test_schema.py
asdf/tests/test_yaml.py

This fixes #367 and allows tag references that use the tag URI scheme to be properly resolved in schema files.

Resolve tag references that use tag URI scheme

---

.travis.yml
appveyor.yml
asdf/tests/helpers.py
asdf/tests/test_generic_io.py
asdf/tests/test_remote_data.py

This update handles the changes that were introduced to astropy's test infrastructure in https://github.com/astropy/astropy/pull/6606. It makes sure that the appropriate test dependencies are installed on the CI servers.
In the long term, we may want to find an alternative to the use of `INTERNET_OFF` in the `assert_tree_match`.
This fixes #375.

Update usage of astropy test infrastructure

---

setup.cfg

When using the latest version of astropy, and therefore the `pytest-remotedata` plugin, it is necessary to explicitly enable strict testing of remote data access. When strict testing is enabled, it means that any test will fail that attempts to access the internet but is not marked with `@remote_data`. This was the behavior previously expected by ASDF, and we want to preserve it now.
Setting this option in `setup.cfg` will have no affect on earlier versions of asdf and astropy.
This should fix the recent test failures that appeared on the nightly cron jobs.

Enable strict remote data checking

---

asdf/tags/core/tests/test_ndarray.py

@Cadair has pointed out that it is not currently possible to serialize a `numpy` array with `dtype=object`. Consider the following  code example, which does not currently work:
```python
import asdf
import numpy as np
data = np.empty((10, 10), dtype=object)
for i, _ in enumerate(data.flat):
data.flat[i] = SomeObject(i, foo, 42)
af = asdf.AsdfFile({'data': data})
af.write_to('data.asdf')
```
In principle, it seems possible to support inline `ndarray`s that contain arbitrary object data. We should discuss whether this should be supported. In the meantime, this PR introduces unit tests that demonstrate the kind of functionality that would be expected. They are currently marked with `pytest.mark.xfail` since they will not pass.
See [this …

Test numpy array with dtype=object

---

.travis.yml
appveyor.yml

It's not longer necessary to provide a link to the branch in Astropy where ASDF tags were added. However, we are required to use the development version of Astropy for all builds now.

Update astropy version in CI scripts

---

.travis.yml
CHANGES.rst
appveyor.yml
asdf/extension.py
setup.py

This closes #378. It allows ASDF extensions to be installed and loaded using `setuptools` entry points. ASDF's own `BuiltinExtension` is now installed this way. Other packages, such as `gwcs` or `astropy` that provide ASDF extensions should use entry points to install their own extensions.
cc @Cadair

Install and load extensions using setuptools entry points

---

CHANGES.rst
appveyor.yml
setup.py

This fixes #396. It is a fairly simple solution, so it's possible that it will not work for all combinations of platforms/git versions.

Automatically initialize asdf-standard submodule in setup.py

---

CHANGES.rst
asdf/asdf.py
asdf/constants.py
asdf/exceptions.py
asdf/extension.py
asdf/resolver.py
asdf/schema.py
asdf/tests/data/foreign_tag_reference-1.0.0.yaml
asdf/tests/data/tag_reference-1.0.0.yaml
asdf/tests/test_low_level.py
asdf/tests/test_schema.py

This fixes #392. Previously it was not possible to resolve foreign tag references that were included in ASDF schemas or files. For example, if a schema in an external package made reference to `tag:stsci.edu:asdf/core/ndarray-1.0.0`, it would not be resolved properly. 
This PR combines tag mappings and url mappings into a single resolver, so that both tags and urls used as IDs can be resolved to real urls. 
@nden this change will enable schemas to move to Astropy and GWCS as appropriate.
**[edit]**
To be clear, this change applies to *fully specified* tag references like `tag:stsci.edu:asdf/core/ndarray-1.0.0`. Relative tag references within the same organization (such as `stsci.edu` worked (e.g. `!core/ndarray-1.0.0`), but these are not sufficient for use by packages that define schemas …

Allow foreign tags to be resolved in schemas and files

---

.travis.yml
CHANGES.rst
appveyor.yml
asdf/asdf.py
asdf/tests/conftest.py
asdf/tests/test_asdftypes.py
asdf/tests/test_generic_io.py
asdf/tests/test_low_level.py

This fixes #406. This also serves as a definitive answer to and closes #168. This seems like the safest approach in order to avoid inadvertently accessing memory mapped array data that is no longer available.
cc @Cadair

Disallow access to tree when file handle is closed

---

CHANGES.rst
asdf/fits_embed.py
asdf/tests/test_fits_embed.py

This fixes #404. The bug occurred specifically in the case where the ASDF file was embedded inside an HDU in a FITS file.

Fix bug that caused serialized FITS tables to be duplicated

---

MANIFEST.in
setup.py
setup_helpers.py

This moves some of the functionality that was previously in `setup.py` into a new file called `setup_helpers.py`. It also unties us a little bit more from some of the weirder parts of `astropy_helpers`. The main motivation was to stop using the parts of `astropy_helpers` that actually import `asdf` as part of the setup script, since this is generally considered to be bad practice.
As a result, this fixed a fairly minor but annoying bug that was introduced by #408.

More improvements and cleanup in setup script

---

CHANGES.rst
asdf/__init__.py
asdf/fits_embed.py
asdf/tests/test_fits_embed.py
docs/asdf/examples.rst

The motivation for this update was a problem report from the archive. They pointed out that storing ASDF metadata in an `IMAGE` HDU goes against convention and would likely lead to incorrect handling of the data when the resulting file is processed by FITS readers.
It was originally proposed to instead use the `FOREIGN` extension. However, this convention [has already been defined](https://arxiv.org/abs/1201.1829), and it seemed too restrictive to have to conform to this convention, especially since there is not already an implementation in `astropy`.
Instead, it was agreed that we would create a new `ASDF` extension for storing ASDF metadata in FITS files. This PR contains the implementation of the corresponding HDU, which is nearly identical to the `FitsHDU` in `astropy.io.fits`. In …

Use new non-standard FITS extension for ASDF-in-FITS

---

CHANGES.rst
asdf/resolver.py

This is a relatively simple fix that allows the package to be imported and used from the source directory. It also is necessary to support builds in development mode, which was only recently supported in #409.
This partially addresses #414.

Allow import and use of module from source directory and development build

---

setup.cfg

I believe the problem is at the FITS level, and so it is difficult to address in ASDF.
A better way to handle this will be available when https://github.com/astropy/pytest-openfiles/pull/10 is merged and released.

Ignore open file in FITS test for now

---

CHANGES.rst
asdf/__init__.py
asdf/external_reference.py
asdf/tags/core/__init__.py
asdf/tags/core/external_reference.py
asdf/tags/core/tests/test_external_reference.py

This is a first attempt at adding a general tag for external array references. This needs testing with things other than FITS and much more work, but it's put here for feedback.
see also spacetelescope/asdf-standard#149, fixes #369

Add an external array reference type

---

asdf/asdftypes.py

This fixes a bug that was discovered in Astropy ([here](https://travis-ci.org/astropy/astropy/jobs/336266918)). Previously there was a special case for the latest version, but this was causing issues.
cc @Cadair

Types from version map should always be added to index first

---

.travis.yml
asdf/tags/core/tests/test_complex.py
asdf/tags/core/tests/test_external_reference.py
asdf/tags/core/tests/test_history.py
asdf/tags/core/tests/test_ndarray.py
asdf/tags/wcs/tests/test_wcs.py
asdf/tests/schema_tester.py
asdf/tests/test_asdftypes.py
asdf/tests/test_compression.py
asdf/tests/test_fits_embed.py
asdf/tests/test_generic_io.py
asdf/tests/test_low_level.py
asdf/tests/test_reference.py
asdf/tests/test_schema.py
asdf/tests/test_stream.py
asdf/tests/test_suite.py
asdf/tests/test_versioning.py
asdf/tests/test_yaml.py
conftest.py
setup.cfg

This closes #245, closes #308, and closes #356.
I think this also enables us to take care of #153 if we so choose. However, this is an all-or-nothing decision. It means we won't be able to use the Astropy test runner at all (which is not necessarily a bad thing).

Improvements to test infrastructure

---

CHANGES.rst
asdf/asdf.py
asdf/schema.py
asdf/tests/data/custom_schema.yaml
asdf/tests/test_schema.py

This closes #440. It adds an argument `custom_schema` to `Asdf.open` and also the `asdf.AsdfFile` constructor. The argument value should be the path to a custom schema that will be used in a secondary validation pass. This is intended to allow users to ensure that particular ASDF files follow custom conventions beyond those enforced by the standard.
This PR can probably be merged as-is (after review), but it may be useful to provide additional features/functionality in the future.
cc @Cadair

Optional top-level validation with custom schema

---

.travis.yml
appveyor.yml

Now that `astropy-3.0` is available, run CI tests against the stable version by default. Also added test case for development version.

Test against Astropy v3.0 by default

---

CHANGES.rst
asdf/tags/core/__init__.py
asdf/tests/helpers.py
asdf/tests/test_schema.py
docs/asdf/examples.rst

This fixes #426. It removes the restrictions on the top-level `data`, `wcs` and `fits` attributes. If such restrictions are still desirable for certain files, then the `custom_schema` option introduced in #442 should be used to impose additional restrictions.
@nden, @perrygreenfield I'm not sure if we have come to a final decision about this, but I wanted to introduce the changes for comments before moving forward.
This should be merged in conjunction with https://github.com/spacetelescope/asdf-standard/pull/155.
The documentation on schema validation should be updated before this is merged.
cc @Cadair

Update core schema

---

setup.py

This is required for compatibility with newer versions of `astropy-helpers`. This should fix #447.

Disable 2to3 on v1.3.x release series

---

.gitignore
MANIFEST.in
tox.ini

While `tox` isn't a great long-term solution for testing since it doesn't currently support conda, it is useful for doing tests locally across multiple environments.

Allow basic testing with tox

---

asdf/tags/wcs/tests/data/test_frames-1.1.0.asdf
asdf/tags/wcs/tests/data/test_wcs-1.0.0.asdf
asdf/tags/wcs/tests/data/test_wcs-1.1.0.asdf
asdf/tags/wcs/tests/setup_package.py
asdf/tags/wcs/tests/test_wcs.py
tox.ini

Ever since new WCS-related schemas were updated in Astropy (https://github.com/astropy/astropy/pull/7079) and gwcs (https://github.com/spacetelescope/gwcs/pull/127), WCS-related tests have been failing in ASDF. This is because we have been attempting to round-trip older versions of files against newer schemas and tags, which doesn't make sense. Instead, we should simply try to read older files and do a few sanity checks, just to make sure that we maintain backwards compatibility when reading.

Fix failing WCS tests

---

asdf/tests/test_asdftypes.py

This fix was motivated by #304. While it does not address that issue directly, it does mean the underlying assumptions are no longer valid. So it closes #304.

Fix CustomType inheritance in custom type used in test

---

asdf/tests/test_suite.py

This fixes recent test failures.

Remove expected warning in test that is no longer occurs

---

CHANGES.rst
asdf/commands/__init__.py
asdf/commands/remove_hdu.py
asdf/commands/tests/test_remove_hdu.py

Specifically for @hbushouse. Given a file `asdf.fits` that contains an ASDF extension, here's an example of how to use it:
```
$ asdftool remove-hdu asdf.fits no_asdf.fits
```
The file `no_asdf.fits` will be created (assuming it doesn't already exist) as a duplicate of the input file but without the ASDF extension.
For usage information:
```
$ asdftool -h
$ asdftool remove-hdu -h
```

Add command to asdftool for removing ASDF extension from FITS file

---

asdf/asdf.py
docs/conf.py

Whilst working on the Reproducible Builds effort [0], we noticed that `asdf` could not be built reproducibly.
This is due to it including nondeterminstically random output as well as the current build time in the documentation.
This was originally filed in Debian as #895737 [1].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/895737
Signed-off-by: Chris Lamb <lamby@debian.org>

Make the build reproducible

---

CHANGES.rst
asdf/extension.py

This allows the package to be tested in environments where it can't first be installed (e.g. the Debian build environment).
In order to make this work, simply define `ASDF_TEST_BUILD` before running `pytest`. 
@olebole this should solve the issue you reported in #498 and #499. I hope to release this in bugfix v2.0.1 sometime this week.

Allow test suite to run even when package is not installed

---

asdf/__init__.py
asdf/fits_embed.py
asdf/tests/test_fits_embed.py

This is intended to resolve https://github.com/STScI-JWST/jwst/issues/1807. After contacting NASA's FITS office, it seems like we should avoid the use of `FOREIGN` since it is an old convention and is not well supported. In fact, it does not seem to be properly validated by `fitsverify`.
cc @stscicrawford, @hbushouse, @perrygreenfield

Use BINTABLE HDU for storing ASDF-in-FITS

---

asdf/tags/wcs/tests/test_wcs.py

These tests appear to fail when using the latest release of GWCS (`0.9.0`) and the latest release of Astropy (`3.0.2`). It appears to work fine with the latest development version of Astropy, however.
This PR simply skips the failing tests when the incompatible versions are present.

Fix wcs tests with incompatible version of Astropy and GWCS

---

CHANGES.rst
asdf/generic_io.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py

The solution in this PR is simply to create a contiguous copy of the broadcasted array and save it to disk. While this uses more memory on disk than strictly required by `numpy`, we need to account for the fact that broadcasting is a concept that is specific to `numpy` and may not translate to other implementations of ASDF. For this reason, it seems to make the most sense to create a copy of the broadcasted array so that it is available for other implementations.
This fixes #506.
cc @Cadair

Allow serialization of broadcasted ndarrays

---

.travis.yml
appveyor.yml
asdf/commands/tests/data/__init__.py
asdf/commands/tests/test_diff.py
asdf/tags/core/tests/data/__init__.py
asdf/tags/core/tests/test_ndarray.py
asdf/tags/wcs/tests/data/__init__.py
asdf/tags/wcs/tests/test_wcs.py
asdf/tests/data/__init__.py
asdf/tests/helpers.py
asdf/tests/test_asdftypes.py
asdf/tests/test_fits_embed.py
asdf/tests/test_schema.py

This is similar in concept to #514, except it is applied to test data files rather than the schemas.

Use importlib resources for accessing test data.

---

CHANGES.rst
asdf/fits_embed.py

Store ASDF-in-FITS data in 1x1 BINTABLE HDU

---

CHANGES.rst
asdf/generic_io.py

This resolves #520. It appears to be related to a [known issue in Python](https://bugs.python.org/issue24658).
Bringing the chunk size below the problematic 2GB threshold appears to fix the issue, at least as reported in #520. I'm not sure whether it's worth adding a test for this since it would require writing a 2GB+ file on a VM in travis...

Fix OSX write limit as workaround for known Python bug

---

CHANGES.rst
asdf/asdf.py
asdf/schema.py
asdf/tests/data/custom_schema_definitions.yaml
asdf/tests/test_schema.py

Custom schema validation was working previously, but only in certain limited cases. This makes custom schema validation more correct and robust.

Fix bug with out-of-line definitions when using custom schemas

---

CHANGES.rst
asdf/__init__.py
asdf/tags/core/tests/test_complex.py

This PR addresses several outstanding problems with the schema for complex numbers. It adds much more thorough tests of the schema and ensures that improperly formatted complex numbers are detected by a schema validation error (which was not previously the case).
In a way, this is a fairly substantial change since it imposes much more stringent requirements on the format of complex numbers. However, since these requirements were implicit to begin with and should have been enforced in the first place, it seems unlikely that anyone is using files that are in conflict with the new rules.
This is closely related to https://github.com/spacetelescope/asdf-standard/pull/171 and integrates the updates to the schema that were introduced there.

Update complex number schema and add tests

---

.travis.yml
setup.py

Now that `jsonschema` has an alpha release for 3.0, we need to restrict the maximum version of our dependency since the latest version appears to cause issues.
This PR also adds a test to travis that uses the latest version of jsonschema (it's allowed to fail for now).

Restrict jsonschema version to avoid using alpha release

---

CHANGES.rst
asdf/block.py
asdf/tests/test_fits_embed.py

This is to close out references to memory-mapped arrays that,
in the current context, not associated with a file. The `Block._memmapped`
is `False` but the `.data` is a memory-mapped array.
WIP spacetelescope/jwst#2282

Ensure when closing, to explicitly close data blocks

---

CHANGES.rst
asdf/asdf.py
asdf/reference.py
asdf/tests/helpers.py
asdf/tests/test_yaml.py
asdf/treeutil.py
setup.cfg

This allows to serialize `typing.NamedTuple`-s and other crazy inheritors from `list` and `tuple` which do not preserve the original constructor signature.
We catch `TypeError` in the constructor and use the auxiliary list.

Allow typing.NamedTuple to be serialized

---

CHANGES.rst
asdf/block.py
asdf/generic_io.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py

Allow fortran-order arrays to be serialized

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_low_level.py

Add top-level keys method to access tree keys

---

CHANGES.rst
asdf/asdf.py
asdf/tags/core/tests/test_history.py

Previously, extension metadata was not being tracked properly for the following use case:
```python
import asdf
af = asdf.AsdfFile()
af.tree['foo'] = ObjectUsingExternalExtension()
af.write_to('foo.asdf')
```
Extension metadata was only being recorded for the case where the fully constructed tree was passed to the `AsdfFile` constructor. This PR updates a test to make sure it works for both cases.

Make sure extension metadata is written in all cases

---

CHANGES.rst
asdf/schema.py
asdf/tests/test_schema.py

Properly validate large numpy integer literals

---

asdf/tests/test_asdftypes.py

This PR adds a test to make sure that ASDF-provided tags are properly overridden if/when an external package provides an extension with the same type. The test case used here is `gwcs`, although `astropy` could also be used.
cc @nden

Add sanity check for extension override

---

CHANGES.rst
asdf/asdftypes.py
asdf/extension.py
asdf/tests/test_asdftypes.py
asdf/tests/test_fits_embed.py
asdf/tests/test_schema.py

ASDF provides some built-in types. When an external extension is found that serializes the same types, that extension should override the corresponding built-in types. However, this wasn't happening in cases where the type to be serialized was actually a subclass of an extension type. This PR fixes that.
While fixing this, some other issues with the test infrastructure were exposed, which are also fixed here.
This PR still does **not** allow subclasses of extension types to be roundtripped. Instead, if a subclass is serialized, when reading the file, the base class serialized by the extension will be returned. This latter functionality will be forthcoming in a future PR.
This partially addresses #555.
cc @nden

Fix issue causing subclass to be serialized by wrong extension

---

.travis.yml
appveyor.yml
asdf/conftest.py
asdf/tests/__init__.py
asdf/tests/conftest.py
asdf/tests/test_generic_io.py
asdf/tests/test_suite.py
conftest.py

Also update CI matrices to test against newer versions of pytest and python.

Address warnings when using pytest 3.8

---

CHANGES.rst
asdf/schema.py
asdf/tests/test_schema.py

Previously an error occurred in the case where a node was tagged with a type from a known extension, but the type itself was unknown. This could happen, for example, in the case where the type is provided by a more recent version of a package, but only the older version of the package is installed.
Now, just a warning occurs, and the affected node is returned as a basic Python tree.

Allow tree to be created even when schema is missing

---

CHANGES.rst
asdf/asdf.py
asdf/block.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/helpers.py

This allows loading ASDF files, then closing the file
and still retaining full access to the tree objects.
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

Add lazy_load parameter to open()

---

CHANGES.rst
asdf/__init__.py
asdf/asdf.py
asdf/schema.py
asdf/tags/core/__init__.py
asdf/tags/core/integer.py
asdf/tags/core/tests/test_integer.py
asdf/tests/test_schema.py
asdf/versioning.py
docs/asdf/features.rst

Add support for arbitrary precision integers

---

CHANGES.rst
asdf/__init__.py
asdf/asdf.py
asdf/block.py
asdf/commands/defragment.py
asdf/commands/diff.py
asdf/commands/exploded.py
asdf/commands/tests/test_defragment.py
asdf/commands/tests/test_to_yaml.py
asdf/commands/to_yaml.py
asdf/extern/atomicfile.py
asdf/fits_embed.py
asdf/generic_io.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_complex.py
asdf/tags/core/tests/test_ndarray.py
asdf/tags/wcs/tests/test_wcs.py
asdf/tests/helpers.py
asdf/tests/schema_tester.py
asdf/tests/test_asdftypes.py
asdf/tests/test_compression.py
asdf/tests/test_fits_embed.py
asdf/tests/test_generic_io.py
asdf/tests/test_low_level.py
asdf/tests/test_reference.py
asdf/tests/test_schema.py
asdf/tests/test_stream.py
asdf/tests/test_yaml.py
docs/asdf/features.rst
docs/sphinxext/example.py

This resolves #578 (albeit indirectly) and resolves #574.
It refactors the top-level `asdf.open` function into a standalone factory function in order to enable better decisions about handling file modes, particularly with respect to memory mapping. It also deprecates the use of `asdf.AsdfFile.open`, since this was not capable of handling such decisions.
There's still a bit more work:
Even though this is technically a bug fix, it affects the API and is a big enough change that it should go in 2.2.0.

Refactor, better mode handling, deprecate asdf.AsdfFile.open

---

asdf/asdf.py

This resolves #469.
Thanks to #579, this error should occur less often since by default `asdf.open` will attempt to determine the appropriate write mode for the file. In most cases, the default mode will be `'rw'`.

Better error message for AsdfFile.update in readonly mode

---

asdf/tests/schema_tester.py
setup.cfg

This fixes #592.
It requires https://github.com/spacetelescope/asdf-standard/pull/181 to be merged first.

Update schemas to reflect removal of domain from Astropy

---

asdf/asdf.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_low_level.py

The `asdf.open` API now uses a more sensible default mode (related to #578). This fixes #602.
cc @jdavies-st, @bernie-simon

Fix default mode assumption when opening files with new API

---

.travis.yml
setup_helpers.py

This is intended to fix #605 and also to fix rendering of the README on pypi. It seems nearly impossible to test without another release, unfortunately.

Fix readme render

---

.travis.yml
appveyor.yml

The main motivation for this is that the Astropy test runner was no longer running schema tests. I have no interest in making this work.

Stop using Astropy test runner

---

CHANGES.rst
asdf/asdf.py
asdf/block.py
asdf/tests/helpers.py
asdf/tests/test_low_level.py
docs/asdf/arrays.rst

This feature has proved to be too problematic to be supported in an official release. The semantics are unfortunately rather complicated due to the fact that the same `AsdfFile` object can be used both for reading and for writing. It also turns out that there already exists an option to `write_to` called `auto_inline` that serves a similar purpose, although I believe it may not be working properly in all cases (see #599).
Also, to complicate matters further, neither `inline_threshold` nor `auto_inline` are idempotent, meaning that both modify the underlying `AsdfFile` object in undesirable ways. This has exposed some significant design warts in the `asdf` API and implementation that need to be addressed, although that will be difficult and will probably lead to significant user-facing …

Revert inline threshold option

---

appveyor.yml
asdf/tests/test_api.py

The test currently is marked with `xfail` until this issue is resolved.

Add a test that exposes issues revealed with auto_inline

---

conftest.py

We already have a test dependency on Astropy, so this is not a problem.

Use astropy display plugin for pytest

---

.travis.yml
tox.ini

Now that a prototype of [tox-conda](https://github.com/drdavella/tox-conda) is available, we can try using it on CI. This has several major benefits:
* greatly simplifies the CI config file
* allows any test environment used by CI to be exactly reproduced locally, which should make debugging much easier

Use tox for testing

---

asdf/tests/schema_tester.py

Fix bug preventing schema tester from running on Windows

---

.travis.yml
tox.ini

This should fix the recent cron failures on travis.

Pin version of gwcs to ~=0.9.1 for older versions of Astropy

---

tox.ini

This should ensure that we always get the latest versions of `pytest-astropy` and its dependencies, even if the `conda` recipes are not yet up-to-date.
As a philosophical issue, there's really no reason we shouldn't prefer getting most dependencies from `pypi` instead of `conda` anyway.

Install pytest-astropy from pip instead of from conda

---

asdf/tests/test_yaml.py

This reproduces the issue reported in #642. This is a bug in `pyyaml`, but would be handled properly if we switched to `ruamel.yaml` (see #391).

Add test for trees with tuple keys

---

CHANGES.rst
asdf/asdf.py

Previously this option was not being passed through when opening an ASDF-in-FITS file using the top-level API.

Pass ignore_unrecognized_tag option to ASDF-in-FITS

---

asdf/tests/test_reference.py

Came up in https://github.com/astropy/astropy/issues/8464.
cc @olebole

Mark external_reference_invalid test with remote_data

---

CHANGES.rst
asdf/schema.py

Prior to this change the YAML meta-schema ID was hard-coded into the `check_schema` routine which is used by the schema tester. This ID is still used as a fallback if the `$schema` keyword is not present, however.

Use $schema keyword to determine metaschema to use for schema tests

---

CHANGES.rst
asdf/schema.py

This is a follow-on to #654. Now that we are properly performing meta-schema validation, it is important to use all available resolvers when loading schemas. Previously, only schemas from the ASDF Standard were resolvable in this way.

Make schema validation resolver use installed extensions

---

asdf/yamlutil.py

Update to fix test failures caused by update to pyyaml-5.1

---

.travis.yml
asdf/conftest.py
conftest.py
tox.ini

Test against legacy and prerelease versions of dependencies

---

CHANGES.rst
asdf/schema.py
asdf/tests/test_schema.py

Allow use of pathlib.Path objects for custom_schema option

---

.travis.yml

There appears to be an incompatibility between `tox-conda` and the latest release of `tox` which is causing the CI failures. See https://github.com/tox-dev/tox-conda/issues/15 for discussion.

Set tox version to avoid buggy release

---

.travis.yml
tox.ini

This is a follow-on to #665. Now that a new version of `tox-conda` has been released, we should depend on that instead of fixing the version of `tox` itself.

Update to reflect release of new tox-conda

---

asdf/tags/core/tests/test_ndarray.py
asdf/tests/schema_tester.py
setup.cfg

This eliminates a few overlooked cases in tests where `yaml.load` was being used instead of `yaml.safe_load`.  There are still a few other instances of `yaml.load` in various places, but these all explicitly pass a safe loader in as an argument.

Use yaml.safe_load in test cases

---

README.rst
tox.ini

Trying to wean ourselves off of `conda` a little bit here. It's not necessary to use it to install dependencies, even if we're still using `tox-conda` for environment management. The current advantage of that is it allows us to run Py35 tests on Travis even though the Travis image doesn't have Python 3.5 installed.

Don't use conda to install tox deps. Update documentation.

---

.gitignore

Does just what it says.  It *may* have been that actually `eggs` was a typo and it was supposed to be `.eggs`?  But just in case I figured I'd make it a separate entry...
(Encountered when doing `python setup.py build`)

add .eggs to gitignore

---

CHANGES.rst
asdf/schema.py
asdf/tags/core/__init__.py
asdf/tests/__init__.py
asdf/tests/test_asdftypes.py
asdf/tests/test_schema.py
asdf/types.py
docs/asdf/extensions.rst

This resolves #446 and also resolves #555.
More work is required, and there also needs to be some more discussion in order to determine whether this would better be supported by some updates to the standard. Also, we need to evaluate current examples in GWCS, Astropy, and possibly Sunpy to evaluate how this can be improved.
cc @nden, @Cadair

Use decorators to serialize subclasses of known custom types

---

asdf/reference.py

The `collections.Sequence` is just a deprecated alias and will be removed in Python 3.8.  It's been available since Python 3.3, so I don't think this changes anything about asdf's support for Python versions.

Use collections.abc.Sequence instead of collections.Sequence

---

CHANGES.rst
asdf/compat/jsonschemacompat.py
asdf/schema.py
setup.cfg

Addresses #530 
In its current state, this PR isn't compatible with jsonschema < 3, due to some (relatively minor) changes to `validators.create(...)`.  It would be straightforward to support both, but I thought I'd keep it clean unless I hear otherwise.
I installed this and ran the unit tests on jwst, gwcs, and astropy.  With the changes in https://github.com/spacetelescope/jwst/pull/3705, they all pass.

Upgrade jsonschema to 3.0.1

---

README.rst

Following the install docs for the dev version fails with "error: package directory 'asdf-standard/schemas' does not exist" because the `asdf_standard` subpackage does not get downloaded with `git clone https://github.com/spacetelescope/asdf`.
I added a separate command to do this (`git submodule update --init`), but one could alternatively
add a flag in `git clone`, i.e.:
`git clone --recurse-submodules https://github.com/spacetelescope/asdf`

Update install docs to include submodule initialization

---

tox.ini

The Travis tests are failing because `pytest 5.1` removed `getfuncargvalue`.  This has been fixed upstream in `pytest-doctestplus` (https://github.com/astropy/pytest-doctestplus/pull/63).  This is a workaround to limit `pytest <5.1` until a new version of `pytest-doctestplus` is released.
(I'm repeatedly getting emails for the failing Travis cron jobs because I was the last committer).

Fix failing tests due to pytest 5.1

---

asdf/tests/test_schema.py
conftest.py
setup.cfg

Fixes the following warning
```
./site-packages/_pytest/mark/structures.py:332
./site-packages/_pytest/mark/structures.py:332: PytestUnknownMarkWarning: Unknown pytest.mark.importorskip - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
PytestUnknownMarkWarning,
```
Plus some updates to testing infrastructure.

Fix test warnings; remove cruft

---

CHANGES.rst
asdf/versioning.py
setup.cfg

Fixes #702
This PR replaces `SpecItem` with `SimpleSpec` (both from `semantic_version`).
It also fixes the semantic_version to >= 2.8 . This is a backwards incompatible change in `semantic_version` so if we need to support earlier versions more changes will be needed.
@olebole Do you think support for earlier versions is needed?

replace SpecItem with SimpleSpec

---

CHANGES.rst
asdf/asdf.py
asdf/extension.py
asdf/resolver.py
asdf/schema.py
asdf/tests/test_api.py
asdf/tests/test_generic_io.py
asdf/tests/test_resolver.py
asdf/tests/test_schema.py

This PR does the following:
- `AsdfFile.resolver` is now a property instead of a method, so caching it does not prevent the `AsdfFile` from being garbage collected.  The property returns an instance of `ResolverChain`, which is callable, so this change will hopefully be transparent to users.
- Fix Resolver's hash behavior
- Add `extension.get_default_resolver` for retrieving the default resolver without first instantiating an `AsdfFile`
- Deprecate `resolvers.default_url_mapping`, `resolvers.default_tag_to_url_mapping`, and `resolvers.default_resolver`, since none of these include mappings from loaded extensions
- Deprecate `extension.default_ext_resolver` because `load_schema` won't recognize it as identical to the default `ResolverChain`
- Deprecate `resolver.Resolver.add_mapping` …

Fix load_schema memory issue and add convenience function for fetching the default resolver.

---

CHANGES.rst
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py

This is the start of a fix for https://github.com/spacetelescope/asdf/issues/711.
When an asdf file is updated, we call [calculate_updated_layout](https://github.com/spacetelescope/asdf/blob/cfa6a039d2e8c5dc93f2fd52e7d0faa9c7b16d51/asdf/block.py#L1253), which shuffles blocks around the file as needed to make room for the expansion of the tree and changes to the other blocks.  When a block gets moved, its underlying memory map is closed and then reopened in the new location.
This is a problem for NDArrayType, which keeps a [memoized copy](https://github.com/spacetelescope/asdf/blob/d8d8b3b62b7a3a6e0ce06dc83708b4c4fb807935/asdf/tags/core/ndarray.py#L251) of an ndarray that is built on top of that mmap.  The segfault occurs when the tree calls `__repr__` on the ndarray.
This PR gives …

Refresh NDArrayType when underlying mmap is closed

---

asdf/tests/test_schema.py
pytest_asdf/plugin.py

It turns out there's already an example in pytest_asdf of ignoring a schema test for older versions of astropy.

Ignore failing schema tests on astropy < 4.0

---

CHANGES.rst
asdf/exceptions.py

Currently, if `AsdfDeprecationWarning` appears, it doesn't show up if one is trying to filter `DeprecationWarning`. If I turn `DeprecationWarning` into exceptions:
```
pytest -W "error::DeprecationWarning"
```
it does not catch `AsdfDeprecationWarning` as it should.
This PR properly subclasses it so it will.

Make AsdfDeprecationWarning a subclass of DeprecationWarning

---

.travis.yml
CHANGES.rst
asdf/tests/test_api.py
tox.ini

This adds a job to the Travis build that runs the tests against an installed asdf package, which should help us catch issues like https://github.com/spacetelescope/asdf/issues/731.
I'll also fix that failing test, but I want to see it fail on Travis first, so I'm opening the PR early.

Add tox environment that runs tests against an installed asdf package

---

CHANGES.rst
asdf/extension.py
asdf/extern/atomicfile.py
asdf/generic_io.py
asdf/tests/coveragerc
asdf/types.py
asdf/util.py
setup.cfg

This removes our dependency on six, which shouldn't be necessary since we dropped Python 2 support.
Resolves https://github.com/spacetelescope/asdf/issues/724

Remove six dependency

---

setup.cfg

Looks like asdf doesn't even install on Python < 3.5, so setup.cfg should reflect that.

Update setup.cfg minimum Python version

---

CHANGES.rst
asdf/asdf.py
asdf/schema.py
asdf/tests/data/custom_schema_definitions.yaml
asdf/tests/data/custom_schema_external_ref.yaml
asdf/tests/test_schema.py
docs/asdf/features.rst

Previously, external references in custom schemas were not being resolved (see https://github.com/spacetelescope/asdf/issues/683).  This was clearly deliberate, though I can't think of a reason why that would be the desired behavior.  This PR changes the custom schema behavior to resolve external references, and fixes an issue in the tests that prevented the example custom schema from resolving correctly.
Resolves https://github.com/spacetelescope/asdf/issues/683

Resolve external references in custom schemas

---

.travis.yml
tox.ini

Changes:
- Drop conda from the Travis environment.  It's not compatible with s390x, and anyway installing it slows the builds considerably.
- Add s390x to the included builds, to support troubleshooting #235 and prevent regressions in the future.
- Upgrade most builds to Python 3.8
- Move Windows out of allowed failures
I also confirmed that at least one build is running with Astropy 4.0 and numpy 1.18.x.
Resolves #717

Clean up tox and travis configs, add new builds

---

.travis.yml
asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_array_blocks.py

These were mostly failing because dtypes default to the endian-ness of the host platform, and we were making assertions in tests assuming little-endian.  Branched off of #740, so we should merge that one first.
Resolves #235

Fix tests on s390x

---

CHANGES.rst
asdf/__init__.py
asdf/_convenience.py
asdf/_display.py
asdf/asdf.py
asdf/commands/__init__.py
asdf/commands/info.py
asdf/commands/tests/test_info.py
asdf/search.py
asdf/tests/test_api.py
asdf/tests/test_search.py
asdf/tests/test_treeutil.py
asdf/tests/test_util.py
asdf/treeutil.py
asdf/util.py
docs/asdf/asdf_tool.rst
docs/asdf/features.rst
docs/asdf/user_api.rst

This adds:
- `asdf.info(...)` for displaying a summary rendering of an ASDF tree in the console
- `asdftool info` subcommand that displays the same rendering from the commandline
- `AsdfFile.search(...)` for interactively searching an ASDF tree
Resolves #644

Add asdf.info and AsdfFile.search prototypes

---

CHANGES.rst
asdf/asdf.py
asdf/tags/core/__init__.py
asdf/tags/core/complex.py
asdf/tags/core/constant.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_history.py
asdf/tests/helpers.py
asdf/tests/test_extension.py
asdf/tests/test_fits_embed.py
asdf/tests/test_versioning.py
asdf/types.py
asdf/versioning.py
asdf/yamlutil.py
docs/asdf/developer_versioning.rst
docs/index.rst
pytest_asdf/plugin.py

This PR updates the asdf-standard pointer to latest master, and adds some tests to ensure that each of the ASDF Standard versions are fully supported.  Happily, only one of the core schemas was updated since 1.0.0.  Here's a summary of the changes:
- Fix handling of history entries for ASDF Standard 1.0.0.  Previously we had claimed to support 1.0.0, but bugs in the `AsdfType` subclass definitions resulted in corrupted 1.0.0-ish files being written.  Probably we should drop this version of the standard in library 3.0.
- Separate `AsdfObjectType` from `AsdfObject`.  This is the one core schema that received an update, and it turns out the library doesn't gracefully handle `AsdfType` classes that support multiple versions and (de)serialize themselves.  I think we should separate the …

Add versioning documentation and tests, fix versioning issues

---

CHANGES.rst

This advances the asdf-standard commit pointer to the current master, which I'll use in the 2.5.2 release.

Update asdf-standard pointer to latest

---

CHANGES.rst
asdf/generic_io.py

Hi there,
I was looking at some anomalies in the lz4 decompression performance, which led me in a roundabout way to find this bug.  Basically, `GenericFile.read_blocks()` was reading more than the requested amount, causing the decompressor to start reading an extra compression block, the first int of which is the size of the compression block.  The lz4 decompressor would then allocate a `bytearray` of this size, which is zero-initialized.  So it was sometimes doing a `memset()` of up to 4 GB, which is a noticeable performance hit!  I think this could also have resulted in corrupted data reads, but that would require the "random" int value to be less than 4K (the file system block size).  I think all the other compressors were at similar risk, depending on how big their internal buffers …

Fix generic_io read_blocks() reading past the requested size

---

CHANGES.rst
asdf/versioning.py

This PR updates the asdf-standard to latest master and adds support for version 1.5.0 (but doesn't promote it to the default version, yet).

Update asdf-standard pointer and add version 1.5.0

---

CHANGES.rst
asdf/compat/numpycompat.py
asdf/schema.py
asdf/tests/test_schema.py
asdf/tests/test_yaml.py
asdf/yamlutil.py

This PR enables validation and/or serialization of `numpy.str_`, `numpy.bytes_`, `numpy.floating`, and `numpy.integer` values.  These values will now all validate against the relevant jsonschema types, and serialize to YAML primitives.

Enable validation/serialization of numpy scalar types

---

CHANGES.rst
asdf/asdf.py
asdf/reference.py
asdf/schema.py
asdf/tags/core/__init__.py
asdf/tags/core/integer.py
asdf/tags/core/ndarray.py
asdf/tests/data/fraction_with_inverse-1.0.0.yaml
asdf/tests/test_asdftypes.py
asdf/tests/test_fits_embed.py
asdf/tests/test_reference.py
asdf/tests/test_schema.py
asdf/tests/test_treeutil.py
asdf/tests/test_yaml.py
asdf/treeutil.py
asdf/types.py
asdf/yamlutil.py
docs/asdf/extensions.rst

This PR fixes a variety of issues related to serialization/deserialization of "implicit references", that is to say, references to the same object id that aren't explicitly wrapped in `asdf.reference.Reference`.  Changes include:
- Fix infinite loops and preserve implicit references through calls to `walk_and_modify` (this is what fixes `custom_tree_to_tagged_tree` and `tagged_tree_to_custom_tree` as well as loading schemas containing reference cycles).
- Fix infinite loops when deserializing reference cycles in our custom YAML loader
- Fix infinite loops when validating trees containing reference cycles in our custom jsonschema validator
- Eliminate need to call `custom_tree_to_tagged_tree` within extension code; instead, any nested custom types returned by a `ExtensionType` subclass …

Support (de)serialization of custom objects containing implicit references

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_api.py

@stscieisenhamer pointed out a bug in adding a history entry to a file that was previously saved without them.  This PR fixes that issue and adds a relevant test.

Fix history entries initialization

---

asdf/versioning.py

... and make 1.5.0 the default standard.

Set submodule pointer to the release candidate of asdf-standard

---

CHANGES.rst
docs/asdf/developer_overview.rst

This is to describe the significant design changes for 2.6.0 to handle internal references and circular references. Only affects the documentation.

Update developer overview documentation

---

CHANGES.rst
docs/asdf/changes.rst

Add today's date to CHANGES.rst, and a `What's new in ASDF 2.6.0?` section to the docs

Update changelogs for 2.6.0 release

---

CHANGES.rst
asdf/commands/diff.py
asdf/commands/tests/data/simple_inline_array.diff
asdf/commands/tests/data/simple_inline_array0.asdf
asdf/commands/tests/data/simple_inline_array1.asdf
asdf/commands/tests/test_diff.py

This PR fixes a bug in the diff tool, which wasn't able to handle a serialized ndarray in "simplified" form, meaning an array that is serialized like this:
```
array: !core/ndarray-1.0.0 [0, 1, 2]
```
Instead of the usual:
```
array: !core/ndarray-1.0.0
data: [0, 1, 2]
datatype: int64
shape: [3]
```
Both are permitted by the ndarray-1.0.0 schema.  I noticed this when working on fixing issues with schema defaults -- the frame-1.1.0 schema's defaults are represented in the simplified form, and once they start appearing in files, tests in tests_diff.py start failing.

Fix diffing of simplified ndarray

---

CHANGES.rst
asdf/tagged.py
asdf/tests/test_tagged.py

The current behavior:
```
In [1]: from asdf.tagged import TaggedList; from copy import deepcopy
In [2]: foo = TaggedList([1, 2, 3])
In [3]: deepcopy(foo)
Out[3]: [1, 2, 3, 1, 2, 3]
In [4]: deepcopy(deepcopy(foo))
Out[4]: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
```
This has something to do with the `TaggedList` class inheriting from both `list` and `UserList`, but we can't drop `list`, because code elsewhere is probably relying upon this:
```
In [5]: isinstance(foo, list)
Out[5]: True
```
Which isn't the case when we inherit from `UserList` only -- users are expected to check `collections.abc.Sequence` instead.  I'm in favor of dropping list eventually, but that seems like a 3.0 change.
This PR overrides `__deepcopy__` to correct the issue with `UserList`.  It does the same on `UserDict`, …

Fix deepcopy of TaggedList

---

CHANGES.rst
asdf/asdf.py
asdf/schema.py

When we fixed caching of schema objects in #682, we had to continue returning unique copies of those objects from `load_schema`, since a certain package (ahem, jwst) was mutating some schemas and thereby corrupting the cache.  That copy isn't necessary within asdf, since it doesn't mess with schemas once they're loaded, but at the time I didn't think to skip the copy step internally.
It turns out that copy adds a significant performance penalty in the validator, where schemas are loaded by tag for every tagged object in an asdf file.  For files with complex trees, making deep copies about doubles the read time!  So, this PR changes internal calls to `load_schema` to `_load_schema_cached`, which dodges the copy.
I tested this with the asdf file described …

Improve validation performance by avoiding deep copy

---

CHANGES.rst
asdf/asdf.py

While I was profiling validation to assess the value of #570, I noticed this unrelated opportunity for a significant speedup (~ 13% less time for complex files).  When the tree is first read, it's already in tagged form.  Then we modify it twice: once to wrap `$ref` fields in `reference.Reference` objects, and again to fill in defaults from the schema.  From the validator's point of view, neither of these steps wrecks the tagged form of the tree, since references are ignored during validation, and the schema defaults are already tagged objects.
Given that, we can proceed to validation without first calling `yamlutil.custom_tree_to_tagged_tree` on the tree, which is an expensive operation.

Improve read performance by skipping rebuild of tree before validation

---

CHANGES.rst
asdf/asdf.py
asdf/fits_embed.py
asdf/tests/test_api.py
asdf/tests/test_fits_embed.py

This PR adds a flag to `asdf.open` and `fits_embed.AsdfInFits.open` that disables validation on read, for situations when the file is already known to be valid and the user wishes to avoid the performance penalty of an unnecessary validation pass.
Resolves #565

Add flag to skip validation on read

---

CHANGES.rst
asdf/asdf.py
asdf/commands/tests/data/frames0.asdf
asdf/commands/tests/data/frames1.asdf
asdf/schema.py
asdf/tests/test_asdftypes.py
asdf/tests/test_schema.py
asdf/yamlutil.py

This PR combines filling defaults and validation on read into a single pass, when both are enabled, and the same treatment for removing defaults and validation on write.  This improves performance since until now we've been walking the tree and schema twice.
Branched off of #792, so probably worth waiting for that one to merge before reviewing this.
Resolves #570

Validate and fill/remove defaults in a single pass

---

.travis.yml
CHANGES.rst
asdf/commands/tests/test_info.py
asdf/tests/helpers.py
pytest_asdf/plugin.py
setup.cfg
tox.ini

This fixes or hides the following warnings that come up when running our tests:
```
PytestDeprecationWarning: direct construction of AsdfSchemaFile has been deprecated, please use AsdfSchemaFile.from_parent
PytestDeprecationWarning: direct construction of AsdfSchemaItem has been deprecated, please use AsdfSchemaItem.from_parent
PytestDeprecationWarning: direct construction of AsdfSchemaExampleItem has been deprecated, please use AsdfSchemaExampleItem.from_parent
```
The pytest plugin has been updated to use `from_parent` when available.
```
AsdfConversionWarning: tag:stsci.edu:asdf/wcs/celestial_frame-1.1.0 is not recognized, converting to raw Python data structure
AsdfConversionWarning: tag:stsci.edu:asdf/wcs/icrs_coord-1.1.0 is not recognized, converting to raw Python data structure
``` …

Eliminate warnings from test suite

---

CHANGES.rst
asdf/block.py
asdf/tests/test_api.py

This fixes auto_inline's behavior when a block is already set to inline, and the associated array exceeds the limit for inline representation.  Previously the block would continue to be written inline, but with these changes it will change to "internal".
I'm also removing an unused internal method, `_should_inline`, which is a remnant of the similar inline_threshold feature that was reverted.
Resolves #599

Fix auto_inline when block is already set to inline

---

asdf/tests/helpers.py
asdf/tests/test_asdftypes.py
asdf/tests/test_fits_embed.py
asdf/tests/test_generic_io.py

Turns out with a few small adjustments we don't need to skip these tests on Windows.  I suspect the Travis environment may have disabled the firewall since last time someone tested this, and the path manipulation stuff is straightforward enough if we use a cross-platform utility instead of constructing paths ourselves.

Enable tests on Windows

---

setup.cfg

The new version stops automatically ignoring import errors on collection.  This causes a failure at collection time due to missing dependencies for docs/sphinxext.  We don't have any docstrings or tests in docs/sphinxext anyway, so I'm just going to ask pytest to ignore that directory.

Fix collection issues with doctestplus 0.7.0

---

CHANGES.rst
asdf/asdf.py
asdf/extension.py
asdf/schema.py
asdf/tags/core/tests/test_history.py
asdf/tests/helpers.py
asdf/tests/test_api.py
asdf/tests/test_fits_embed.py
asdf/tests/test_helpers.py
asdf/tests/test_schema.py
asdf/tests/test_types.py
asdf/tests/test_yaml.py
asdf/treeutil.py
asdf/type_index.py
asdf/types.py

Many of our warnings are `UserWarning` instead of `AsdfWarning` of some kind, which makes it difficult for users to squelch warnings from the whole package all at once.  This converts all previously untyped warnings to `AsdfWarning` and cleans up warning checks in the tests, which weren't making effective use of the `pytest.warns` match parameter.

Use AsdfWarning instead of UserWarning

---

CHANGES.rst
asdf/asdf.py
asdf/tests/helpers.py
asdf/tests/test_fits_embed.py
asdf/tests/test_schema.py
asdf/tests/test_types.py
asdf/tests/test_yaml.py
asdf/type_index.py
asdf/yamlutil.py
pytest_asdf/plugin.py

This PR fixes a number of issues related to the version mismatch warning:
- Move the cache of previously emitted warnings from TypeIndex to AsdfFile, avoiding accumulation of AsdfFiles in memory
- Make the version mismatch warning message more useful by including the tag that was chosen as a fallback.  I also added a note stating that the fallback behavior is deprecated and will be removed in 3.0.
- Start warning even when only the schema patch version is different.  A patch version is likely to include new fields that would be discarded by an older ExtensionType implementation, so modifying the file may cause unintended data loss.
- Stop warning simply because a file contains a tag with a supported but older version.  That doesn't seem useful.
- Stop coercing tag versions in the YAML …

Clean up version mismatch warning

---

CHANGES.rst
asdf/compat/jsonschemacompat.py
asdf/schema.py
docs/asdf/install.rst
setup.cfg
tox.ini

This PR drops support for jsonschema 2.x, in anticipation of needing 3.x for draft-07.
I also compared tox.ini, setup.cfg, and the documentation, and noticed a few discrepancies.  I chose the highest minimum versions from among them and updated everything to match.

Remove jsonschema 2.x support and update minimal dependencies

---

CHANGES.rst
asdf/schema.py
asdf/tests/data/default-1.0.0.yaml
asdf/tests/data/one_of-1.0.0.yaml
asdf/tests/test_schema.py

This PR completely disables filling/remove defaults from subschemas within `oneOf` or `anyOf` combiners.  #809 demonstrates a serious bug in the defaults code that prevents use of `oneOf` in most realistic cases.  Given that there isn't a clear correct answer when choosing a default from among multiple `oneOf` subschemas, I'm inclined to ignore them when processing defaults.
I also propose that we do away with defaults for `anyOf`.  The way `anyOf` currently behaves is to always add a default from the first subschema.  If the object actually matches one of the subsequent subschemas, then we'll be adding a default from the wrong type!
With these changes, the remaining default rules are as follows, for a given missing property:
- If an object's own property definition has a default, use …

Stop traversing oneOf and anyOf combiners when filling/removing defaults

---

CHANGES.rst
asdf/block.py
asdf/fits_embed.py
asdf/tags/core/ndarray.py
asdf/tests/test_fits_embed.py

This PR fixes an issue with reading binary blocks stored in FITS files.
When astropy reads data that requires scaling, it performs said scaling and returns the result in native byte order.  Until now asdf has been assuming that all data from a FITS file is big-endian, since that's how the bytes are stored on disk, but due to the scaling operation that's not always the case.
The fix is to accept that the dtype reported by an array from a FITS file is correct.
CC @stscieisenhamer

Fix misinterpretation of byte order of blocks stored in FITS files

---

CHANGES.rst
asdf/versioning.py

This resolves a bug reported by @jdavies-st where ASDF 1.0.0 files were being written with incorrect tag versions.

Fix bug in version map caching

---

.travis.yml
CHANGES.rst
asdf/__init__.py
asdf/_config.py
asdf/asdf.py
asdf/entry_points.py
asdf/extension.py
asdf/fits_embed.py
asdf/resource.py
asdf/schema.py
asdf/tests/conftest.py
asdf/tests/test_api.py
asdf/tests/test_config.py
asdf/tests/test_entry_points.py
asdf/tests/test_fits_embed.py
asdf/tests/test_resource.py
asdf/tests/test_schema.py
setup.cfg

This PR introduces a new API for extending asdf with additional schemas.  The entry point accepts any `collections.abc.Mapping`, where the key is the schema URI `str` and the value is the content as `bytes`.
Included is a `Mapping` implementation that makes it easy to serve up schemas from a directory or package.  For asdf_transform_schemas, it'll look something like this:
```python
from pathlib import Path
from asdf.resource import DirectoryResourceMapping
def entry_point():
schemas_root = Path(__file__).parent/"schemas". 
return [
DirectoryResourceMapping(schemas_root, "http://asdf-format.org/schemas/transform")
]
```
But any `Mapping` will work, so users can also add a schema from the console using a `dict`:
```python
import asdf
schema = """
type: object
properties:
bar:
type: integer …
```

Add new resource Mapping API

---

CHANGES.rst
asdf/block.py
asdf/generic_io.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py

This PR allows binary blocks to be written to disk in non-contiguous order.  Previously we had allowed Fortran order but converted to C order in all other cases, and this causes problems when a view over a block is depending on the original order.
While I was investigating this one, I found another bug that produced unreadable ASDF files when an array in the tree was both offset and broadcasted.
Resolves #826

Allow arrays to be written to blocks in non-contiguous order

---

CHANGES.rst
asdf/schema.py
setup.cfg

This PR addresses a bug in `check_schema` that has been preventing us from thoroughly validating default values in schemas.  Happily, the only schemas which seem to be invalid are the old wcs schemas, which are deprecated anyway.  The specific issue is in frame-1.1.0:
```
obsgeoloc:
description: |
3-vector giving the position of the observer relative to the
center-of-mass of the Earth, oriented the same as
BCRS/ICRS. Defaults to `[0, 0, 0]`, meaning "true" GCRS.  Used
when `reference_frame` is `GCRS` or `precessed_geocentric`.
type: array
items:
$ref: ../unit/quantity-1.1.0
minItems: 3
maxItems: 3
default:
- { value: [0], unit: m }
- { value: [0], unit: m }
- { value: [0], unit: m }
```
The elements of the default array aren't valid because they aren't tagged, instead they're generic …

Fix validation of default values in schemas

---

CHANGES.rst

This just removes the 2.6.1 section of the changelog and moves its entries to the top of the 2.7.0 section.

Update CHANGES.rst for 2.7.0 release

---

CHANGES.rst
asdf/schema.py
asdf/tests/test_schema.py
pytest_asdf/plugin.py

A [recent bug fix](https://github.com/asdf-format/asdf/pull/785) made this check more strict, which is causing tests in jwst to fail.  This PR adds an option to disable validation of the schema `default` property for projects that want to use a descriptive `default` value instead of providing a literal default.

Make validation of schema default configurable

---

CHANGES.rst
asdf/asdf.py
asdf/tags/core/__init__.py
asdf/tags/core/tests/test_extension_metadata.py
asdf/tests/test_api.py

The next version of ASDF is going to add some additional properties to extension metadata, which the schema permits but would cause the library to raise an error due to the way the `ExtensionMetadata` class was initialized.  This PR changes the `ExtensionMetadata` class to a dict (like the other core objects) so that it can hold additional properties without complaint.
I'd like to get this into the 2.7 release so that files produced by 2.8 do not cause these errors.

Prevent errors when extra properties are present in extension metadata

---

CHANGES.rst
asdf/stream.py
asdf/tests/test_fits_embed.py
asdf/tests/test_stream.py
docs/asdf/arrays.rst
docs/asdf/features.rst
docs/sphinxext/example.py

This was merged into master as part of #817, but we don't want to include that entire commit in 2.7.

Replace usage of deprecated tostring with tobytes

---

CHANGES.rst
asdf/schema.py
asdf/tags/core/tests/test_ndarray.py

This PR is a minor adjustment to #819. I had intended to use schemas from the new API before resorting to the old API, but my original implementation passed the schema URI through the old resolver first, which may be converting it to a filesystem URL that the new code can't recognize. This change is simply to check the schemas from the new API first, and only pass the URI through the resolver if necessary.

Check resource manager before passing schema URI through resolver

---

setup.cfg

pytest 6 was released today and seems to be incompatible with pytest-doctestplus.
Example build failure: https://travis-ci.com/github/asdf-format/asdf/jobs/365887046
Related pytest-doctestplus issue here: https://github.com/astropy/pytest-doctestplus/issues/118

Restrict pytest to versions < 6

---

CHANGES.rst
asdf/__init__.py
asdf/asdf.py
asdf/config.py
asdf/resource.py
asdf/schema.py
asdf/tests/conftest.py
asdf/tests/test_config.py
docs/asdf/developer_api.rst
docs/asdf/user_api.rst

Since `AsdfConfig` is returned by `asdf.get_config`, it should be considered a part of the public API and included in the documentation.  This PR changes `asdf._config` --> `asdf.config`, updates the docs, and adds some missing test coverage.

Make config module public and add missing test coverage

---

asdf/extension/__init__.py
asdf/extension/_legacy.py
asdf/util.py

This PR changes the `asdf.extension` module from a file to a directory, and moves the current contents of extension.py to `asdf.extension._legacy`.  All the existing public objects are imported in the new init file  so this shouldn't cause problems.

Reorganize extension.py into a directory to prepare for new API

---

CHANGES.rst
asdf/config.py
asdf/entry_points.py
asdf/resource.py
asdf/tests/test_config.py
asdf/tests/test_entry_points.py
asdf/tests/test_resource.py

Some updates to the resource mappings:
- Wrap registered mappings in a proxy class that also carries around the package that supplied the mapping.  Without this, they'll be hard to debug, since the class name of the mapping itself doesn't generally provide any useful hints.
- Make sure mappings added at runtime take precedence over automatically registered mappings.
- Add config parameter that permits removing all of a package's mappings in one call.

Resource mapping updates

---

CHANGES.rst
asdf/_helpers.py
asdf/asdf.py
asdf/config.py
asdf/tests/test_asdf.py
asdf/tests/test_config.py
asdf/versioning.py

- Add option to configure the default ASDF Standard version
- Move version-related properties from mixin to AsdfFile
- Update docstring on AsdfFile.write_to and AsdfFile.update to reflect true behavior of version parameter
- Add some tests

Versioning cleanup

---

asdf/tests/test_util.py
asdf/util.py

Previously an inner class name wouldn't include the fact that it was nested in an outer class:
```python
class SomeClass:
class SomeInnerClass:
pass
```
The name of `SomeClass` has been correct, but `SomeInnerClass` would come out as `some_module.SomeInnerClass` instead of `some_module.SomeClass.SomeInnerClass`.  This PR changes it to the latter.

Use __qualname__ when building fully qualified class names

---

CHANGES.rst
asdf/asdf.py
asdf/commands/tags.py
asdf/commands/tests/test_tags.py
asdf/config.py
asdf/entry_points.py
asdf/extension/__init__.py
asdf/extension/_extension.py
asdf/extension/_legacy.py
asdf/fits_embed.py
asdf/schema.py
asdf/tags/core/tests/test_history.py
asdf/tests/test_api.py
asdf/tests/test_asdf.py
asdf/tests/test_config.py
asdf/tests/test_entry_points.py
asdf/tests/test_extension.py
asdf/tests/test_types.py

This PR refactors the existing extension code to make the new API easier to implement.  Changes include:
- Move extension loading from `_DefaultExtensions` to the new `asdf.entry_points` module
- Move list of registered extensions from `_DefaultExtensions` to `AsdfConfig`
- Remove most of the code from `_DefaultExtensions` so that it becomes a thin interface around `AsdfConfig`
- Add methods for adding and removing registered extensions at runtime
- Add wrapper that allows extensions to carry around their own metadata

Allow installed extensions to be configured with AsdfConfig

---

asdf/generic_io.py
asdf/schema.py
asdf/tests/test_generic_io.py
asdf/tests/test_schema.py
asdf/tests/test_util.py
asdf/treeutil.py
asdf/util.py

This PR allow asdf to properly resolve relative references against `asdf://` URIs.  The `urllib.parse` module maintains a list of URI schemes that should behave like `http` with regard to resolving relative paths, and needed `asdf` added to its list.
There's a second change in here that fixes a long-standing issue with resolving references in metaschemas.  It's common for such schemas to define an `id` property, but the asdf library didn't know not to treat that property object as a URI.  The fix is to check that `id` is a string before assuming it's a URI.

Support asdf:// URI scheme

---

CHANGES.rst
asdf/block.py
asdf/reference.py
asdf/schema.py
asdf/tests/test_schema.py

It turns out my test didn't catch all the issues that come up during actual validation.  I updated the test, made some fixes, and also made sure that the patched `urilib.parse` is used everywhere.

Fix oversights in support for asdf:// URI scheme

---

asdf/asdf.py
asdf/extension/__init__.py
asdf/extension/_legacy.py
asdf/tags/core/tests/test_history.py
asdf/tests/test_extension.py

This (partially) fixes a performance regression due to #847.  I noticed that the tests were running ~ 15% slower on the latest master, and it turns out my changes are causing the `TypeIndex` object for the default set of extensions to be rebuilt when previously it was reused from the `asdf.extension.default_extensions` object.
The change here doesn't actually improve the tests much, since an autouse fixture resets the config every time and forces cache misses.  But here's a test program that demonstrates the difference:
```python
from time import time
from asdf import AsdfFile
started_at = time()
for _ in range(10000):
AsdfFile().extension_list
print(time() - started_at)
```
Trials on 2.7.0:
```
0.6928091049194336
0.694317102432251
0.6906321048736572
```
Trials on master:
``` …
```

Fix performance regression due to rebuilding type index

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_asdf.py
asdf/type_index.py
asdf/yamlutil.py

This PR continues from #847 and fixes the issue where extensions not used during serialization were written to the file metadata.  The fix necessitated adding a hook to `yamlutil.dump_tree` to modify the tagged tree after it had been converted, since only then do we know what extensions were used.
My long-term goal for the new `SerializationContext` class is for us to pass that object around instead of the `AsdfFile` itself.  Currently when `AsdfFile.write_to` is called, it modifies the `AsdfFile` instance in order to write with the specified parameters.  Some of these modifications are permanent, which breaks the contract of `write_to` (it's documented as an "export" type of operation that doesn't change the `AsdfFile`), and some are merely awkward, like these:
```python
def …
```

Include only extensions used in metadata + introduce SerializationContext

---

.travis.yml
CHANGES.rst
docs/asdf/install.rst
setup.cfg
tox.ini

This PR makes Python 3.6 the minimum supported version.

Drop support for Python 3.5

---

asdf/asdf.py
asdf/fits_embed.py

This PR continues from #848 and changes `asdf.open` to wait to assign extensions to the `AsdfFile` instance until the version is known.  In the future, extensions will have ASDF Standard version requirements, and assigning them early will result in unnecessary warnings.
This change won't be needed until the new extension API comes, but it's a nicely self-contained bit of work so I thought I'd separate it to make review easier.

Wait to assign extensions until version is known

---

CHANGES.rst
asdf/asdf.py
asdf/config.py
asdf/extension/_extension.py
asdf/fits_embed.py
asdf/tags/core/__init__.py
asdf/tags/core/tests/test_history.py
asdf/tests/test_asdf.py
asdf/tests/test_config.py
asdf/tests/test_extension.py
asdf/tests/test_fits_embed.py
asdf/yamlutil.py

This PR is branched off of #849.  Here I'm adding support for extension URIs, where are defined as an attribute on the extension instance and are written to the file metadata.  Technically this is part of the new extension API, but the change fit nicely into a separate PR.
There are two new extension attributes:
- `extension_uri`: The URI of the "extension to the ASDF Standard" that the extension class implements.  Something like "asdf://somewhere.org/extensions/foo-1.0".
- `legacy_class_names`: The fully qualified names of extension classes that provided this functionality before the advent of URIs.  This allows us to switch to URIs and change the class name without incurring warnings from the library.
Additionally I changed `AsdfFile.__init__` and `asdf.open` to accept extension URIs in …

Implement support for extension URIs

---

CHANGES.rst
asdf/asdf.py
asdf/extension/_extension.py
asdf/tests/test_asdf.py
asdf/tests/test_extension.py
setup.cfg

This PR is branched off of #850.  It adds support for specifying an ASDF Standard version requirement as an attribute on the extension class.  We'll need this for the older transform extensions, each of which corresponds to a specific ASDF Standard version.  It'll also be handy when we implement the core extension (currently `asdf.extension.BuiltinExtension`) using the new API.

Support for ASDF Standard requirements on extensions

---

CHANGES.rst
asdf/config.py
asdf/schema.py
asdf/tests/conftest.py
asdf/tests/test_config.py
asdf/tests/test_schema.py
asdf/tests/test_util.py
asdf/util.py

This implements an idea from @CagtayFabry discussed in https://github.com/asdf-format/asdf-standard/issues/271.  See #838 for an alternative implementation.
The PR is branched off of #850.  The relevant changes are in the latest commit.
The idea is to allow pattern matching in the `tag` validator, so that schema authors can permit many versions of a tag.  For example, the following pattern:
```yaml
tag: asdf://somewhere.org/tags/foo-*
```
will match any of the following:
```
asdf://somewhere.org/tags/foo-1.0.0
asdf://somewhere.org/tags/foo-2.0
```
and this will match any transform tag:
```
asdf://asdf-format.org/extensions/transform/tags/*
```
which I expect will save us a lot of tedious updating of schemas when we add or update transforms.

Permit wildcard in tag validator URIs

---

CHANGES.rst
asdf/util.py

With the new API using tag patterns in the converters, this cache should be larger.  I checked the size of some relevant compiled regexes and `sys.getsizeof` reported < 1024 bytes for all, so at most this will require 1 MiB which seems reasonable.

Increase size of tag pattern cache

---

CHANGES.rst
asdf/asdf.py
asdf/tests/test_asdf.py
asdf/type_index.py

I think we should give these a leading underscore, since I can't see them being useful to extension developers and we may want to change the implementation after the old extension API is removed.

Rename used extensions attributes

---

CHANGES.rst
asdf/schema.py
asdf/tags/core/ndarray.py
asdf/tests/test_schema.py
asdf/versioning.py

This updates the asdf-standard submodule to include the latest draft of the ASDF Standard 1.6.0 version map, and implements the restriction on mapping key types that will be part of that version.  Starting with 1.6.0, mapping keys will be limited to string, integer, or boolean type.

Add ASDF Standard 1.6.0 and implement restriction of mapping key types

---

CHANGES.rst
asdf/asdf.py
asdf/config.py
asdf/entry_points.py
asdf/extension/__init__.py
asdf/extension/_converter.py
asdf/extension/_extension.py
asdf/extension/_legacy.py
asdf/extension/_manager.py
asdf/extension/_tag.py
asdf/fits_embed.py
asdf/schema.py
asdf/tests/test_asdf.py
asdf/tests/test_entry_points.py
asdf/tests/test_extension.py
asdf/tests/test_integration.py
asdf/tests/test_resource.py
asdf/yamlutil.py

Here at last are the new `Extension` and `Converter` APIs!  Some features aren't yet implemented (and may not be until the 2.9 release), but I think the interfaces have everything we need to support the asdf-astropy package.  Here's what a converter might look like for the identity transform:
```python
class IdentityConverter(TransformConverter):
tags = [
"asdf://asdf-format.org/extensions/transform/tags/identity-*",
"tag:stsci.edu:asdf/transform/identity-*",
]
types = ["astropy.modeling.mappings.Identity"]
def from_yaml_tree_transform(self, node, tag, ctx):
from astropy.modeling.models import Identity
return Identity(node.get("n_dims", 1))
def to_yaml_tree_transform(self, model, tag, ctx):
node = {}
if model.n_inputs != 1:
node["n_dims"] = model.n_inputs
return node
```
I'd like to …

Add Extension and Converter ABCs

---

CHANGES.rst
asdf/asdf.py
asdf/block.py
asdf/config.py
asdf/reference.py
asdf/tests/test_config.py
asdf/tests/test_schema.py
asdf/versioning.py
asdf/yamlutil.py

This PR includes the following changes:
- Stop removing schema defaults for all ASDF Standard versions
- Stop filling defaults for ASDF Standard versions > 1.5.0 (this will only affect the forthcoming 1.6.0 standard)
- Deprecate the `do_not_fill_defaults` argument wherever it may be found
- Add the `legacy_fill_schema_defaults` global config option to control filling defaults for older ASDF Standard versions

Stop removing defaults and fill defaults only for legacy versions

---

asdf/extension/__init__.py
asdf/extension/_manifest.py
asdf/tests/test_extension.py

This PR adds an implementation of the `Extension` interface that reads properties like `extension_uri`, `tags`, and `asdf_standard_requirement` from the manifest document.

Add extension that reads from manifest

---

CHANGES.rst
asdf/tags/core/ndarray.py
asdf/tests/test_api.py

This fixes a bug reported in #867 where copied arrays were unavailable after the `AsdfFile` was closed.  This feature was broken by https://github.com/asdf-format/asdf/pull/716, which forced all arrays to be regenerated if the underlying file was closed.  The solution is to regenerate memory-mapped arrays only.
Resolves #867

Fix bug preventing access to arrays after file is closed

---

.travis.yml
asdf/block.py
asdf/commands/diff.py
asdf/resolver.py
asdf/schema.py
asdf/tags/core/integer.py
asdf/tags/core/ndarray.py
asdf/versioning.py
asdf/yamlutil.py
tox.ini

This PR adds bandit to to the Travis jobs and fixes or marks `# nosec` failing lines in the non-test (and non-extern) code.

Add bandit to CI jobs and fix or # nosec failed lines

---

CHANGES.rst
asdf/asdf.py
asdf/config.py
asdf/entry_points.py
asdf/extension/_converter.py
asdf/extension/_extension.py
asdf/extension/_manager.py
asdf/fits_embed.py
asdf/tests/test_asdf.py
asdf/tests/test_config.py

Some fixes for issues that were uncovered while testing converters in asdf-astropy:
- Sort plugins by package name + plugins from the asdf package at the end so that extension packages can override built-in plugins.
- Change `AsdfFile.extensions` property to return "user extensions" only, that is to say, extensions that were passed in to `AsdfFile.__init__` or `asdf.open`.
- Update docstrings to note where `ExtensionProxy` is returned.
- Remove some features that allowed referring to extensions by URI.  I think I went a little overboard with implementing those before we had a real use case, they can always be revived later.
- Include the extension URI in the `ExtensionProxy` repr to aid in debugging.

Tweaks to new extension code

---

CHANGES.rst
asdf/tests/test_api.py
asdf/treeutil.py

This PR resolves a long-standing issue where trees containing `None` values are not faithfully written to an ASDF file.  An example, using 2.7.0:
```python
In [3]: import asdf
In [6]: asdf.AsdfFile({"foo": None, "bar": 42}).write_to("test.asdf")
In [7]: cat test.asdf
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: Space Telescope Science Institute, homepage: 'http://github.com/spacetelescope/asdf',
name: asdf, version: 2.8.0.dev49+ge6a0d37}
history:
extensions:
- !core/extension_metadata-1.0.0
extension_class: asdf.extension.BuiltinExtension
software: !core/software-1.0.0 {name: asdf, version: 2.8.0.dev49+ge6a0d37}
bar: 42
...
In [8]: af = asdf.open("test.asdf")
In [9]: "foo" in af
Out[9]: False
```
and …

Support serialization of null values

---

CHANGES.rst
asdf/commands/__init__.py
asdf/commands/edit.py
asdf/commands/tests/test_edit.py

I have added an 'edit' subcommand to the asdftool.  It separates the ASDF markings and YAML text into a separate file to be edited, using
```
asdftool -e -f <ASDF file> -o <YAML file name>
```
Once editing the YAML is complete, use 
```
asdftool -s -f <edited YAML file> -o <ASDF to save YAML to>
```
There may be a gotcha when saving the edited YAML back to ASDF file.  If the edited YAML contains for characters than the number of characters before the binary blocks in the ASDF file, an error message is returned.

Asdftool edit

---

.travis.yml
asdf/conftest.py
asdf/resource.py
asdf/tests/test_resource.py
conftest.py
setup.cfg
tox.ini

- Fix `importlib.abc.Traversable` bug
- Add Python 3.9 job to Travis CI matrix
- Update setup.cfg with `project_urls`
- Fix dev urls in `tox.ini`
- Update `_docdir` pytest autouse fixture to work with Pytest 6.0 and the latest `pytest-doctestplus`.

Make asdf compatible with Python 3.9

---

CHANGES.rst
asdf/tests/helpers.py

This change should fix the test failure reported in #887.  `importlib.resources.path` is clearly documented as not supporting directories:
```
package is either a name or a module object which conforms to the Package requirements. resource
is the name of the resource to open within package; it may not contain path separators and it may not
have sub-resources (i.e. it cannot be a directory).
```
In our Travis jobs `importlib.resources.path(some_module, "")` returns the path containing the module's `__init__.py`, but evidently that is not the case in all environments.
I ended up removing use of `importlib.resources` here since we're making another mistake by returning the context manager's path.  In some cases that path will point to a temporary file that is deleted on `__exit__`, so it's …

Do not request a directory from importlib.resources.path

---

.github/workflows/asdf_ci.yml
asdf/tests/helpers.py
asdf/tests/test_file_format.py
asdf/tests/test_generic_io.py
tox.ini

I added all Travis CI tests to github actions, with the exception of the big endian test.  There is no straight forward support for big endian architecture in github actions, so will be done in a separate workflow.  There are two known failures, the Numpy Dev and Pre-Release Dependencies tests.
Resolves #818

GitHub actions, no big endian test

---

CHANGES.rst
asdf/commands/tests/test_defragment.py
asdf/commands/tests/test_exploded.py
asdf/commands/tests/test_to_yaml.py
asdf/compression.py
asdf/fits_embed.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/__init__.py
asdf/tests/test_fits_embed.py
asdf/tests/test_reference.py
docs/asdf/features.rst

This fixes an issue with numpy 1.20 due to code in compression.py assigning an empty bytes object to an empty ndarray range.  I also changed instances of np.int and np.float to int and float, respectively, since the numpy aliases have been marked as deprecated in 1.20.

Fix errors and warnings with numpy 1.20

---

.github/workflows/asdf_ci.yml

I noticed that the tests aren't running on the 2.7.x branch, so I added that to the list.  I also added all tags and all PR bases.

Adjust CI workflow filters

---

.github/workflows/s390x.yml
asdf/tests/test_api.py

This adds a new actions workflow that runs the tests on s390x architecture.  It's scheduled to run when a new tag is created (presumably a release candidate) and Mondays at 6am UTC.

Add s390x workflow

---

asdf/constants.py
asdf/schema.py
asdf/tags/core/integer.py
asdf/tests/test_api.py
asdf/tests/test_schema.py

Removal of the 52 bit limit for numbers in an ndarray (originally imposed for anticipated use with javascript), which allows usage for larger numbers.  The `ndarray` is still limited by 64 bits by the `dtype`.  In addition to removing this validation check, the `pytest` tests used to test the original limit have been removed as well.
Resolves #891

Literal bit limit changed from 52 bits to 64 bits

---

CHANGES.rst
asdf/compression.py

I missed that we were setting `buffer[...]` here and not `buffer.data[...]`!  That's the real source of the problem.  This is the difference between them:
```python
In [10]: buffer = np.zeros((10,), np.uint8)
...: buffer.data[0:5] = b'12345'
...: buffer
Out[10]: array([49, 50, 51, 52, 53,  0,  0,  0,  0,  0], dtype=uint8)
In [11]: buffer = np.zeros((10,), np.uint8)
...: buffer[0:5] = b'12345'
...: buffer
Out[11]: array([57, 57, 57, 57, 57,  0,  0,  0,  0,  0], dtype=uint8)
```
(where 57 is 12345 % 2**8)

Fix buffer assignment in compression.py

---

.github/workflows/downstream.yml

This adds a workflow that tests packages that depend on asdf.  We can trigger it manually before a release and it's also scheduled to run weekly.

Add workflow that tests downstream packages

---

CHANGES.rst
asdf/asdf.py
asdf/commands/edit.py
asdf/commands/tests/test_edit.py

This updates the new "asdftool edit" subcommand to automatically generate a temporary file name and open an editor.  There are heavier changes than might be expected because I discovered/created some opportunities to share more code with asdf.py and block.py.

Automatically launch editor when user invokes asdftool edit

---

CHANGES.rst
asdf/tags/core/tests/test_ndarray.py
pytest_asdf/plugin.py
setup.cfg
tox.ini

This fixes tests that are currently busted in master due to numpy deprecations and a warning out of astropy.  More detail below.

Fix tests impacted by numpy 1.20 deprecations

---

CHANGES.rst
asdf/block.py
asdf/fits_embed.py
asdf/generic_io.py
asdf/tags/core/ndarray.py
asdf/tests/test_fits_embed.py

This PR fixes bugs in serializing views over FITS arrays and base arrays with negative strides.
The astropy.io.fits library always writes arrays in C-contiguous order, but this library has been serializing views as though the arrays were to be written in the same order that they are stored in memory.  This works fine for arrays that are already C-contiguous but corrupts views over F-contiguous or non-contiguous arrays.  The fix here will handle the most common case where the view and the array have the same memory layout.  It raises an error when they do not, which is better than writing unreadable files.  I ran the jwst regression tests on this branch and all tests passed except for 5 known and unrelated failures.
In the case of a base array with negative strides, we've been serializing …

Fix strides issues over FITS arrays and base arrays with negative strides

---

CHANGES.rst
asdf/block.py
asdf/tags/core/ndarray.py
docs/asdf/changes.rst

I only fooled myself into thinking that this issue was fixed -- when testing I had forgotten that a change in master inlines arrays with < 100 elements.  Reversing the strides is one piece of the puzzle but the offset still needs to be recomputed for that memory layout, and that's a difficult problem that I don't know how to solve yet.  This PR reverts the partial fix for base arrays with negative strides so that the fix for FITS arrays can be released.

Revert attempted fix for base arrays with negative strides

---

asdf/tests/test_fits_embed.py

@kmacdonald-stsci pointed out a flaw in the tests I added to cover views over FITS arrays -- the base array was full of zeros, so the assertions were not checking what I thought they were.  Correcting the tests revealed a new bug (present in 2.7.2, so not caused by the 2.7.3 changes) where views over FITS arrays with a different dtype are not deserialized correctly.  This is an uncommon case but we should fix it eventually, so I added an xfail'ed test and will file an issue as well.

Fix FITS array view tests

---

.github/workflows/s390x.yml
asdf/commands/tests/test_edit.py
docker/s390x/Dockerfile
docker/s390x/README.md

This fixes an asdftool edit test that has been failing on s390x architecture.  The difference there is that the initial byteorder string is "big" and not "little", so replacing it with "medium" causes an extra prompt to confirm that it's okay to rewrite the file.
I also checked in a Dockerfile that I used to troubleshoot the problem with some brief instructions on how to use it.
Resolves #928

Fix test failures on s390x and add Docker image for future troubleshooting

---

.github/workflows/downstream.yml

This catches up our downstream workflow with the recent change in the specutils default branch name.  I imagine astropy will change soon as well, but it looks like it hasn't quite yet so I'll leave it alone for now.

Update specutils ref to reflect new default branch name

---

.github/workflows/s390x.yml

This fixes the s390x build now that we're generating asdf/version.py on the fly

Make s390x install editable

---

.github/workflows/changelog.yml

This adds a workflow that checks for a CHANGES.rst entry for the current PR.  It also responds to the same label that we used before, `no-changelog-entry-needed`.
Resolves #820

Revive changelog check

---

CHANGES.rst
asdf/tags/core/ndarray.py

Here's my second attempt at a fix for #916.  I noticed that we have a precedent where we copy the view when it has strides unsupported by ASDF (in the existing case, 0 strides).  Since re-computing the view against the base array as serialized is hard, I propose that we do the same here and simply copy the view when its base is non-contiguous.  I also added scipy to our test dependencies so that we can test this using the example in the issue description.
Fixes #916

Fix for base arrays with negative strides

---

CHANGES.rst
asdf/_convenience.py
asdf/asdf.py
asdf/commands/tests/test_info.py
asdf/tests/test_search.py
docs/asdf/features.rst

The `.tree` is unnecessary given that we have an `AsdfFile.__getitem__` defined.
Resolves #875

Drop .tree from search result paths

---

conftest.py

We apparently have a solution for this that used to work but something changed in the meantime.  It doesn't seem to hurt anything to use a temporary working directory for all tests, so I changed the fixture to do that.
Resolves #942

Use temporary working directory for all tests

---

CHANGES.rst
asdf/generic_io.py

This removes some workarounds from bugs that no longer affect us.
- The macOS read/write issue was resolved in Python 3.6+: https://bugs.python.org/issue24658
- I haven't found documentation on the Windows issue, but I tested on Python 3.6.13, 3.7.10, and 3.8.5 on Windows and was able to write a 4 GB array using this branch.
Resolves #932

Drop workarounds for bugs in older versions of Python on macOS and Windows

---

CHANGES.rst
asdf/tags/core/ndarray.py
asdf/tests/test_fits_embed.py

This PR modifies the check on views over FITS array to prohibit any change in dtype (not just change in item size).  This is needed to prevent the issue described in #937 where such arrays are deserialized with the wrong dtype.  For other reasons (see https://github.com/asdf-format/asdf/pull/810) we need to accept the dtype reported by astropy.io.fits, so it seems our best option is just to further limit what can be done with views over FITS arrays.
Resolves #937

Prohibit views over FITS arrays that change dtype

---

CHANGES.rst
asdf/commands/diff.py
asdf/commands/tests/data/frames_ignore_asdf_library.diff
asdf/commands/tests/data/frames_ignore_reference_frame.diff
asdf/commands/tests/test_diff.py
setup.cfg

This adds a `--ignore-query` (or `-i`) flag to the asdftool diff command.  It accepts a JMESPath expression and ignores matching nodes when computing the diff.

Add --ignore-query flag to asdftool diff

---

README.rst

fix pytest codeblock format

---

.github/workflows/downstream.yml

This updates our downstream workflow to run astropy tests from the `main` branch instead of `master`.  The name changed this past week.  It was failing this morning:
https://github.com/asdf-format/asdf/runs/2321003190?check_suite_focus=true
Also, it seems this workflow is a bit fragile.  Generally, we should be running the _default_ branch of all these repos, assuming the default branch is the dev branch.  Is there a reason we need to even be naming this branch?
```
pip install git+https://github.com/org/repo
```
will install the project from the default branch without needing to specify it.  Maybe we should simplify this downstream workflow?

Astropy master to main in downstream workflow

---

CHANGES.rst
asdf/asdf.py
asdf/generic_io.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_asdf.py
asdf/tests/test_file_format.py
asdf/tests/test_generic_io.py

This PR drops support for lazy-loading arrays over http and adds support for https and 3xx redirects.  The lazy-loading is a nice idea, but not useful in its current state and something we should revisit later when we have the time.
Resolves #965

Support https and redirects

---

CHANGES.rst
asdf/commands/tests/test_diff.py
asdf/tags/core/tests/test_history.py
asdf/tests/test_file_format.py
asdf/tests/test_fits_embed.py

astropy 4.2.1 started emitting an additional warning when opening bad files.  This PR marks tests that open known bad files to ignore that warning.
Resolves #966

Prevent astropy warnings in tests

---

asdf/tests/test_generic_io.py

Use of HTTP Range was removed in #971 so I think it's fair to remove this test.
Resolves #917

Remove HTTP range test

---

CHANGES.rst
asdf/asdf.py
asdf/exceptions.py
asdf/generic_io.py
asdf/tests/test_generic_io.py

The `GenericFile.seek_until` method turned out to have a couple of problems -- besides the mismatch on return code, the docstring also advertises an `exception` argument that is supposed to cause the method to raise an error when the delimiter isn't found.  I fixed both and also created a new subclass of `ValueError` so that users can catch the exception in a more targeted way.
Resolves #876

Resolve differences between seek_until docstring and implementation

---

asdf/tests/test_yaml.py
asdf/yamlutil.py

The standard requires that the root of every ASDF tree bear an asdf-1.1.0 tag, so `asdf.yamlutil.dump_tree` is too permissive.
Resolves #967

Tighten up root node requirements in yamlutil.py

---

CHANGES.rst
asdf/schema.py

This fixes a bug causing relative references in metaschemas to be resolved incorrectly (for example, the reference `#/definitions/schemaArray` was being resolved to `http://json-schema.org/draft-04/schema#/definitions/schemaArray` instead of the the host document).  The problem turned out to be that we have been using some Draft 7 components when building up our schema validator.
Resolves #976

Use all the Draft 4 components in schema validator

---

CHANGES.rst
asdf/commands/extension.py
asdf/commands/tags.py
asdf/commands/tests/test_extension.py
asdf/commands/tests/test_tags.py

Long term we may want to drop these, the Python API has plenty of options for getting at this information.
Resolves #959

Update asdftool tags and asdftool extensions for new extension API

---

CHANGES.rst
asdf/search.py
asdf/tests/test_search.py
docs/asdf/features.rst

This adds `AsdfSearchResult.replace`, which assigns a new value to all nodes in the search result.  For example, to plagiarize a file:
```python
af.search('author').replace('Perry Greenfield')
```
Resolves #925

Add replace method to AsdfSearchResult

---

CHANGES.rst
asdf/block.py

An earth-shattering, one-character PR to use the last block index found in the file, in case a pathological data block also contains something that looks like a block index header.  This can especially happen if uninitialized arrays are written to disk, because the uninitialized regions could contain recycled memory that has a block index (which happened in #989).
I confirm this fixes the reading of this file, which exhibits the pathology: https://drive.google.com/file/d/1DJr2qkdC2Qm3tos1cigmbUK8ngFzha5K/view?usp=sharing

Search for block index starting from end of file

---

docs/asdf/user_api.rst

This fixes a warning that occurs in sphinx 4.0 due to multiple automodapi that include AsdfExtension.

Fix sphinx build warning

---

CHANGES.rst
asdf/block.py
asdf/tests/test_array_blocks.py

This addresses #999 (and therefore also https://github.com/spacetelescope/jwst/issues/6039).
The problem arises when adding a block to an existing file that has no block index.  Ordinarily BlockManager knows the location of each internal block right away due to the index, but when the index is missing it defers locating most of the blocks until they're requested by the user.  When a block is added under those conditions, the BlockManager needs to be careful to locate remaining blocks first, otherwise the new block steals a block number that's already been claimed.

Fix bug when adding a block to an existing file with no index

---

CHANGES.rst
README.rst
asdf/config.py
asdf/extension/_compressor.py
asdf/extension/_extension.py
asdf/extension/_manifest.py
asdf/tests/test_config.py
asdf/treeutil.py
asdf/util.py
docs/asdf/arrays.rst
docs/asdf/asdf_tool.rst
docs/asdf/changes.rst
docs/asdf/config.rst
docs/asdf/developer_versioning.rst
docs/asdf/extending/compressors.rst
docs/asdf/extending/converters.rst
docs/asdf/extending/extensions.rst
docs/asdf/extending/legacy.rst
docs/asdf/extending/manifests.rst
docs/asdf/extending/resources.rst
docs/asdf/extending/schemas.rst
docs/asdf/extending/uris.rst
docs/asdf/extending/use_cases.rst
docs/asdf/features.rst
docs/asdf/install.rst
docs/asdf/using_extensions.rst
docs/conf.py
docs/index.rst

This PR adds a whole mess of new documentation sections and updates existing sections to reflect changes introduced in version 2.8.0.  It might be easier to review in the HTML render, which can be found here: https://asdf.readthedocs.io/en/al-503-document-2.8-features/

Update documentation to reflect new 2.8 features

---

CHANGES.rst
asdf/compression.py
asdf/tests/test_compression.py

Use a round-trip to Numpy to create a 1D `memoryview` that has the right byte order, because `memoryview` can't cast to all types it can represent.
Closes #1009.

Fix array compression for non-native byte order

---

CHANGES.rst
asdf/commands/tests/test_edit.py

Use 'python3' instead of 'python' in tests

---

CHANGES.rst
asdf/schema.py
asdf/tests/test_schema.py

This fixes a bug where the schema loader looks for content on disk when it should be retrieving it from the ResourceManager instance.
Resolves #1028

Fix schema URI resolving when the URI prefix is also claimed by a legacy extension

---

asdf/tagged.py

The docstring doesn't seem 100% accurate since `TaggedString` doesn't have an `__init__` method and one cannot tag it directly upon creating (in contrast to `TaggedList`)

fix `TaggedString` docstring

---

CHANGES.rst
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py

@CagtayFabry what do you think about this alternative fix?  My concern with #1016 is that we won't catch all the cases where an NDArrayType is created.
Resolves #1015

Remove 'name' and 'version' attributes from NDArrayType instances

---

CHANGES.rst
compatibility_tests/test_file_compatibility.py

Even after #1026, there are still some appearances of executing "python" instead of "python3" self. This PR replaces them and so completes fixing #1018. 
This is tested with the Debian build of python-asdf.

Use python3 as executable instead of python in tests

---

CHANGES.rst
asdf/commands/tags.py
asdf/commands/tests/test_tags.py
asdf/tests/test_types.py

This fixes a bug in the `asdftool tags` command when an extension does not implement all the tags in its manifest.
I'm also removing two tests that involve gwcs that haven't really been testing anything since support for WCS serialization was removed from this library.  These tests fail with gwcs master due to the removal of the gwcs.tags module.

Fix tag listing when extension is not fully implemented

---

asdf/tests/httpserver.py

Building 2.8.3 for Python 3.10 on openSUSE fails two tests with a deprecation warning:
```
[  605s] =================================== FAILURES ===================================
[  605s] __________________________ test_no_warning_nan_array ___________________________
[  605s] 
[  605s] tmpdir = local('/tmp/pytest-of-abuild/pytest-0/test_no_warning_nan_array0')
[  605s] 
[  605s]     def test_no_warning_nan_array(tmpdir):
[  605s]         """
[  605s]         Tests for a regression that was introduced by
[  605s]         https://github.com/asdf-format/asdf/pull/557
[  605s]         """
[  605s]     
[  605s]         tree = dict(array=np.array([1, 2, np.nan]))
[  605s]     
[  605s] >       with assert_no_warnings():
[  605s] 
[  605s] …
```

replace deprecated isSet()

---

.github/workflows/ci.yml
setup.cfg
tox.ini

pytest-doctestplus has been compatible with pytest 6 since version 0.8
As Pytest 5 is not compatible with Python 3.10, this is a blocker.

Unpin Pytest < 6

---

.github/workflows/ci.yml
.github/workflows/s390x.yml
CHANGES.rst
setup.cfg
tox.ini

This PR drops support for Python 3.6 and Python 3.7 and removes tests and test environments that are only relevant to these versions.

Drop support for Python 3.6 and 3.7

---

CHANGES.rst
asdf/core/_converters/complex.py
asdf/core/_converters/entities.py
asdf/core/_converters/integer.py
asdf/core/_converters/tests/test_entities.py
asdf/core/_entities.py

@CagtayFabry's question [here](https://github.com/asdf-format/asdf/pull/1048#discussion_r783782316) revealed some flaws in the new Converters.  I've updated them to claim specific tag versions and also to retain additional properties in an "extra" dict where the schema allows them.

Remove wildcard from converter tags

---

.github/workflows/ci.yml
CHANGES.rst
setup.cfg
tox.ini

Our Python 3.6 CI job has started failing due to dependencies that require > Python 3.6, so it seems like a reasonable time to drop support for Python 3.6 in this package as well.

Drop support for Python 3.6

---

CHANGES.rst
asdf/extension/_extension.py
asdf/extension/_manifest.py
asdf/tests/test_extension.py
tox.ini

This pulls some compression plugin-related changes out of https://github.com/asdf-format/asdf/pull/1050 and into a separate PR.

Adjustments to compression tests and documentation

---

CHANGES.rst
setup.py

If one runs `pip install .` without running `git submodule update --init`, then pip spits out an incomprehensible error due to `asdf-standard` being empty. This PR adds a check that for `asdf-standard` being empty, with an error raised which describes what to do.

Add error message to setup.py.

---

CHANGES.rst
asdf/extension/_manifest.py
asdf/extension/_tag.py
asdf/schema.py
asdf/tests/test_extension.py
asdf/tests/test_integration.py

Currently, manifest tags will only allow one `schema_uri` per tag. For example, this forces every transform schema in `asdf-transform-schemas`, to perform an `allOf` between the new properties added by that transform and one of the `transform-*` schemas. What this means is that if we want to create a new `transform-*` schema, we have to create a new schema for every other transform. This will allow us to only need to create an updated manifest along side the new `transform-*` schema, which will be less prone to human error.
Note that when validating against a `tag` with multiple `schema_uri`, one assumes an `allOf` condition between all of the schemas referenced (meaning it must be a valid for every schema listed under the tag).

Allow manifest tags to list multiple `schema_uri` values.

---

asdf/fits_embed.py

`astropy.io.fits` complains when you do not include a Primary extension. Also, DQ array is usually 16-bit int (also `arange` does not make sense for DQ).

DOC: Improve AsdfInFits example

---

CHANGES.rst
asdf/testing/helpers.py

This backports `asdf.testing.helpers` from the asdf-3.0-epic branch.

Add simplified test helpers

---

CHANGES.rst
asdf/extension/_tag.py
asdf/tests/test_extension.py

@WilliamJamieson I was wrong about this property, it is in fact in use by roman_datamodels.  I'm adding it back here (with a deprecation warning) so that roman_datamodels can have a chance to switch to the new property.

Restore TagDefinition.schema_uri property but add deprecation warning

---

setup.py

In asdf-format/asdf-transform-schemas#32, a recursive yaml file finding was added. This was done so that arbitrarily deep directory trees for schemas and other resource file could be used without modification of `setup.py` for non-editable installations. This PR brings that functionality into asdf itself.

Add recursive yaml find to `setup.py`

---

CHANGES.rst
asdf/tests/helpers.py
asdf/tests/test_types.py
pytest_asdf/plugin.py

Fix for pytest 7.0 depreciation warning

---

CHANGES.rst
asdf/asdf.py
asdf/fits_embed.py
asdf/reference.py
asdf/tests/test_history.py
asdf/tests/test_schema.py
asdf/tests/test_types.py
asdf/tests/test_yaml.py
asdf/treeutil.py
asdf/type_index.py
asdf/yamlutil.py
docs/asdf/extending/legacy.rst
docs/asdf/using_extensions.rst
docs/sphinxext/example.py
pytest_asdf/plugin.py
setup.cfg

Removes the following flags/arguments:
- `ignore_version_mismatch`
- `ignore_unrecognized_tag`
- `ignore_inplicit_conversion`
for `AsdfFile`.
This is part of the process to make asdf-3.0 more strict.

Remove various ignore flags/arguments from ASDF

---

CHANGES.rst
pytest_asdf/plugin.py

This fixes a bug that causes the schema tests to fail when the schemas are not located in a directory named "schemas".
I'm also removing checks related to astropy 3.0 that are no longer relevant and changing the plugin to use the latest ASDF Standard version always, so that we don't need to worry about inferring the tag URI from the schema and parsing the version.

Remove schema version parsing from the pytest plugin

---

asdf/util.py
compatibility_tests/test_file_compatibility.py

`distutils` is deprecated. cc @eslavich

MNT: Replace distutils with packaging

---

CHANGES.rst
asdf/resolver.py
asdf/resource.py
asdf/schema.py
asdf/tests/helpers.py
asdf/tests/test_api.py
asdf/tests/test_config.py
asdf/tests/test_resource.py
asdf/versioning.py
setup.cfg
setup.py

PR asdf-format/asdf-standard#292 packages asdf-standard so that it can be released on PyPi. Once `asdf-standard` is available as a pypi package, the `git submodule` used to include asdf-standard into asdf will no longer be required. This PR aims to accomplish this.

Switch to using `asdf-standard` as a PyPi package.

---

.pre-commit-config.yaml
asdf/_convenience.py
asdf/asdf.py
asdf/schema.py
asdf/tests/test_api.py
asdf/tests/test_fits_embed.py
asdf/tests/test_schema.py
asdf/tests/test_versioning.py
asdf/type_index.py
bandit.yaml
pyproject.toml
setup.cfg
setup.py
tox.ini

@WilliamJamieson what do you think of this?  I'm in the habit of running black, flake8, etc manually and would like to continue to do so on occasion.  With these changes I get the same results for this:
```
pre-commit run --all-files
```
vs all these separately:
```
black .
isort .
flake8
bandit -c bandit.yaml -r .
```
As much as possible I had them share configs, but in some cases the excludes get overridden by whatever pre-commit passes to the tool.
I also noticed that isort with the black profile was using a line length of 88.  I changed it to 120 to match black, but that resulted in some reformatting of imports.

Share config between pre-commit and manual use of tools

---

.github/workflows/downstream.yml

Enables downstream ci to be run on a PR if one adds the `Downstream CI` label.
Closes #1097

Added condition for label to run downstream tests as part of PR

---

.gitignore
asdf/__init__.py
asdf/_helpers.py
asdf/asdf.py
asdf/tests/test_entry_points.py
pyproject.toml
setup.py

Update usage of `setuptools_scm` to use the `pyproject.toml` file rather than the now depreciated `setup.py` method instead.

Update setuptools_scm configuration

---

CHANGES.rst
asdf/asdf.py
asdf/block.py
asdf/commands/tags.py
asdf/commands/tests/test_tags.py
asdf/config.py
asdf/extension/__init__.py
asdf/extension/_legacy.py
asdf/extension/_manager.py
asdf/schema.py
asdf/tests/helpers.py
asdf/tests/test_api.py
asdf/tests/test_asdf.py
asdf/tests/test_config.py
asdf/tests/test_extension.py
asdf/tests/test_schema.py
asdf/yamlutil.py

Now that user extensions are gone, we can move ExtensionManager to AsdfConfig instead of keeping a reference on each AsdfFile.  This simplifies the code vs passing around those instances, and saves users from having to instantiate an AsdfFile to get ahold of ExtensionManager.
I'm also dropping the AsdfFile.version setter in this PR, which mainly existed to reset the AsdfFile's extension variables.  I don't think it's safe to change the version of an open AsdfFile anyway (instead users should call write_to or maybe update).

Remove AsdfFile.extension_manager, AsdfFile.extension_list, and AsdfFile.version setter

---

setup.cfg

Until https://github.com/pytest-dev/pytest/issues/9765 is resolved, our Windows CI job will fail with pytest 7.1.

Pin pytest to < 7.1 for Windows

---

CHANGES.rst
asdf/schema.py
asdf/tests/test_schema.py
setup.cfg
tox.ini

This updates our minimum jsonschema version to 4.x and makes the changes necessary to use their new API.
Resolves https://github.com/asdf-format/asdf/issues/1104

Update jsonschema to 4.x

---

CHANGES.rst
pytest_asdf/plugin.py

Adds ability to set asdf-standard for an example item in a schema example test, this is part of the fix for astropy/asdf-astropy#82.
The bug is actually that the pytest plugin always assumes the example is written under the default asdf-standard. This is incorrect in the reported bug because `time-1.0.0` only appears in asdf-standard 1.0.0, so the asdf-astropy extension never gets loaded, causing a fall back to the astropy extension.

Support for examples speciflying asdf-standard version

---

CHANGES.rst
docs/asdf/extending/extensions.rst
docs/asdf/extending/legacy.rst
docs/asdf/extending/resources.rst
docs/conf.py
pyproject.toml

Changes layout for `pyproject.toml` vs `setup.cfg` examples from listing consecutively to placing them on user selectable tabs.

Change to tab layout for pyproject.toml vs setup.cfg

---

.github/workflows/s390x.yml

fixes issue with `s390x` test failure: https://github.com/asdf-format/asdf/actions/runs/2526970260

unpin dependency versions in `s390x` build

---

pyproject.toml
tox.ini

This ignores the warning discussed in #1168, so that the CI can proceed as normal. The cause of the warning should be found and fixed later.

Temporally Ignore pytest warning

---

CHANGES.rst

Update changelog for hotfix of `jsonschema` issue. See #1172.

Update changelog for release 2.12.1

---

CHANGES.rst
asdf/_display.py
asdf/_node_data.py
asdf/_node_info.py
asdf/asdf.py
asdf/search.py
asdf/tests/test_info.py

Adds the ability to search and pull information about fields in an asdf file from the underlying schema files. For example, this enables one to store keywords pertaining to a given asdf object's data entries within the schema(s) defining that object. This however requires that the underlying schemas to all be tagged.

Add ability to pull information from tagged schemas

---

CHANGES.rst
asdf/generic_io.py

The `GenericFile` class (and its subclasses) in asdf is intended to be a wrapper/handler for `io.IOBase` derived python objects, which are what python opens files into. These objects are either "seekable" or not, where in the base python object the `.seekable()` method returns `True` if it is seekable and `False` otherwise. Currently, `GenericFile` and its subclasses default to having `.seekable()` always be `False` even when wrapping python `io` objects which are seekable. This PR changes this behavior so that `GenericFile.seekable()` defaults to the value of `.seekable()` value provided by the underlying python object.

Refactor seekable in `GenericFile`

---

.pre-commit-config.yaml

In https://github.com/asdf-format/asdf-transform-schemas/pull/69#discussion_r967744284, it was pointed out that autoflake8 was recently archived in favor of autoflake. This PR makes the update here.

Update from autoflake8 to autoflake

---

CHANGES.rst
asdf/_display.py
asdf/_node_info.py
asdf/asdf.py
asdf/search.py
asdf/tests/test_info.py
docs/asdf/features.rst

Adds support for using a `AsdfSearchResult` as the `path` argument to a `schema_info` call on `AsdfFile` and a `schema_info` method on an `AsdfSearchResult`.
Fixes #558

Add support of schema_info for AsdfSearchResult as "path"

---

CHANGES.rst
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_array_blocks.py

per eslavich the contiguous array check should check for both f and c order array so modified flags.contiguous to flags.forc
modified ndarray test_fortran_order test to verify fortran ordered on 'roundtrip' write then read

fix saving fortran ndarray issue #1205

---

CHANGES.rst
asdf/schema.py
asdf/tests/test_schema.py
requirements-dev.txt

Add custom default validator to 'applicable_validators' argument to jsonschema.validators.create
Tested locally with jsonschema 4.16
This is work towards fixing #1172
One test is still failing locally (a doctest in docs/asdf/config.rst) but I wanted to trigger the CI and discuss the changes so far.
closes #1177

Unpin jsonschema, fix default validation

---

.pre-commit-config.yaml
docs/conf.py

Enable [`yesqa` ](https://github.com/asottile/yesqa) as part of pre-commit.
`yesqa` checks that `# noqa` codes apply and orders the `# noqa` codes.

Update pre-commit with yesqa

---

.github/workflows/ci.yml
asdf/commands/tests/test_diff.py
asdf/tests/test_asdf.py
asdf/tests/test_fits_embed.py
asdf/tests/test_generic_io.py
pyproject.toml
tox.ini

Turns all warnings into errors and cleans up pytest config

Turn warnings into errors

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_asdf.py
asdf/tests/test_generic_io.py
pyproject.toml

Instead of using isinstance, look for attributes 'raw' and 'getvalue' to determine what generic_io subclass to use. This adds support for fsspec objects.

Use ducktyping in generic_io get_file

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_asdf.py
asdf/tests/test_generic_io.py
pyproject.toml

Opening an http filesystem file using fsspec returns an object that is incompatible with generic_io. The fsspec object, when treated like a generic_io.RealFile, fails on both the _size and name/uri calculations.
[generic_io.GenericFile._size](https://github.com/asdf-format/asdf/blob/989cd955420ae717dff763c152be3cc21343d244/asdf/generic_io.py#L221) does not appear to be used so this PR removes it from all GenericFile classes.
[fd.name](https://github.com/asdf-format/asdf/blob/989cd955420ae717dff763c152be3cc21343d244/asdf/generic_io.py#L727) is used to calculate the uri (when not otherwise supplied). fsspec http files do not have a name so a different method of defining uri (such as providing one at the time of opening) will need to be used when a uri is necessary. This PR adds a `hasattr` …

Add fsspec http support

---

CHANGES.rst
asdf/fits_embed.py
asdf/tests/test_fits_embed.py
asdf/util.py

Fixes #1232 
When an asdf tree containing arrays is read from a fits file, the arrays are created as NDArrayType objects (instead of ndarray). If this tree was resaved to a fits file the NDArrayType was mishandled during matching arrays to hdu items which resulted in duplicate storage of array data in hdu items and internal blocks.
This PR adds a few tests for this issue and fixes the handling of NDArrayType to allow for accurate matching between hdu items and arrays to avoid data duplication.

Fix handling of NDArrayType during block to fits hdu matching

---

CHANGES.rst
asdf/generic_io.py
asdf/tags/core/tests/test_ndarray.py

even when reading an already opened file
fixes issue #1239
update changelog
add regression test docstring

always close memmaps with the asdf file

---

asdf/tests/test_versioning.py

Allow for more fine-grained control over explicit tag/extension version match failures.
test_version_map_support checks for explicit tag/extension matches. All tags currently not supported in legacy extensions fail these matches which required xfailing all checks with standard tags: https://github.com/asdf-format/asdf/blob/05d5001b27766b01688f8bd4b6e01d92445e1e3c/asdf/tests/test_versioning.py#L269-L271
As astropy.io.misc.asdf supports some of the core tags (time, unit, etc) but is a deprecated extension any updates to the schema for these tags will result in core tag test failures in test_version_map_support. This PR will allow xfailing just those tags supported outside of asdf and allow for continued testing of other core tags.

use pytest to parametrize test_version_map_support

---

CHANGES.rst
asdf/schema.py
asdf/tagged.py
asdf/tests/test_tagged.py

In spacetelescope/rad#155, a bug with using `enum` was reported. It of course had an unhelpful error message. The details of the bug's cause and possible resolution are detailed in issue #1256. This PR fixes #1256 by implemented one of possible paths (path 3) for resolution and adds regression tests for this behavior.

Bugfix for `enum` bug

---

.pre-commit-config.yaml
asdf/fits_embed.py
pyproject.toml

`ruff` updated its pre-commit API at some point, meaning the `pre-commit.ci` bot was not updating the plugin automatically. In the intervening time `ruff --fix` was improved to remove unnecessary `noqa` flags and fix unused imports (not marked with a `noqa`). Hence
- The removal of the slow `yesqa` job.
- The fix `fits_embed.py`.

Update ruff config

---

.pre-commit-config.yaml
asdf/_display.py
asdf/asdf.py
asdf/block.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_external_reference.py
asdf/tests/test_extension.py
asdf/treeutil.py
asdf/types.py
docs/asdf/arrays.rst
docs/asdf/developer_overview.rst
docs/asdf/features.rst
pyproject.toml

Inspired by astropy/astropy#13982 and astropy/astropy#13985, this PR adds [codespell](https://github.com/codespell-project/codespell) as another build style tool to ASDF. codespell should autofix (via pre-commit) any common spelling issues in ASDF and its docs (if a word is being incorrectly fixed, simply add it to the `ignore-words-list` in the `pyproject.toml` file.

Start using codespell

---

asdf/tests/helpers.py
asdf/tests/test_versioning.py
asdf/versioning.py

Modifies _assert_extension_type_correctness to skip checking type versions that are not part of a non-development supported version of the asdf-standard.
Two other tests are added `test_default_in_supported_versions` and `test_development_is_not_default` to catch possible errors where the default is set to a non-supported (or development) version.
As this PR will skip testing completeness (that a type has a schema of the same version) of type versions that are only in development version, it's possible that updating the development version of the asdf-standard will cause test failures if the schema and type versions do not match. Put another way, a PR that advances the asdf-standard development version might reveal and then have to fix these type/schema version issues.
This should allow …

skip testing type versions not in any deployed standard

---

CHANGES.rst
asdf/tags/core/integer.py
asdf/tags/core/ndarray.py
asdf/tests/test_types.py
asdf/tests/test_versioning.py
asdf/types.py

fixes an issue with integer where IntegerType instead of cls was used during class instantiation which resulted in objects being created with the incorrect version. Prior code (that only had one integer version, 1.0) did not suffer from issues because of this bug.
fixes #1245 by removing the use of super in NDArrayType and adding an exception to check for incompatible use of super in classes of type ExtensionTypeMeta.
This should be merged with asdf-standard PR https://github.com/asdf-format/asdf-standard/pull/350

support integer-1.1 and ndarray-1.1

---

CHANGES.rst

This release is to release the fix for BAMWelDX/weldx#825 so that it can be used by weldx.

Update changes for 2.14.3 release

---

pytest_asdf/plugin.py

Currently, the values must be in a newline-separated string, so like
```toml
asdf_schema_skip_tests = 'src/rad/resources/schemas/rad_schema-1.0.0.yaml'
```
or
```toml
asdf_schema_skip_tests = """
src/rad/resources/schemas/rad_schema-1.0.0.yaml
src/rad/resources/schemas/second_rad_schema-1.0.0.yaml
"""
```
When configuration is in a list format:
```toml
asdf_schema_skip_tests = [
'src/rad/resources/schemas/rad_schema-1.0.0.yaml',
'src/rad/resources/schemas/second_rad_schema-1.0.0.yaml',
]
```
the following error occurs:
https://github.com/spacetelescope/rad/actions/runs/3705663865/jobs/6279862181
```
________________________ ERROR collecting test session _________________________
.tox/py310/lib/python3.10/site-packages/pluggy/_hooks.py:265: in __call__
return self._hookexec(self.name, …
```

allow `asdf_schema_skip_tests` and `asdf_schema_xfail_tests` to be list objects under TOML

---

.github/workflows/downstream.yml

Attempt to fix CRDS failures for jwst downstream test

use HOME instead of ~ in crds path

---

asdf/asdf.py

Instead of searching the tree for NDArrayType instances to count the number of internal blocks to estimate the tree size, count the internal blocks directly.
This should be more efficient (by removing 1 tree traversal during update) and should make adding block-enabled extensions easier (by removing a case where NDArrayType is specially handled and assumed to be the only block-using object).

count blocks._internal_blocks during update

---

CHANGES.rst
asdf/block.py
asdf/tests/test_array_blocks.py

This wraps the Block class's `_data` reference in a weakref when reading in lazy_load=True and copy_arrays=False mode.  There isn't any benefit when reading ndarray but this will allow us to process large chunked arrays without memory mapping.

Discard cache of lazy-loaded block data when it is no longer referenced by the tree

---

asdf/asdf.py
asdf/block.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py

Block.readonly appears to only be used to unset the write flag during ndarray creation:
https://github.com/asdf-format/asdf/blob/master/asdf/tags/core/ndarray.py#L267-L268
This flag is already set for readonly memmaps (perhaps as a result of #1230) making the Block.readonly flag redundant.
This PR removes the Block.readonly flag and the associated code that sets it and adds to test_readonly to explicitly force memmapping (rather than relying on the defaul).

remove redundant Block.readonly

---

tox.ini

Fixes #1244, by adding the appropriate flags to the `tox` environment for `astropy` downstream testing

Use `--open-files`, `--run-slow`, and `--remote-data` flags for astropy downstream

---

asdf/tests/test_yaml.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts.
It enables `ruff` to explicitly check:
- `Pyflakes` (a `ruff` default)
- `pycodestyle` (also a `ruff default)
- `isort` (we were running `isort` as a standalone tool)
- `pyupgrade` (we were running parts of `pyupgrade` standalone, this runs all those checks and found some extra things to change)

Add `pyupgrade` check to `ruff`

---

asdf/extension/_compressor.py
asdf/extension/_converter.py
asdf/extension/_extension.py
asdf/extension/_legacy.py
asdf/reference.py
asdf/resource.py
asdf/schema.py
asdf/tags/core/external_reference.py
asdf/tags/core/ndarray.py
asdf/tests/test_extension.py
asdf/tests/test_types.py
asdf/types.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1299.
It enables `ruff` to explicitly check `pep8-naming` style checks.

Add `pep8-naming` check to `ruff`

---

asdf/commands/edit.py
asdf/entry_points.py
asdf/generic_io.py
asdf/reference.py
asdf/search.py
asdf/tests/helpers.py
asdf/tests/test_reference_files.py
asdf/tests/test_versioning.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1301.
It enables `ruff` to explicitly check `flake8-blind-except` style checks.

Add `flake8-blind-except` check to `ruff`

---

asdf/_display.py
asdf/_node_info.py
asdf/asdf.py
asdf/block.py
asdf/commands/diff.py
asdf/commands/extract.py
asdf/commands/main.py
asdf/commands/remove_hdu.py
asdf/compression.py
asdf/entry_points.py
asdf/fits_embed.py
asdf/reference.py
asdf/schema.py
asdf/search.py
asdf/tagged.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_extension_metadata.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/helpers.py
asdf/tests/test_compression.py
asdf/tests/test_generic_io.py
asdf/tests/test_schema.py
asdf/tests/test_versioning.py
asdf/type_index.py
asdf/types.py
asdf/util.py
pyproject.toml
pytest_asdf/plugin.py

This PR is part of breaking #1293 into multiple parts and is built off #1302.
It enables `ruff` to explicitly check `flake8-bugbear` style checks.

Add `flake8-bugbear` check to `ruff`

---

asdf/asdf.py
asdf/commands/diff.py
asdf/commands/tests/test_extract.py
asdf/commands/tests/test_remove_hdu.py
asdf/tags/core/integer.py
asdf/tags/core/tests/test_history.py
asdf/tags/core/tests/test_integer.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_api.py
asdf/tests/test_compression.py
asdf/tests/test_helpers.py
asdf/tests/test_info.py
asdf/tests/test_schema.py
asdf/tests/test_search.py
asdf/tests/test_treeutil.py
asdf/tests/test_types.py
asdf/tests/test_util.py
asdf/tests/test_yaml.py
asdf/types.py
compatibility_tests/test_file_compatibility.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1304.
It enables `ruff` to explicitly check `flake8-comprehensions` style checks.

Add `flake8-comprehensions` check to `ruff`

---

asdf/tests/test_util.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1307.
It enables `ruff` to explicitly check `flake8-import-conventions` style checks.

Add `flake8-import-conventions` check to `ruff`

---

asdf/_convenience.py
asdf/asdf.py
asdf/commands/edit.py
asdf/commands/extension.py
asdf/tags/core/tests/test_ndarray.py
pyproject.toml
pytest_asdf/plugin.py

This PR is part of breaking #1293 into multiple parts and is built off #1308.
It enables `ruff` to explicitly check `flake8-print` style checks.

Add `flake8-print` check to `ruff`

---

asdf/tags/core/ndarray.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1313.
It enables `ruff` to explicitly check `eradicate` style checks.

Add `eradicate` check for `ruff`

---

asdf/_display.py
asdf/_node_info.py
asdf/search.py
asdf/tests/test_config.py
asdf/tests/test_versioning.py
pyproject.toml
pytest_asdf/plugin.py

This PR is part of breaking #1293 into multiple parts and is built off #1314.
It enables `ruff` to explicitly checks:
- `pandas-vet` (no changes)
- `pygrep-hooks` (no changes and feature incomplete with the pre-commit hook)
- `pylint`

Add `pylint` check for `ruff`

---

asdf/extension/_compressor.py
asdf/extension/_converter.py
asdf/extension/_extension.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1315.
It enables `ruff` to explicitly checks `flake8-pie` style.

Add `flake8-pie` check for `ruff`

---

asdf/generic_io.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_fits_embed.py
asdf/tests/test_yaml.py
pyproject.toml

This PR is part of breaking #1293 into multiple parts and is built off #1316.
It enables `ruff` to run its unique set of checks.

Enable `ruff` specific checks

---

pyproject.toml

This PR enables all `ruff` checks by default. It then turns off checks we cannot (or will now support) at the current time. This is so we can accumulate new `ruff` checks as `ruff` adds them (its under fast development to add new checks all the time).
This will occur when the `pre-commit.ci` bot updates the `.pre-commit-config.yaml` file in a PR each week. We can decide how to fix these "new" checks when they start creating error messages in these new PRs.
This PR is the final part of breaking #1293 into multiple parts and is built off #1317.
Closes #1293

Enable `ALL` `ruff` checks by default

---

.pre-commit-config.yaml
asdf/tags/core/tests/test_complex.py
asdf/tests/helpers.py
asdf/tests/test_asdf.py
asdf/tests/test_yaml.py
asdf/yamlutil.py
pyproject.toml

[`flynt` ](https://github.com/ikamensh/flynt) is a comprehensive too to update string creation from `%`-style and `.format`-style strings into f-strings. It is more comprehensive than the tools built into `ruff` and `pyupgrade` as a consequence it has found a few straggling older style format strings left in ASDF.
This PR adds a standard configuration for `flynt` and runs the tool on ASDF

Apply the `flynt` tool

---

CHANGES.rst
asdf/exceptions.py
docs/asdf/developer_overview.rst

This warning should be used for any experimental api changes that should be considered provisional and might experience breaking changes (even in minor releases).

add AsdfProvisionalAPIWarning

---

CHANGES.rst
pyproject.toml
requirements-dev.txt

Numpy 1.25 is currently being developed and is dropping support for python 3.8.
Fixes #1326

require numpy < 1.25 for python 3.8

---

.pre-commit-config.yaml
asdf/_display.py
asdf/asdf.py
asdf/block.py
asdf/commands/diff.py
asdf/commands/extract.py
asdf/commands/tests/test_diff.py
asdf/fits_embed.py
asdf/generic_io.py
asdf/search.py
asdf/stream.py
asdf/tags/core/complex.py
asdf/tags/core/ndarray.py
asdf/tests/test_types.py
asdf/tests/test_versioning.py
asdf/util.py
compatibility_tests/assert_file_correct.py
compatibility_tests/common.py
compatibility_tests/generate_file.py
compatibility_tests/test_file_compatibility.py
conftest.py
pyproject.toml

We are currently using `ruff v0.0.223` and `ruff v0.0.230` was recently released. It updates and adds new checks. This PR updates ASDF to conform with these ahead of the pre-commit.ci bot attempting to update `ruff`.

Update ruff to v0.0.231

---

.pre-commit-config.yaml

isort is failing to build in the pre-commit ci
This looks to be related to https://github.com/PyCQA/isort/issues/2079
Bumping to 5.11.5 to see if it builds.

bump isort to 5.11.5

---

.pre-commit-config.yaml
asdf/block.py
asdf/fits_embed.py
asdf/generic_io.py
asdf/tests/test_versioning.py
asdf/types.py
pyproject.toml

Ruff has made a few tweaks (some of which I requested in charliermarsh/ruff#2202 and charliermarsh/ruff#2158) to rules we are already enforcing (in particular `SIM300` has been update to detect even more versions of yoda conditions which need to be ignored because we are specifically testing that we can handle those conditions).
This PR cleans up all unnecessary noqa and adds some new `SIM300` noqa. It also ignores:
- `TRY002`
- `TRY301`
- `TRY400`
Which we will address at a later date, per https://github.com/asdf-format/asdf/pull/1329#issuecomment-1405301731.

More ruff clean-ups

---

asdf/block.py

This PR fixes reserve_blocks to treat objects in the tree (nodes) in a way consistent with
yamlutil.custom_tree_to_tagged_tree. Conversion of nodes in a custom tree will preferentially use Converters if a type/tag is supported by both old style types and new style converters. Reserve blocks always assumed old style types. This resulted in serialization calling old style reserve_blocks and then new style converters for nodes supported by both types and converters.

don't call reserve_blocks on types that have converters

---

CHANGES.rst
asdf/asdf.py
asdf/block.py
asdf/commands/tests/test_defragment.py
asdf/commands/tests/test_exploded.py
asdf/commands/tests/test_to_yaml.py
asdf/fits_embed.py
asdf/stream.py
asdf/tags/core/ndarray.py
asdf/tags/core/tests/test_integer.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/helpers.py
asdf/tests/test_api.py
asdf/tests/test_array_blocks.py
asdf/tests/test_asdf.py
asdf/tests/test_compression.py
asdf/tests/test_file_format.py
asdf/tests/test_fits_embed.py
asdf/tests/test_generic_io.py
asdf/tests/test_stream.py
pytest_asdf/plugin.py
tox.ini

Public use of the block manager will be removed in ASDF 3.0 to allow for major changes to it's API. It is currently used by the legacy extensions (also removed in ASDF 3.0). The new converters do not currently have block storage access.
To provide a sense for possible breaking changes to the block manager and block storage access, the current experimental branch that adds block storage access to converters passes all block manager calls through the serialization context:
https://github.com/asdf-format/asdf/commit/4f6215608431f9f9e563fda9dc79d22c87a930bf
Adding block storage access to the converter is scheduled for ASDF 3.0 and the API and implementation details are not yet finalized.
Fixes issue #1335

add AsdfDeprecationWarning to AsdfFile.blocks

---

.pre-commit-config.yaml
pyproject.toml

All functionality from `pyupgrade` can now be fully replaced by `ruff`, see the completion of https://github.com/charliermarsh/ruff/issues/827.
This PR removes `pyupgrade` and configures `ruff` to take fully advantage of these changes.

Remove pyupgrade use from pre-commit

---

.github/workflows/downstream.yml

With https://github.com/spacetelescope/stdatamodels/pull/117 merged we no longer need to run a manual `crds sync` prior to running the stdatamodels tests.
This PR removes the no longer needed cache crds job from the CI.

remove crds cache ci job

---

.github/workflows/ci.yml
CHANGES.rst
pyproject.toml
tox.ini

Add testing against the oldest pinned versions of our dependencies.
Note that per https://github.com/asdf-format/asdf/pull/1331#discussion_r1096980876 I moved the script for generating the minimum dependencies out of ASDF and into its own package, see: https://github.com/WilliamJamieson/minimum_dependencies.
Closes #1331, as this supersedes it.

Add oldest dependencies testing

---

asdf/tests/test_generic_io.py

When python 2 support was dropped several tests that used io.open were switched to open. This left behind duplicate tests that this PR removes.

clean up duplicate tests and combine similar

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_generic_io.py

The use of atomic file produces filenames that can contain random characters. Fix the filename the error message prior to raising.
Without this PR
```python
import asdf
asdf.generic_io.get_file('missing/foo', 'w')
```
produces
```
FileNotFoundError: [Errno 2] No such file or directory: '/.../asdf/missing/.___atomic_writekdbtzq1a'
```
With this PR it produces
```
FileNotFoundError: [Errno 2] No such file or directory: 'missing/foo'
```

provide more informative error message for failed open

---

CHANGES.rst
asdf/core/_extensions.py
asdf/core/_integration.py
asdf/core/_validators/ndarray.py
asdf/core/tests/test_integration.py
asdf/exceptions.py
asdf/extension/__init__.py
asdf/extension/_extension.py
asdf/extension/_manager.py
asdf/extension/_manifest.py
asdf/extension/_validator.py
asdf/resource.py
asdf/schema.py
asdf/tags/core/ndarray.py
asdf/tests/test_config.py
asdf/tests/test_extension.py
asdf/tests/test_resource.py
docs/asdf/extending/extensions.rst
docs/asdf/extending/use_cases.rst
docs/asdf/extending/validators.rst
docs/index.rst
pyproject.toml

This resurrects #1050 so that we can merge it to master and include in a 2.x release.

Add new plugin type for custom schema validators

---

CHANGES.rst
asdf/generic_io.py
asdf/tests/test_generic_io.py

Providing a path with two leading slashes results in an invalid parsed path. Catch this case and raise an exception reporting the invalid path.
fixes #1353

catch invalid path parsing for paths with two leading slashes

---

asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_types.py
asdf/types.py
tox.ini

This makes the warning make sense, by only issuing it on immediate children of `CustomType`. It will make astropy/astropy#14395 much simpler.

Make the warning only issue on the very first subclass of `CustomType`

---

.github/workflows/label.yml

Looking at the documentation for the labeler action used, `any_of` is a better choice because It may become necessary to label with more than one backport label. This change supports that logic.

Move label check to using `any_of` instead of `one_of`

---

tox.ini

- `astropy` resolved the `CustomType` warnings in astropy/astropy#14395.
- `specutils` resolved the `CustomType` warnings in astropy/specutils#1012

Remove warning ignores from CI

---

CHANGES.rst
asdf/commands/extract.py
asdf/commands/remove_hdu.py
asdf/commands/tests/test_extract.py
asdf/commands/tests/test_remove_hdu.py
asdf/fits_embed.py
asdf/tests/test_deprecated.py
asdf/tests/test_fits_embed.py
docs/asdf/features.rst
docs/conf.py
pyproject.toml
tox.ini

Support to reading and writing ASDF in fits is moving to [stdatamodels](https://github.com/spacetelescope/stdatamodels).
https://github.com/spacetelescope/stdatamodels/pull/110
fixes #1332

deprecate AsdfInFits

---

asdf/conftest.py
pyproject.toml

The use of relative paths for `--ignore` in the `addopts` configuration for `pytest` means that the tests will fail if pytest is triggered from a directory outside the `asdf` directory. This is because those paths are relative to where the `pytest` command is executed. This is causing the CI to fail in asdf-astropy: https://github.com/astropy/asdf-astropy/actions/runs/4220556775/jobs/7334281038 because warnings are being collected.
This PR fixes this by moving the `--ignore` command-line arguments to the `conftest.py`

Fix bug with running tests in ASDF from path outside asdf

---

.github/workflows/ci.yml
.github/workflows/downstream.yml
.github/workflows/s390x.yml
.github/workflows/scheduled.yml

I have noticed a few things have being occurring since we began splitting off the 2.15.x development for ASDF:
1. A lot of unnecessary workflow runs have taken place; namely, `downstream` and `s390x` workflows seem to be getting run on every push to the `master` and `2.15.x` branches. Essentially this results in a lot of duplicated CI runs. In turn we seem to be running out of runners for our actual PRs, so we end up waiting for CI to run. Since both `downstream` and `s390x` both take a long time to complete (for some of their jobs) and are intended as "smoke" testing, they do not need to be run on every merge to `master` or `2.15.x`. In reality, they only need to be run on a schedule, when called for by the appropriate label in on a PR, or when we push a tag for a release.
2. Our CI, …

Add a scheduled workflow

---

.github/workflows/changelog.yml
.github/workflows/ci.yml
.github/workflows/downstream.yml
.github/workflows/label.yml
.github/workflows/s390x.yml

To give us more available runners, jobs triggered by PRs should cancel previous jobs triggered by that PR (from the same workflow), so that only one instance of each job is running per PR. Currently, if a new commit is pushed to a PR, but the CI has not completed then that instance of the CI will continue to run in addition to the new set of CI which will be triggered by the new commit. This ends up causing us to continue to run no-longer-relevant CI jobs to completion, which uses up job runners.
This PR adds concurrency rules based on: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow to our PR related CI jobs. This should start freeing up runners for asdf.

Add concurrency cancellations to workflows

---

.github/workflows/label.yml

Concurrency groups act funny on `pull_request_target` triggered workflows (`github.ref` becomes the branch being merged into not a reference to the PR branch). Label Checker is a very small and fast workflow, so we don't need concurrency cancelations with it

Remove concurrency cancel for `Label Checker` job

---

.github/workflows/changelog.yml
.github/workflows/label.yml

The meeseeks backports shouldn't have to have a `no-changelog-entry-needed` label for their CI. This PR solves this by moving to the old workflow that was used by astropy for its changelog and is still used by jdaviz. This workflow happens to include skips for meeseeks.
Note the original ASDF workflow was a copy of the astropy one from before it was refactored into the reusable workflow, being used here. So they should operate exactly the same, except for the additional meeseeks logic.

Use reusable changelog workflow

---

.github/workflows/label.yml

Now that branch protection rules are in place for `2.15.x` and backport PRs have been reviewed. It makes sense for these PRs to automatically be "Rebased and Merged" to the `2.15.x` branch if the CI fully passes.
This PR adds CI to trigger adding the `meeseeksmachine` PRs to the automerge queue.

Automatically set automerge for meeseeksmachine

---

CHANGES.rst
asdf/commands/extract.py
asdf/commands/remove_hdu.py
asdf/commands/tests/test_extract.py
asdf/commands/tests/test_remove_hdu.py

these require AsdfInFits support and should have warnings that are not subclasses of DeprecationWarning so they are not ignored by default
fixes #1382

add warning to asdftool extract and remove-hdu commands

---

CHANGES.rst
asdf/asdf.py
asdf/block.py
asdf/commands/tags.py
asdf/commands/tests/test_tags.py
asdf/schema.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/helpers.py
asdf/tests/test_deprecated.py
asdf/tests/test_schema.py
asdf/yamlutil.py

Deprecate:
- run_hook
- run_modifying_hook
- url_mapping
- tag_mapping
- type_index
- resolver
- extension_list

deprecate AsdfFile attrs and methods that use legacy extension api

---

CHANGES.rst

Fixes parsing warnings in our changelog. See: https://github.com/asdf-format/asdf/actions/runs/4234381629/jobs/7356584432#step:3:8 for warnings being fixed.

Fix some warnings raised by the changelog CI

---

CHANGES.rst
asdf/asdf.py
asdf/extension/__init__.py
asdf/extension/_legacy.py
asdf/schema.py
asdf/tests/helpers.py
asdf/tests/test_api.py
asdf/tests/test_deprecated.py
asdf/tests/test_extension.py
asdf/tests/test_schema.py
asdf/tests/test_versioning.py
pytest_asdf/plugin.py
tox.ini

deprecates several helper functions/attributes exposed via `asdf.extensions` that are related to only the legacy extension api:
- default_extensions
- get_default_resolver
- get_cached_asdf_extension_list

deprecation asdf.extension legacy functions

---

asdf/tests/test_file_format.py

While running individual tests, I found a test which raises a deprecation warning when run on its own. This in-itself is a bit disturbing as the warning does not appear when the entire test suite is run.
EDIT: Clarification, the failure that I am speaking of is when the `test_file_format.py` test suite is run by itself.

Fix for missed warning supression

---

CHANGES.rst
asdf/_types.py
asdf/testing/helpers.py
asdf/tests/test_deprecated.py
asdf/tests/test_schema.py

move format_tag to testing.helpers

---

CHANGES.rst
asdf/__init__.py
asdf/asdf.py
asdf/entry_points.py
asdf/extension/__init__.py
asdf/tests/test_asdf.py
asdf/tests/test_config.py
asdf/tests/test_deprecated.py
asdf/tests/test_extension.py
asdf/tests/test_types.py
asdf/tests/test_util.py
pyproject.toml
tox.ini

~~Currently based off of https://github.com/asdf-format/asdf/pull/1409 and should not be merged before that PR.~~

Deprecate AsdfExtension, AsdfExtensionList, BuiltinExtension

---

asdf/commands/tests/test_diff.py
asdf/tags/core/tests/test_complex.py
asdf/tags/core/tests/test_history.py
asdf/tags/core/tests/test_ndarray.py
asdf/tests/test_api.py
asdf/tests/test_array_blocks.py
asdf/tests/test_asdf.py
asdf/tests/test_compression.py
asdf/tests/test_config.py
asdf/tests/test_extension.py
asdf/tests/test_file_format.py
asdf/tests/test_fits_embed.py
asdf/tests/test_generic_io.py
asdf/tests/test_helpers.py
asdf/tests/test_integration.py
asdf/tests/test_reference.py
asdf/tests/test_resolver.py
asdf/tests/test_resource.py
asdf/tests/test_schema.py
asdf/tests/test_search.py
asdf/tests/test_stream.py
asdf/tests/test_types.py
asdf/tests/test_yaml.py
pyproject.toml

Fixes #1342
Adds`match` checks to all the `pytest.raises` checks, so that error messages are checked.

Resolve `PT011` error code

---

docs/asdf/release_and_support.rst

Added a description of the ASDF library version stating that we will maintain backwards API compatibility in minor versions.
fixes #1366

clarify ASDF library versioning strategy

---

asdf/resolver.py
asdf/tests/helpers.py
asdf/tests/test_deprecated.py
asdf/type_index.py
asdf/types.py
docs/asdf/developer_api.rst
pytest_asdf/plugin.py

To add deprecation warnings, several public sub modules were 'shadowed' by moving them to a private file (prefixed with `_`) and adding a stub public module in their place that issued a deprecation warning then replaced itself with the private module. Here is one example:
https://github.com/asdf-format/asdf/blob/6b4701277bb25c1d4e8583b88bc2b125be9a36d6/asdf/types.py#L1-L26
This example illustrates one issue with this approach where certain objects needed special handling to allow doc references to work.
An alternative approach was used for `asdf.tests.helpers`.
https://github.com/asdf-format/asdf/blob/6b4701277bb25c1d4e8583b88bc2b125be9a36d6/asdf/tests/helpers.py#L1-L26
That has several benefits including:
- easier control over what attributes are exposed
- a hook to allow deprecation …

Module shadowing

---

asdf/_tests/test_asdf.py
asdf/_tests/test_deprecated.py
asdf/fits_embed.py
asdf/resolver.py
asdf/type_index.py
asdf/types.py
docs/asdf/asdf_tool.rst
docs/asdf/deprecations.rst
docs/asdf/developer_api.rst
docs/asdf/extending/legacy.rst
docs/conf.py
docs/index.rst

This aims to consolidate tests and documentation for the new deprecation warnings.
The testing missing from test_deprecations (those introduced in #1336) are moved to test_deprecations.
A `Deprecations` page is added to the docs describing the new deprecations and deprecation warnings with migration information. https://asdf--1459.org.readthedocs.build/en/1459/asdf/deprecations.html
Fixes #1346

Consolidate deprecations add deprecations page to docs

---

asdf/block.py
asdf/tags/core/ndarray.py

This is from https://github.com/astropy/astropy/actions/runs/4376653449/jobs/7659080296 for https://github.com/astropy/astropy/pull/14510

np.product is deprecated in numpy 1.25

---

.github/workflows/downstream.yml
tox.ini

astropy was included here because of astropy.io.misc.asdf which is deprecated and uses the legacy extension api (which will be removed during this development cycle). The remaining usage of asdf in astropy is through asdf-astropy.
specutils includes a legacy extension that may be moved to asdf-astropy. Per advice from WilliamJamieson specutils is being removed from downstream testing.

remove astropy and specutils from downstream

---

.readthedocs.yaml
docs/conf.py
docs/rtd_environment.yaml

`tomli` usage combine with `tomli` pin is incorrect for `python 3.11`. Also, switch to using conda and `python 3.11` for RTD build.

Bugfix for docs on python 3.11

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/scheduled.yml
CHANGES.rst
CONTRIBUTING.rst
README.rst
docs/asdf/developer_versioning.rst

After this PR is merged the `master` branch can be renamed to `main`.
We should probably merge https://github.com/asdf-format/asdf-standard/pull/370 first as `asdf-standard` has a hard coded reference to `master`. It's possible github will redirect these (based on https://github.com/github/renaming, but i'm not sure if the ci jobs are considered "web requests").

rename master branch to main

---

CHANGES.rst

Updates the main changelog to reflect the 2.14.4 release.

Forward port changelog changes for 2.14.4 release

---

CHANGES.rst
asdf/_tests/test_array_blocks.py
asdf/_tests/test_compression.py
asdf/_tests/test_config.py
asdf/asdf.py
asdf/block.py
asdf/config.py
asdf/tags/core/ndarray.py
docs/asdf/config.rst

This PR moves:
- `all_array_storage`
- `all_array_compression`
- `all_array_compression_kwargs`
into `asdf.config.AsdfConfig`. These were previously passed around as arguments to several functions during `AsdfFile` writes. By moving them into the config the `AsdfFile` can continue to accept them as arguments to `AsdfFile.write_to` and `AsdfFile.update` (by using the arguments to set the values in the `AsdfConfig` context created within those functions) and now users can also adjust these settings in the config directly.
This helps to make these storage settings available to all functions called within the `AsdfConfig` contexts created during write without having to pass them around as arguments (this proved important for the upcoming deferred block and Converter block storage support).

Move array storage settings to config

---

asdf/_tests/test_array_blocks.py
asdf/block.py

This PR adds an optional `key` argument to `BlockManager.add` and adds `BlockManger.find_or_create_block` to support providing a hashable  `key` when adding a block (different from the default `id(block._data)` used when a key is not provided. This is useful when `id(block._data)` is inconsistent, unavailable, expensive or otherwise inconvenient to use. This is work towards a deferred block system that will add block storage support to the converter.
Note that `BlockManager.__getitem__` was specifically not updated as it would require another local import and provides no additional functionality over the more explicit `find_or_create_block.

add key support to block manager

---

asdf/_tests/test_array_blocks.py
asdf/block.py

This adds a `data_callback` argument to `asdf.block.Block` that allow the block to dynamically load data during write. This is work towards a deferred block implementation where this callback will be used during the deferred write.

Block data callback

---

.readthedocs.yaml
CHANGES.rst

Add date to 2.15.0 changelog section to start the release process.
EDIT: this also includes a modification of the readthedocs configuration to allow the docs to build on rtd. They were failing with a missing `dot` command and the issue with this comment suggests that we were silently depending on this package which was previously installed in older rtd docker images: https://github.com/readthedocs/readthedocs.org/issues/8800#issuecomment-1007261093

update changelog for 2.15.0 release

---

.github/workflows/label.yml

This PR updates the label checker ci job to use the new 2.15.1 milestone (instead of 2.15.0 which was closed following the 2.15.0 release).
The CI for this PR appears to run off the files in the target branch (main) and is failing to assign the updated 2.15.1 milestone.

update label_checker ci job for 2.15.1

---

requirements-dev.txt

CI for a previous PR revealed that the python 3.8 devdeps job failed due to astropy dropping support for 3.8:
https://github.com/asdf-format/asdf/actions/runs/4789902511/jobs/8518523706
This PR removes astropy from python 3.8 devdeps testing (and continues to use the development version of astropy for python 3.9+).

skip astropy dev testing for python 3.8

---

asdf/_tests/tags/core/tests/test_ndarray.py

Astropy removed astropy.io.misc.asdf in their development version.
https://github.com/astropy/astropy/pull/14668
ASDF has one test that silently depended on the astropy.io.misc.asdf submodule to provide an equality function for an AffineTransform.
The PR removing the public API for the legacy extension already deals with this issue but is unlikely to be quickly merged: https://github.com/asdf-format/asdf/pull/1464
This PR includes the updated test from #1464 to not depend on the types provided by the now non-existent astropy.io.misc.asdf which is causing devdeps jobs to fail (as seen in CI runs for this PR https://github.com/asdf-format/asdf/pull/1531).

drop depending on astropy.io.misc.asdf for test

---

.github/workflows/ci.yml
CHANGES.rst
pyproject.toml
requirements-dev.txt
tox.ini

Use new nightly wheels repository: https://anaconda.org/scientific-python-nightly-wheels/repo
drop testing with development scipy (which is not a dependency)

drop python 3.8 support and update CI

---

CHANGES.rst
asdf/_tests/test_generic_io.py
asdf/generic_io.py

fileno is needed for memory mapping and numpy.frombuffer. Test that fileno does not result in an ``io.UnsupportedOperation`` before creating a ``generic_io.RealFile`` and if the error occurs, create a ``generic_io.RandomAccessFile`` instead.
fixes issue #1552

test for valid fileno before creating RealFile

---

CHANGES.rst
asdf/_tests/test_extension.py
asdf/core/_converters/reference.py
asdf/core/_extensions.py
asdf/extension/_converter.py
asdf/extension/_manager.py
asdf/reference.py
asdf/yamlutil.py
docs/asdf/extending/converters.rst

Following the ASDF tag-up discussion here is another option for moving Reference to a converter based on the suggestions from @eslavich 
`asdf.reference.Reference` serializes to an untagged dictionary.
https://github.com/asdf-format/asdf/blob/b0c9a50e8d3add337e1271369a3bf834925176a4/asdf/reference.py#L45-L46
https://github.com/asdf-format/asdf/blob/b0c9a50e8d3add337e1271369a3bf834925176a4/asdf/reference.py#L108-L111
This type of conversion is unsupported in the new extension API (using Converters) in asdf main. To allow `Reference` to be moved to a `Converter` this PR introduces the ability to define converters that defer conversion to other converters (or in the case of `Reference` to un-tagged serialization to a yaml map).
This PR changes the public API of `Converter.select_tag` (in a …

Allow converter deferral and move Reference to a converter

---

asv.conf.json

Currently, the benchmarks at https://spacetelescope.github.io/bench/asdf/ do not show a commit when clicked; this configuration change should fix that.

[benchmarks] add commit URL for showing commits when clicked

---

CHANGES.rst
asdf/_tests/test_yaml.py
asdf/yamlutil.py
requirements-dev.txt

[nep51](https://numpy.org/neps/nep-0051-scalar-representation.html) changes numpy scalars modifying the repr.
this change conflicts with represent_float/int (from pyyaml, which uses repr). With numpy 2.0 (which implements nep51) scalars are being encoded as, for example, 'np.float64(3.14)' instead of '3.14'. To work around this change, convert the values to builtin python types before passing them to pyyaml for encoding.
This PR also disables pyyaml devdeps testing as it is incompatible with cython 3.0 and it's failure to install stops devdeps testing.

convert numpy scalars to python types before yaml encoding

---

asdf/schema.py

`asdf.schema.load_schema` is mentioned in the docs:
https://asdf.readthedocs.io/en/stable/asdf/extending/schemas.html#checking-schema-syntax
but not included in the api documentation. This PR adds `asdf.schema.load_schema` to `asdf.schema.__all__` to include it in the api documentation.
Link to built docs for `asdf.schema`: https://asdf--1600.org.readthedocs.build/en/1600/api/asdf.schema.load_schema.html#asdf.schema.load_schema

add load_schema to asdf.schema.__all__

---

docs/asdf/features.rst

As mentioned: https://github.com/asdf-format/asdf/issues/1588
asdf writes tuples as YAML sequences which are loaded as lists (not tuples). This PR describes the behavior in the documentation and mentions how a custom extension could be used to write/read tuples.

add note about implicit tuple to list conversion on write/read

---

asdf/_tests/test_asdf.py
asdf/asdf.py
asdf/extension/__init__.py
asdf/extension/_converter.py
asdf/extension/_serialization_context.py
docs/asdf/developer_api.rst
docs/asdf/developer_overview.rst
docs/asdf/extending/converters.rst

As far as I can tell, the public usage of SerializationContext occurs exclusively through extensions.
Rather than document `asdf.asdf` (where `SerializationContext` was implemented prior to this PR) which was previously undocumented, this PR moves `SerializationContext` to `asdf.extension._serialization_context` and exposes it publicly at `asdf.extension.SerializationContext`.
Code that imports `SerializationContext` from `asdf.asdf` should continue to work (as `SerializationContext` is imported in `asdf.asdf`) but should be updated to import from the documented public location once this PR makes it into a release.
Link to relevant updated docs: https://asdf--1573.org.readthedocs.build/en/1573/api/asdf.extension.SerializationContext.html#asdf.extension.SerializationContext
Fixes …

move SerializationContext to asdf.extension and add it to docs

---

docs/rtd_environment.yaml

readthedocs is choosing to use an ancient version of the sphinx theme (0.4.3 from 2019). This PR modifies the rtd environment file to require a newer version of the theme.

require and add min version to sphinx theme for rtd

---

.github/workflows/changelog.yml

The scientific-python changelog checker by default also checks milestones. Since https://github.com/asdf-format/asdf/pull/1610 removed the requirement that PRs have milestones this can result in PRs incorrectly failing the changelog check because they don't have a milestone.
The workflow is based largely off of one used for jwst: https://github.com/spacetelescope/jwst/blob/master/.github/workflows/changelog.yml and what was [used previously in asdf](https://github.com/asdf-format/asdf/blob/9e746c899482523b668b8737cd744c4c8fb0c45e/.github/workflows/changelog.yml).

switch to simple changelog check

---

CHANGES.rst
asdf/_tests/test_api.py
asdf/_tests/test_schema.py
asdf/asdf.py

With the removal of the deprecated kwargs the `**kwargs` were also expanded and documented to make it more explicit what arguments are supported.
devdeps will fail due to pyyaml and cython3 incompatibility: https://github.com/yaml/pyyaml/issues/601
stdatamodels downstream failure addressed in: https://github.com/asdf-format/asdf/pull/1594

remove deprecated AsdfFile.open, asdf.open, write_to, update kwargs, 

---

CHANGES.rst
asdf/_tests/_issues/test_1553.py
asdf/_tests/_regtests/test_1553.py
asdf/tags/core/ndarray.py

NDArrayType does not implement this method and if not intercepted (and an AttributeError raised) than AsdfFile.info will load all array data
Fixes: https://github.com/asdf-format/asdf/issues/1553
This PR adds a regression test for this bug.

raise AttributeError for __asdf_traverse__ on NDArrayType

---

CHANGES.rst
asdf/_tests/_issues/test_1558.py
asdf/_tests/_regtests/test_1558.py
asdf/asdf.py

With these changes, when an AsdfFile object is closed the tree (which already could not be accessed because of the tree property gatekeeping) is set to a blank AsdfObject.
This allows the garbage collector to clean up objects referenced in the tree even though the AsdfFile object does not fall out of scope.
Fixes #1558

free tree on AsdfFile.close

---

tox.ini

Updates tox.ini to define used environments as tox 4.9 does not allow 'on-the-fly' environment creation unless the environment is prefixed with `pyXX`.

define python envs in github ci

---

CHANGES.rst
asdf/_tests/test_schema.py
asdf/asdf.py
asdf/schema.py

This PR removes the deprecated `resolve_local_refs` argument to `asdf.schema.load_schema`.

remove deprecated  load_schema argument, resolve_local_refs

---

CHANGES.rst
asdf/asdf.py
pyproject.toml

Testing (by cleaning up out test dependencies that don't yet support python 3.12) revealed only 1 required change to allow asdf to support python 3.12, removal of one use of `utcfromtimestamp`:
https://github.com/asdf-format/asdf/blob/cee306e74217b275a69ee4d7c96b18d1bc55bdd8/asdf/asdf.py#L1339-L1341
The tests can be found here: https://github.com/asdf-format/asdf/pull/1633
This change was broken out into this PR to make backporting easier. Python 3.12 will be released 2023-10-02 and we may want to consider releasing a 2.15.2 that includes the change in this PR even if we release 3.0 before that time (so users that can't yet update to 3.0 have an option to run 3.12).
Updating the CI to test python 3.12 would ideally be included in this PR but given the lack of released 3.12 support for …

Add support for python 3.12

---

asdf/_tests/test_extension.py
asdf/extension/_converter.py
docs/asdf/extending/converters.rst
pyproject.toml
requirements-dev.txt
tox.ini

tldr; #1561 introduced a subtle change to which Converters are ignored. stdatamodels includes an erroneous converter that is now not ignored. This PR fixes the asdf side of the issue (and drops the unused `gwcs` test dependency).
Prior to #1561 the types supported by a converter that doesn't support any tags that are supported by the extension were ignored. The modifications in that PR checked if the converter implemented 'select_tag' and if not ignored the types. However if the converter implemented 'select_tag' the converter types were indexed (as the converter could return None from 'select_tag' and defer to a new converter).
If a converter inherits from Converter it gains the select_tag method from the parent Converter class
(which provides documentation of the method but doesn't …

fix Converter type indexing for Converters not supported by Extension

---

CHANGES.rst
asdf/_jsonschema/exceptions.py
docs/asdf/config.rst
pyproject.toml
requirements-dev.txt

PRs open for downstream users:
- https://github.com/DKISTDC/dkist/pull/295
- https://github.com/BAMWelDX/weldx/pull/886
- https://github.com/spacetelescope/jwst/pull/7880

Drop jsonschema

---

asdf/_tests/test_generic_io.py

Testing with python 3.12 in https://github.com/asdf-format/asdf/pull/1633 revealed an issue with one test that is using `IOBase`. See comment: https://github.com/asdf-format/asdf/pull/1633#discussion_r1328802508
It appears that in python 3.12 `IOBase.__init__` no longer accepts accepts the same arguments. This appears to be an undocumented change (I can't seen to find any documentation) and I don't recall this occurring in rc1. The use of `IOBase` in the test can be replaced with `FileIO` (which fits the usage better).
This change is split from #1633 to make it easier to backport to 2.15.x

switch IOBase to FileIO in test

---

asdf/_tests/test_serialization_context.py
asdf/extension/_serialization_context.py

~based off the changes in: https://github.com/asdf-format/asdf/pull/1537~ EDIT: #1537 is merged
Adds get/set_array_storage/compression to SerializationContext to allow converters to control array storage.
Existing failures for stdatamodels and dkist are expected see: https://github.com/asdf-format/asdf/pull/1537#issuecomment-1707190502
~and currently with jwst due to a requirement for unreleased stcal changes: https://github.com/spacetelescope/jwst/pull/7874~
Closes #1291
Closes #1013

Allow control of array storage via SerializationContext

---

.github/workflows/ci.yml
asdf/_tests/tags/core/tests/test_ndarray.py
asdf/_tests/test_api.py
asdf/_tests/test_asdf.py
asdf/_tests/test_file_format.py
asdf/_tests/test_generic_io.py
asdf/_tests/test_schema.py
pyproject.toml
requirements-dev.txt
tox.ini

~After https://github.com/asdf-format/asdf/pull/1594 is sorted (which at the moment removes the gwcs test dependency) this PR can be finished and brought out of draft.~
~EDIT: based off changes in https://github.com/asdf-format/asdf/pull/1650 which fixes 1 test for python 3.12.~
The changes in this PR clean up the `test` dependencies. Some likely targets are:
- gwcs: looks to be entirely unused
- asdf-astropy: used for a handful of outdated tests and for some tests of 'nested' objects which could be handled by custom objects
- astropy: mostly incorrect usage now that serialization has moved to asdf-astropy
This also adds 3.12 testing which will currently fail because of aiohttp (required by fsspec). See https://github.com/asdf-format/asdf/pull/1651 for results with fsspec removed as a …

Clean up test dependencies, add python 3.12 testing

---

docs/asdf/whats_new.rst

Update the `what's new` page to describe the changes in 3.0.0 and mention significant upcoming changes (turning off memory mapping as default).
Link to built documentation: https://asdf--1649.org.readthedocs.build/en/1649/asdf/whats_new.html#whats-new-3-0-0
Fixes #1628

update docs for 3.0 release

---

.github/dependabot.yml
.github/workflows/s390x.yml
.github/workflows/scheduled.yml
CHANGES.rst
docs/asdf/release_and_support.rst

update changelog
remove CI tests for 2.15 branch
remove commented out description of 2.15 as a considered LTS in docs

prep for 3.0 release

---

tox.ini

These improvements to `tox.ini` were originally included in #1651 I split them off into this separate PR so that the changes can make it into main and that test PR can be closed.
devdeps failures are unrelated and addressed in: #1665

add devdeps parameterization to tox.ini environments

---

asdf/_tests/test_generic_io.py
asdf/generic_io.py

`np.core` is deprecated in numpy 2.0 and causing failures in the devdeps tests:
https://github.com/asdf-format/asdf/actions/runs/6619133498/job/17979194872?pr=1664#step:10:607
This PR replaces all references to `np.core.memmap` with `np.memmap` to fix these errors.

use np.memmap instead of np.core.memmap

---

.github/workflows/ci.yml

The OpenAstronomy build workflow uses python version `3.x`. This is now defaulting to `3.12`. As `aiohttp` does not yet have a stable python 3.12 version (and this is a test dependency installed as part of the build testing run) this is causing build to fail:
https://github.com/asdf-format/asdf/actions/runs/6657397904/job/18092159951?pr=1668
This PR forces the build version to 3.11.

build with python 3.11 (not 3.12)

---

.github/issue_template.md
.github/pull_request_template.md
.github/workflows/ci.yml

Since pre-commit-ci will no longer be auto-fixing PRs this PR also adds:
- a workflow that runs pre-commit (the branch protections will be updated when this PR is merged to make this a required job)
- a pull request template describing running pre-commit, pytest, etc
I also added an issue template to this PR since it seems like a good thing to provide.
Fixes https://github.com/asdf-format/asdf/issues/1679

add pre-commit workflow to replace pre-commit-ci

---

CHANGES.rst
asdf/_block/external.py
asdf/_block/io.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_util.py
asdf/commands/diff.py
asdf/commands/main.py
asdf/core/_converters/complex.py
asdf/generic_io.py
asdf/reference.py
asdf/schema.py
asdf/util.py
asdf/yamlutil.py
docs/asdf/deprecations.rst
pytest_asdf/plugin.py

This PR starts the cleanup of the asdf api starting with the `asdf.util` submodule. This PR includes the following deprecations:
- deprecate `human_list` (unused in downstream)
- deprecate `resolve_name` and `minversion` (these are out-dated copies from `astropy.utils`, the one use in the asdf pytest plugin was replaced, these methods are unused in downstream)
- deprecate `iter_subclasses` (unused in downstream, replaced with `_iter_subclasses` for internal uses)
The following were not listed in `__all__` and are only used internally. Each was modified to be prefixed with an `_` to make their `private` nature more explicit:
- `BinaryStruct`
- `InheritDocstrings`
- `patched_urllib_parse`
One addition was made to the public api:
- add `get_file_type` and `FileType` to `__all__` (these are …

Cleanup `asdf.util`

---

.github/workflows/ci.yml
pyproject.toml

Add a non-devdeps python 3.12 run to the CI (and update devdeps 3.12 to use released 3.12).
This PR also adds a minor change to the pytest defaults to include failed and errored tests in the summary output.

test py312 non-devdeps

---

CHANGES.rst

Fix a typo in the changelog listing #1690 (which has not been released) under 3.0.1 (which has been released).

fix changelog typo

---

CHANGES.rst
asdf/_asdf.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_reference.py
asdf/reference.py
docs/asdf/deprecations.rst

Deprecate the automatic calling of `AsdfFile.find_references` during `AsdfFile.__init__` and `asdf.open`. A warning will only appear if a reference is found. References appear to be unused in all known downstream packages so I don't expect we will see any of these warnings. `find_references` walks and modifies (so performs a deep copy of) the tree so the eventual removal of this automatic calling should speed up most calls to `AsdfFile.__init__` and `asdf.open`.

deprecate find_references calls during AsdfFile.__init__ and open

---

CHANGES.rst
asdf/_display.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_info.py
asdf/_tests/test_util.py
asdf/util.py

For childless (leaf) nodes, show the `str` value (when `show_values` is `True`). This allows objects like `Time` to display their value.
For example, on main when running `asdftool info some_roman_file.asdf` the output will contain:
```
│ │ ├─start_time (Time)
│ │ ├─mid_time (Time)
│ │ ├─end_time (Time)
```
With this PR the same file contains the output:
```
│ │ ├─start_time (Time): 2021-01-01T00:00:00.000
│ │ ├─mid_time (Time): 2021-01-01T00:01:16.020
│ │ ├─end_time (Time): 2021-01-01T00:02:32.040
```
This PR also deprecates the now unused `asdf.util.is_primitive`.
Fixes #1686

Display value for all childless nodes during `info`

---

CHANGES.rst
asdf/_tests/tags/core/tests/test_integer.py
asdf/_tests/test_reference.py
asdf/_tests/test_util.py
asdf/commands/edit.py
asdf/util.py

This PR introduces `asdf.util.load_yaml` to load the yaml contents of an ASDF file.
```python
import asdf
tree = asdf.util.load_yaml("test.asdf")
tagged_tree = asdf.util.load_yaml("test.asdf", tagged=True)
```
This is an alternative to #1677 and can be used to replace the (many) uses of `_force_raw_types` in downstream code and `_get_yaml_content` (see note below about `sphinx-asdf`).
It should be possible to remove `_force_raw_types` once all the downstream packages have removed its usage. This PR removes the use of this argument in `asdftool edit`. `asdftool diff` will require more work to remove the use of `_force_raw_types`. At the moment this PR does not deprecate nor remove `_force_raw_types`.
Although `_get_yaml_content` is no longer used in asdf with this PR it is used in …

Introduce `asdf.util.load_yaml`

---

CHANGES.rst
pyproject.toml
pytest_asdf/plugin.py
tox.ini

This PR increases the minimum required pytest to 7+, updates the asdf pytest plugin for changes in pytest 8.1 (the current development version) and updates the `pytestdev` tox factor to test against the github/development version (instead of any pre-release).
Fixes https://github.com/asdf-format/asdf/issues/1730

require pytest 7+ update for pytest 8.1.dev

---

tox.ini

astrocut tests seem to be downloading files which is randomly failing.
See: https://github.com/asdf-format/asdf/actions/runs/7718257705/job/21039125750?pr=1745#step:10:463
and: https://github.com/asdf-format/asdf/actions/runs/7717678770/job/21037293335#step:10:559
As we're mainly interested in making sure the asdf portion of astrocut is not impacted by changes here this PR restricts the tests to those defined in [test_asdf_cut](https://github.com/spacetelescope/astrocut/blob/main/astrocut/tests/test_asdf_cut.py).
The change here is similar to restrictions placed on other downstream tests:
- [weldx](https://github.com/asdf-format/asdf/blob/7ae2d7eb198b4ef433eed6be8394a18ac22af619/tox.ini#L310)
- [sunpy](https://github.com/asdf-format/asdf/blob/7ae2d7eb198b4ef433eed6be8394a18ac22af619/tox.in …

restrict astrocut tests

---

benchmarks/schema.py

As asdf no longer depends on jsonschema the benchmark that tests jsonschema will fail (as it's not installed).
This PR removes the jsonschema benchmark.
This should fix: https://github.com/spacetelescope/bench/issues/72

remove jsonschema benchmark

---

CHANGES.rst
asdf/_asdf.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_schema.py
docs/asdf/deprecations.rst
docs/asdf/features.rst

This PR deprecates automatic validation on assignment to `AsdfFile.tree`. This long-undocumented feature (documentation added in asdf 3.0 #1599) can be replaced by a call to `AsdfFile.validate` after tree assignment (which is already necessary for tree assignments that don't replace the entire tree).
The eventual disabling of the deprecated feature will allow downstream code that currently uses the non-public `_tree` attribute (to avoid the validation on assignment) to be updated to use the public `tree`. Here are a few examples:
- https://github.com/spacetelescope/stdatamodels/blob/4a06de96585dad1c8497e4fd01d4041ee2c210b4/src/stdatamodels/model_base.py#L623
- https://github.com/spacetelescope/stdatamodels/blob/4a06de96585dad1c8497e4fd01d4041ee2c210b4/src/stdatamodels/fits_support.py#L772 …

deprecate validation on AsdfFile.tree assignment, AsdfFile.__init__ and AsdfFile.resolve_references

---

pyproject.toml

ruff now requires that `select` and `extend-ignore` be in `tool.ruff.lint`. This PR updates pyproject.toml to satisfy this new requirement.

update pyproject.toml for new ruff requirements

---

asdf/_tests/test_yaml.py
asdf/yamlutil.py

This PR updates yamlutil to use `ConstructorError` from `yaml.constructor` instead of `yaml` (where it does not appear to be available in yaml 6.0 (and likely many earlier versions). This change is compatible with our minimum yaml version (5.4.1): https://github.com/yaml/pyyaml/blob/b79e34b37e676371a6a104970a8a944fb514b679/lib/yaml/constructor.py#L8
A parametrized test was added to cover the code that was updated (no test appears to have been covering these `raises`).
Fixes #1713

fix yaml.constructor.ConstructorError import

---

CHANGES.rst
asdf/_display.py
asdf/_tests/test_info.py

if `__str__` fails during `asdf.info` or returns multiple lines then don't show the value.
This fixes the current roman_datamodels downstream job which is failing due to a wcs which contains no transforms which causes gwcs to fail a `__str__` call.
A PR is open to fix the `__str__` issue in gwcs: https://github.com/spacetelescope/gwcs/pull/489
However even with the above fix the `WCS.__str__` result is a multi-line string which breaks `info` formatting. To deal with this, this PR also checks the `__str__` output for multiple lines and in that case discards the `__str__ ` result.
To provide a few examples using a tree containing `gwcs.WCS(output_frame="icrs")`.
Without the gwcs PR and with asdf main, asdf.info returns:
```
File ~/projects/src/gwcs/gwcs/wcs.py:1347, in WCS.__str__(self) …
```

info don't show value for bad __str__

---

.github/workflows/s390x.yml
asdf/util.py
docs/conftest.py
pyproject.toml
tox.ini

pytest-doctestplus is listed as a test dependency. However, none of the "plus" features are used and this PR drops it as a dependency and replaces it with the builtin doctest.
With this PR the 3.11 tests pick up 1756 tests
https://github.com/asdf-format/asdf/actions/runs/8143804626/job/22256481482?pr=1765#step:10:247
this is the same as the 3.11 tests for main:
https://github.com/asdf-format/asdf/actions/runs/8096624540/job/22125799613#step:10:248

drop doctestplus test dependency

---

.github/workflows/ci.yml
docs/asdf/extending/schemas.rst

Fix a few docs links (due to changes in the asdf-standard docs) and modify the CI jobs to not prevent jobs from running if the `asdf-schemas` job fails (as it does now).

Fix docs and modify CI job run requirements

---

CHANGES.rst
asdf/_asdf.py
asdf/_tests/_helpers.py
asdf/_tests/test_api.py
asdf/_tests/test_array_blocks.py
asdf/_tests/test_asdf.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_file_format.py
asdf/_tests/test_schema.py
asdf/_tests/test_types.py
asdf/_tests/test_yaml.py
asdf/versioning.py
asdf/yamlutil.py
pytest_asdf/plugin.py

This PR:
- deprecates `AsdfFile.version_map`
- removes asdf uses of `versioning.get_version_map` (which this PR also renames to `_get_version_map` as it is undocumented, not listed in `versioning.__all__` and unused by all known downstream packages)
- no longer relies on the [version maps in asdf-standard](https://github.com/asdf-format/asdf-standard/blob/main/resources/schemas/stsci.edu/asdf/version_map-1.6.0.yaml) to map asdf standard versions to file format and yaml versions
Note that at the moment ASDF only supports file format 1.0.0 and yaml 1.1. This PR adds those constants to `asdf.versioning`.
When this PR is merged a new issue can be opened to track the removal of `AsdfFile.version_map` in asdf 4.0. The PR that removes `version_map` can also remove `versioning._get_version_map`. …

Deprecate `AsdfFile.version_map`

---

CHANGES.rst
asdf/_tests/tags/core/tests/test_ndarray.py
asdf/tags/core/ndarray.py
pyproject.toml

This PR adds `float16` support to asdf. As this requires changes to the `ndarray` schema (part of the asdf standard) ~this PR currently has `asdf-standard` installed via git from the source branch for: https://github.com/asdf-format/asdf-standard/pull/411~ EDIT: a new version of `asdf-standard` was released

add float16 support

---

.github/workflows/ci.yml
CHANGES.rst
pyproject.toml
requirements-dev.txt
tox.ini

Removes the now-decommissioned [asdf-unit-schemas](https://github.com/asdf-format/asdf-unit-schemas) from the list of dependencies and updates the CI to:
- no longer test `asdf-unit-schemas`
- remove `asdf-wcs-schemas` and `asdf-coordinates-schemas` (which aren't dependencies) from `requirements-dev.txt`

Remove unused `asdf-unit-schemas` update CI

---

CHANGES.rst
asdf/_node_info.py
asdf/_tests/_regtests/test_1738.py

This PR adds a check for a `_tag` attribute before attempting to fetch schema for a node during `NodeSchemaInfo` tree traversal.
The current code assumes that any object implementing `__asdf_traverse__` also has a `_tag` attribute which contains a valid tag.
"duck typing" was used here (instead of checking for `isinstance(Tagged)` as `roman_datamodels` defines non-Tagged objects that contain valid `_tag` attributes.
Fixes #1738
The weldx failure is unrelated (caused by a new pandas version) the roman_datamodels failure is addressed in: https://github.com/asdf-format/asdf/pull/1748

fix __asdf_traverse__ for non-tagged object

---

CHANGES.rst
asdf/_tests/test_deprecated.py
asdf/_tests/test_schema.py
asdf/_tests/test_versioning.py
asdf/testing/helpers.py
asdf/versioning.py

This PR deprecates `asdf.testing.helpers.format_tag` (and replaces it's one use with a string) and `asdf.versioning.AsdfSpec` (which is unused).
Fixes: #1773

Deprecate `asdf.testing.helpers.format_tag` and `asdf.versioning.AsdfSpec`

---

CHANGES.rst
asdf/_asdf.py
asdf/_tests/test_api.py
asdf/exceptions.py

This PR adds the package name and version for the package providing the manifest used to create an extension that was used to write the file. For example, writing out a file with this PR produces a `history`:
```yaml
history:
extensions:
- !core/extension_metadata-1.0.0
extension_class: asdf.extension._manifest.ManifestExtension
extension_uri: asdf://asdf-format.org/core/extensions/core-1.5.0
manifest_software: !core/software-1.0.0 {name: asdf-standard, version: 1.0.4.dev153+gcafd84a}
software: !core/software-1.0.0 {name: asdf, version: 3.0.2.dev81+g67e7a8e3.d20240205}
```
This will be beneficial for tracking what software was used for the many asdf extensions that use manifests from other packages (like `gwcs` and `asdf-wcs-schemas`, `roman_datamodels` and `rad`, etc...).
This new …

Record manifest providing package in history, use specific warning for `_check_extensions`

---

CHANGES.rst
asdf/_tests/_regtests/test_1715.py
asdf/reference.py

Remove use of `json_id` in `find_references` callback passed to `walk_and_modify`.
The `json_id` argument (which stores the most recently encountered 'id' value) is primarily (perhaps only) useful for schema parsing. However, `find_references` (called on the ASDF tree) uses the `json_id` value to construct the uri for the referred object. I see no reference to this behavior in:
https://datatracker.ietf.org/doc/html/rfc6901
https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03
https://datatracker.ietf.org/doc/html/rfc3986
and this can lead to reference resolution failure (see #1715).
Fixes #1715

fix bug where a dict with an id causes contained refs to fail to resolve

---

CHANGES.rst
asdf/_asdf.py
asdf/_tests/test_extension.py
asdf/exceptions.py
tox.ini

https://github.com/asdf-format/asdf/pull/1758 assumed that the `uri` used for a manifest matches the `id` in the manifest. This should be the case (as defined in the [extension manifest schema](https://github.com/asdf-format/asdf-standard/blob/1458b25b3092231a7b023ac934ebb7bd31f77d3f/resources/schemas/asdf-format.org/core/extension_manifest-1.0.0.yaml#L23)). However this was not previously being checked. Both [dkist](https://github.com/asdf-format/asdf/actions/runs/9002886955/job/24732233076#step:10:1157) and [weldx](https://github.com/asdf-format/asdf/actions/runs/9002886955/job/24732232556#step:10:10740) downstream jobs show failures since both these packages use manifests with ids that do not match the uris. The dkist failure is due to use of sunpy manifests (which are [fixed in main …

issue warning if manifest id does not match uri

---

CHANGES.rst
asdf/_tests/test_extension.py
asdf/extension/_manager.py
docs/asdf/extending/converters.rst

This changes how converters with class paths/names as types are handled by asdf.
Prior to PR, when converting a class instance (foo) of class (Foo) the class path of the instance was inspected with ``get_class_name`` and the ``_converters_by_type`` index was searched using the class name. This index contained both classes and class paths (as converters could use both/either) with classes being preferred. This creates issues when a module has a different class path from the typical 'public' path for the class as the module might move the private implementation without changing the 'public' path with the expectation that this will not break downstream code. For converters that use class paths these types of moves will break the converter.
This PR changes the handling of class paths used for …

index converters by type when no converter is found

---

CHANGES.rst
asdf/_asdf.py
asdf/_block/manager.py
asdf/_block/options.py
asdf/_core/_converters/ndarray.py
asdf/_tests/test_array_blocks.py
asdf/_tests/test_config.py
asdf/_tests/test_serialization_context.py
asdf/config.py
asdf/extension/_serialization_context.py
docs/asdf/arrays.rst
docs/asdf/config.rst

This PR adds:
- `AsdfConfig.default_array_save_base`
- `AsdfFile.set_array_save_base` (and `AsdfFile.get_array_save_base`)
- `SerializationContext.set_array_base` (and `SerializationContext.get_array_save_base`)
that control if asdf will save the "base" array when an array view is saved.
`default_array_save_base` was used here instead of `all_array_save_base` as a step towards https://github.com/asdf-format/asdf/issues/1503
Fixes #1669 #1005

add option to control base array saving

---

CHANGES.rst
asdf/_asdf.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_yaml.py
asdf/treeutil.py
docs/asdf/deprecations.rst

This is work towards fixing #1723
This PR deprecates "implicit conversion" and the flag controlling warning messages when this behavior occurs (`ignore_implicit_conversion`). See the above issue for more details. In brief, this prevents extensions from adding support for `namedtuple` classes.
The removal of this feature (after the deprecation period, which this PR will start) will mean that attempting to add a `namedtuple` to the asdf tree (without implementing a converter for the `namedtuple`) will result in an error. The effectively drops the "support" we currently have for `namedtuple` (which does not roundtrip, loses all `namedtuple` specifics and saves these instances as lists). User code that wishes to continue to support `namedtuple` instances will need to:
- convert them all to …

deprecate ignore_implicit_conversion and implicit_conversion

---

asdf/_asdf.py

These are unused as seen in the coverage (and searching the asdf and downstream code):
https://app.codecov.io/gh/asdf-format/asdf/blob/main/asdf%2F_asdf.py#L1600
and appear to be related to the removed `TypeIndex` and could have been removed in: https://github.com/asdf-format/asdf/pull/1637

remove unused `_warn_tag_mismatch` and `_warned_tag_pairs`

---

.github/workflows/ci.yml
tox.ini

Add python 3.13 testing. It looks like (with our devdeps) that python 3.13 is supported (at the moment, all tests pass with 3.13). This PR does not add "official" 3.13 support as it's still in beta.

python 3.13 testing

---

.readthedocs.yaml

Applies changes from https://github.com/spacetelescope/jwst/pull/8633
to allow removal of the stable branch (RTD will automatically generate one since we're semantically versioned).
I've already renamed the stable branch to "old_stable".

get tags for rtd

---

.github/workflows/build.yml
.github/workflows/ci.yml

closes #1763  
run `build.yml` on pull requests as part of the CI, and include import tests on the built wheel. Upon being triggered by a release, also upload to PyPI

consolidate build workflow

---

pyproject.toml

As reported in https://github.com/asdf-format/asdf/issues/1804 one of our tests fails when run with pytest < 8.
This PR pins pytest to > 8.
Fixes: https://github.com/asdf-format/asdf/issues/1804

require pytest 8 to deal with warnings change

---

CHANGES.rst
asdf/_tests/test_extension.py
asdf/_tests/test_yaml.py
asdf/exceptions.py
asdf/yamlutil.py
docs/conf.py

asdf currently produces an unhelpful message for some objects that fail to serialize during `asdf.write_to`:
```python
import asdf, collections
class MyDict(collections.UserDict):
pass
asdf.AsdfFile({"d": MyDict({"a": 1})}).write_to("foo.asdf")
```
Produces:
```
...
yaml.representer.RepresenterError: ('cannot represent an object', {'a': 1})
```
This PR adds a new exception `AsdfSerializationError` that includes the object type in the error message when yaml emits a `yaml.representer.RepresenterError` (for backwards compatibility the new exception inherits from `yaml.representer.RepresenterError`).
Running the above example with this PR produces:
```
asdf.exceptions.AsdfSerializationError: ("Object of type[<class '__main__.MyDict'>] is not serializable by asdf. Please convert the object to …
```

improve error when an object fails to serialize

---

CHANGES.rst
asdf/_entry_points.py
asdf/_tests/test_entry_points.py
asdf/util.py
docs/conf.py
pyproject.toml

This is a follow up to #1260: according to [the comment linked](https://github.com/python/importlib_metadata/issues/410#issuecomment-1304258228) in that PR's commit message, standard library `importlib.metadata` isn't problematic starting from Python 3.12

DEP: drop importlib_metadata as a dependency on Python 3.12 and newer

---

CHANGES.rst
asdf/_jsonschema/exceptions.py
asdf/_jsonschema/tests/_suite.py
pyproject.toml

`attrs` 24.1.0 (released yesterday) deprecated the `hash` argument in favor of `unsafe_hash`
For simplicity of implementation, I also bumped the minimal requirement to 22.2.0, which added the `unsafe_hash` argument.
xref https://github.com/python-attrs/attrs/pull/1323
For context, I noticed this because it breaks astropy's CI, so please let me know if this patch can be released promptly or not. We'll be able to adapt in any case.

MNT: handle a deprecation warning from `attrs` v24.1.0

---

CHANGES.rst
README.rst
asdf/_asdf.py
asdf/_tests/_regtests/test_1334.py
asdf/_tests/_regtests/test_1525.py
asdf/_tests/_regtests/test_1530.py
asdf/_tests/_regtests/test_1558.py
asdf/_tests/tags/core/tests/test_ndarray.py
asdf/_tests/test_api.py
asdf/_tests/test_array_blocks.py
asdf/_tests/test_deprecated.py
asdf/_tests/test_yaml.py
docs/asdf/arrays.rst

deprecate `copy_arrays` with warning

---

.readthedocs.yaml

Applies same changes as https://github.com/spacetelescope/jwst/pull/8644/
to try to get the stable version to show a non-dev tag
Fixes https://github.com/asdf-format/asdf/issues/1798

ignore files changed by rtd to fix version

---

.readthedocs.yaml

fix readthedocs build to not require user input for `towncrier build`

---

asdf/_asdf.py
asdf/_tests/test_deprecated.py
changes/1819.removal.rst
pytest_asdf/plugin.py

This PR deprecates `ignore_version_mismatch`. Since asdf 3.0.0 it has done nothing (it was only used for the legacy extension API which was removed in asdf 3.0.0).
There are a few downstream uses in stdatamodels mostly in tests. However there is one jwst test that fails due to a non-specific warning filter:
https://github.com/spacetelescope/jwst/blob/89f126a035751674f29a9027e2deae11b3e63fca/jwst/assign_wcs/tests/test_schemas.py#L57
Requires https://github.com/spacetelescope/stdatamodels/pull/313
and likely https://github.com/spacetelescope/jwst/pull/8693 (or a release of stdatamodels with the above PR)
before merging. I'm opening it for review now in case there is discussion about the warning message (changes to the message would require updating the jwst PR).
Closes …

deprecate ignore_version_mismatch

---

tox.ini

dkist added benchmarks to their test suite in https://github.com/DKISTDC/dkist/pull/382
which they disable for unit test runs using [--benchmark-skip](https://github.com/DKISTDC/dkist/pull/382/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R38)
This PR adds the same skip to our downstream dkist test (which is otherwise [failing](https://github.com/asdf-format/asdf/actions/runs/10942008003/job/30377992700?pr=1744) on the benchmarks).
</details>

skip dkist benchmarks

---

CHANGES.rst
changes/1819.removal.rst
changes/1825.bugfix.rst
changes/1827.doc.rst
changes/1828.general.rst
changes/1830.doc.rst

Romancal regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/11151181622
JWST regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/11151191151
match those on main: https://github.com/spacetelescope/RegressionTests/actions/runs/11135377170
</details>

update changelog for 3.5.0

---

.github/workflows/ci.yml

Python 3.13 is released. This PR switches our CI to use the released (instead of the dev) version.
</details>

use non-dev python 3.13

---

.github/workflows/downstream.yml
tox.ini

This PR adds https://github.com/abacusorg/abacusutils to our downstream tests.
The tox environment was largely modeled on the test setup in the downstream repo:
https://github.com/abacusorg/abacusutils/blob/6e18f79fc31aea7973abbb144b78d049a2452eeb/.github/workflows/tests.yml#L84
as there are a few "difficult to install" dependencies.
The tests are currently passing but do show some warnings related to asdf:
```
/home/runner/work/asdf/asdf/asdf/_asdf.py:189: AsdfWarning: copy_arrays is deprecated; use memmap instead. Note that memmap will default to False in asdf 4.0.
```
which are expected following the deprecation of `copy_arrays` https://github.com/asdf-format/asdf/pull/1797
- ``changes/<PR#>.doc.rst``: …

add abacusutils to downstream

---

asdf/_extern/atomicfile.py

Fixes #1850
The STScI central store network mount does odd things with `._` files.
```python
>>> f = open("._foo", "wb")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '._foo'
>>> f = open(".bam", "wb")
>>> f = open("._foo", "wb")
```
This causes issues for asdf which uses `.___atomic_write...` temporary files. This PR changes the files to `.asdf_tmp...` to work around the problematic mount.
</details>

change atomic file prefix

---

.github/pull_request_template.md

The current pull request checklist is formatted a bit wonky (`details` spaces out the task list)
</details>

improve pull request template checklist

---

asdf/_tests/test_extension.py
asdf/extension/_converter.py
changes/1853.feature.rst

Closes #1632
For a converter that supports multiple tags but does not implement select tag, raise a RuntimeError (instead of a warning). Previously a warning was produced only for `Converter` subclasses (virtual subclasses produced RuntimeErrors). Now both real and virtual subclasses produce errors.
</details>

Error for Convert subclasses with multiple tags if select_tag isn't implemented

---

README.rst
asdf/_asdf.py
asdf/_tests/test_array_blocks.py
asdf/_tests/test_deprecated.py
changes/1800.removal.rst

remove `copy_arrays` parameter

---

asdf/_tests/test_yaml.py
asdf/config.py
changes/1858.removal.rst
docs/asdf/config.rst

Switches the default value for [convert_unknown_ndarray_subclasses](https://asdf.readthedocs.io/en/latest/api/asdf.config.AsdfConfig.html#asdf.config.AsdfConfig.convert_unknown_ndarray_subclasses) to False and issues an `AsdfDeprecationWarning` if this setting is enabled. We can remove it in asdf 5.0.
</details>

switch convert_unknown_ndarray_subclasses to False

---

asdf/_asdf.py
asdf/_tests/tags/core/tests/test_ndarray.py
asdf/_tests/test_api.py
asdf/_tests/test_array_blocks.py
asdf/_tests/test_generic_io.py
asdf/_tests/test_reference.py
changes/1801.general.rst
docs/asdf/whats_new.rst

based on (and blocked by) https://github.com/asdf-format/asdf/pull/1800
default `memmap=False`

default `memmap` parameter to `False`

---

.github/workflows/downstream.yml

roman_datamodels (one of the packages we test in our downstream CI) now requires at least python 3.11. This PR updates the python versions used for our downstream testing to python 3.12 (from python 3.10).
The specutils failure is caused by gwcs and is fixed in https://github.com/spacetelescope/gwcs/pull/508 which is unreleased. I'm ok with this failing until a gwcs release is made.
The weldx failure is due to a pin for asdf < 4. We could consider disabling that job but I'm ok with it being a known failure.
- …

update downstream jobs to run on python 3.12

---

.github/workflows/downstream.yml
tox.ini

- remove weldx
- change abacusutils tests per suggestion: https://github.com/asdf-format/asdf/pull/1845#issuecomment-2407650943
</details>

cleanup downstream

---

asdf/_asdf.py
asdf/_node_info.py
asdf/_tests/test_info.py
asdf/exceptions.py
changes/1875.bugfix.rst

`schema_info` currently fails to find both subschemas and attributes of subschemas for schemas that use certain "combiners" (like `allOf`) and/or references.
This PR updates `schema_info` to support more schema configurations (including `$ref` and `allOf` usage).
~Requires https://github.com/spacetelescope/rad/pull/525 as the rad schemas contain invalid extra `$ref` items.~ EDIT: rad PR was merged see comment below about [compatibility](https://github.com/asdf-format/asdf/pull/1875#issuecomment-2546691245) (tldr; we'll want to set the asdf min in rad to >4.0.x when the changes in this PR are released)
- ``changes/<PR#>.doc.rst``: documentation …

improve schema info collection combiner handling

---

pyproject.toml

When the switch was made from `write_to` to `version_file`, the version requirement on setuptools_scm was not increased. `version_file` is only available as of v8, https://github.com/pypa/setuptools-scm/blob/v8.0.4/CHANGELOG.md?plain=1#L62.
Most tasks below are not applicable.

pyproject.toml: version_file requires setuptools_scm>=8

---

tox.ini

The dkist downstream job is failing:
https://github.com/asdf-format/asdf/actions/runs/12910632436/job/36001118249#step:10:493
This is due to the current test configuration being incompatible with the ignores in the dkist pytest.ini configuration file (the tests are run in `./dkist` but the configuration assumes the tests are run in `./`).
This PR updates the dkist downstream CI to be compatible with the dkist pytest configuration.
</details>

fix dkist downstream test

---

CHANGES.rst
changes/1875.bugfix.rst
changes/1880.doc.rst
changes/1884.bugfix.0.rst
changes/1884.bugfix.1.rst
changes/1884.bugfix.2.rst
changes/1884.bugfix.3.rst
changes/1884.feature.rst
changes/1897.doc.rst

Regtests:
JWST: https://github.com/spacetelescope/RegressionTests/actions/runs/13076554018/job/36490187942
Romancal: https://github.com/spacetelescope/RegressionTests/actions/runs/13076556498/job/36490167650
</details>

prep 4.1.0 release notes

---

tox.ini

https://github.com/spacetelescope/astrocut/pull/141 moved the asdf related tests in astrocut. This PR updates our downstream CI to use the new tests.
https://github.com/asdf-format/asdf/actions/runs/13766003671/job/38492519757
passing with this PR
(for reference failing on main due to no tests run https://github.com/asdf-format/asdf/actions/runs/13758873655/job/38470764784)
</details>

fix downstream astrocut tests

---

asdf/_tests/tags/core/tests/test_ndarray.py
asdf/tags/core/ndarray.py
changes/1901.bugfix.rst

The ndarray schema doesn't prevent additional keywords in datatype definitions for structured datatypes.
https://github.com/asdf-format/asdf-standard/blob/c17c3ecabcad7b65e41e0fb79054988b37f45a38/resources/schemas/stsci.edu/asdf/core/ndarray-1.1.0.yaml#L214
For example, adding a description to a sub-datatype doesn't violate the schema:
```yaml
datatype:
- name: a
description: a description
datatype: int8
```
However it fails the custom datatype validation in asdf.
This PR updates the custom datatype validator to only compare a selection of datatype keys `{"name", "datatype", "byteorder", "shape"}`. This allows adding descriptions to sub-datatypes.
Fixes #1900
- …

allow extra keywords in structured datatype validation

---

asdf/_tests/test_util.py
asdf/yamlutil.py
changes/1907.bugfix.rst

Closes #1821
The fix in #1825 was partial (only covering non-tagged nodes) since `construct_mapping` is not a generator but `construct_yaml_map` is).
This PR updates `_IgnoreCustomTagsLoader` to use `construct_yaml_map` and `construct_yaml_seq` (both generators) to handled tagged recursive structures.
</details>

use yaml constructors for _IgnoreCustomTagsLoader

---

tox.ini

astrocut moved their asdf tests in https://github.com/spacetelescope/astrocut/pull/149
This PR updates the astrocut downstream tests here to use `--pyargs` which looks to be the expected way to run these tests based on:
https://github.com/spacetelescope/astrocut/blob/9c5aebecd806705e3942bd9204dd8be705b38059/tox.ini#L65
also rather than calling just the asdf tests (which breaks every time they rename/reorg the test files) this PR also just runs all astrocut tests.
- ``changes/<PR#>.general.rst``: infrastructure or miscellaneous …

fix astrocut downstream tests

---

.github/workflows/downstream.yml

Re-enables weldx downstream tests.
weldx tests are now passing: https://github.com/asdf-format/asdf/actions/runs/14647049842/job/41103793924?pr=1919
Closes #1870
</details>

add weldx downstream

---

.pre-commit-config.yaml
asdf/__init__.py
asdf/_asdf.py
asdf/_display.py
asdf/commands/__init__.py
asdf/commands/exploded.py
asdf/config.py
asdf/generic_io.py
asdf/reference.py
asdf/resource.py
asdf/schema.py
asdf/tagged.py
asdf/tags/core/__init__.py
asdf/treeutil.py
asdf/util.py
asdf/versioning.py
pyproject.toml

Closes #1911
This required updating the pre-commit hooks as older versions of the pyproject.toml validator don't understand `license-files`. This also updated the ruff version and pulled in some new rules mainly sorting `__all__`. I can roll back this change if preferred.
</details>

update pyproject.toml to avoid setuptools warnings

---

asdf/_block/reader.py
asdf/_tests/_block/test_reader.py
changes/1918.bugfix.rst

On main if padding bytes are found between the end of the tree and the beginning of the first block they must be all null.
https://github.com/asdf-format/asdf/blob/ad470c0cac455d8297a484b2541254f06f2a139d/asdf/_block/reader.py#L172-L173
This doesn't agree with the [standard](https://www.asdf-format.org/projects/asdf-standard/en/1.1.1/file_layout.html#tree):
> This empty space may be filled with any content (as long as it doesn’t contain the block_magic_token described in [Blocks](https://www.asdf-format.org/projects/asdf-standard/en/1.1.1/file_layout.html#block)).
This PR updates the block parsing to allow non-null bytes as long as they don't match the block magic. Since the block header does not contain a checksum of the header bytes it's not possible to detect invalid padding (that …

allow non-null post tree pre block padding

---

asdf/_block/io.py
changes/1920.feature.rst

On main the block index is always loaded with `SafeLoader`. For files with a very large number of blocks this can take a considerable length of time.
This PR replaces the `SafeLoader` use with the "base loader" from asdf.versioning:
https://github.com/asdf-format/asdf/blob/9149ab669e545dfb35102340e7b390ec444d5750/asdf/versioning.py#L11
which can be `CSafeLoader`.
For a file with 10000 blocks main takes ~0.5 second (more with profiling) to load the block index:
With this PR the time is about a factor of 10 less:
- …

allow block index loading to use CSafeLoader

---

asdf/_tests/test_lazy_nodes.py
asdf/lazy_nodes.py
asdf/treeutil.py
changes/1922.bugfix.rst

This fixes a bug where a deepcopy of a lazy node retains references to the original lazy tree (instead of becoming non-lazy nodes). While adding tests for and fixing this issue I found that `walk_and_modify` converts `AsdfOrderedDictNode` instances into `dict`. That bug is also fixed in this PR and is required for this PR since `walk_and_modify` is used to handle the deepcopy.
</details>

fix deepcopy of lazy tree

---

changes/1938.doc.rst
docs/asdf/arrays.rst
docs/asdf/extending/converters.rst
docs/asdf/extending/extensions.rst
docs/asdf/extending/schemas.rst

Add `get/set_array_compression` to section describing compression
Closes: #1855
Add comparison of tags vs refs in schemas (recommend `foo-1*` like tags)
Closes: #1791 
Expand documentation about versioning for extension developers
Closes: #1895
Add section about converter tag wildcards leading to ignored converters
Closes: #1631
</details>

Docs updates

---

asdf/_asdf.py
asdf/_display.py
asdf/_node_info.py
asdf/_tests/test_deprecated.py
asdf/search.py
changes/1935.removal.rst

Deprecate `refresh_extension_manager` argument to `info`, `schema_info` and `SearchResult.schema_info`.
This is unused but does appear in the automatically generated docs.
Closes #1881
</details>

deprecate refresh_extension_manager

---

asdf/_tests/test_deprecated.py
asdf/schema.py
changes/1936.removal.rst

Deprecate `url_mapping` argument to `get_validator`. Arbitrary mapping of uris/urls is no longer supported.
Closes: #1864
</details>

deprecate url_mapping argument to get_validator

---

asdf/_asdf.py
asdf/_commands/edit.py
asdf/_io.py
asdf/_tests/test_api.py
asdf/yamlutil.py
changes/1955.bugfix.rst
pytest_asdf/plugin.py

Simply what happens when `asdf.open` is called. On main this involves:
- `asdf.open` an alias of [asdf._asdf.open_asdf](https://github.com/asdf-format/asdf/blob/6197b4c8505cdbaa1e4076566becc6af17877e89/asdf/_asdf.py#L1507)
- then calls [AsdfFile._open_impl](https://github.com/asdf-format/asdf/blob/6197b4c8505cdbaa1e4076566becc6af17877e89/asdf/_asdf.py#L909) a class method that expects an instance as an argument
- then calls [AsdfFile._open_asdf](https://github.com/asdf-format/asdf/blob/6197b4c8505cdbaa1e4076566becc6af17877e89/asdf/_asdf.py#L796) another class method that expects an instance
This PR simplifies the process to:
- `asdf.open` an alias of asdf._asdf.open_asdf
- calls `asdf._io.open_asdf` (which reads the comments, tree and blocks)
- returns a created instance (which still …

Simplify open

---

pytest_asdf/plugin.py

Start the deprecation process for the bundled pytest asdf plugin in favor of a separate package for the plugin.
See: https://github.com/asdf-format/pytest-asdf-plugin
The current plan is:
- merge this PR which adds a check for `pytest-asdf-plugin` to avoid registering both plugins
- make an asdf release
- make and release the separate package (tentatively `pytest-asdf-plugin` to avoid the name conflict) I have this after this check to allow it to be released with a real version check against a released asdf that has the plugin check added in this PR.
- the "external" plugin from the new package and the old "bundled" plugin from asdf should work along side each other. A user that installs asdf will continue to get the "bundled" plugin. If they install `pytest-asdf-plugin` they'll get the …

Check for external pytest-asdf-plugin and don't register bundled plugin if the external one exists

---

changes/1959.removal.rst
pytest_asdf/plugin.py

With the release of https://pypi.org/project/pytest-asdf-plugin/ and updates to our downstream to use the new plugin we can start warning when the bundled plugin is used.
This PR issues a warning when the bundled plugin runs a test.
Requires:
- https://github.com/asdf-format/asdf-standard/pull/478
- https://github.com/asdf-format/asdf-wcs-schemas/pull/77
- https://github.com/asdf-format/asdf-transform-schemas/pull/127
- https://github.com/asdf-format/asdf-coordinates-schemas/pull/71
- https://github.com/astropy/asdf-astropy/pull/291
- https://github.com/spacetelescope/rad/pull/667 (rad has no devdeps testing with asdf so as long as these go in before the next asdf release we're fine to merge this asdf PR first)
- https://github.com/BAMWelDX/weldx/pull/997
- …

warn when bundled pytest plugin runs

---

asdf/_core/_converters/integer.py
asdf/_core/_converters/ndarray.py
asdf/_core/_extensions.py
asdf/_tests/tags/core/tests/test_ndarray.py
asdf/_tests/test_history.py
asdf/_tests/test_schema.py
asdf/_tests/test_types.py
asdf/_tests/test_versioning.py
asdf/versioning.py
changes/1962.feature.rst
docs/asdf/config.rst
pyproject.toml
tox.ini

Support new "unstable" schemas (1.7.0) added in https://github.com/asdf-format/asdf-standard/pull/479 by:
- adding new integer-1.2.0 and ndarray-1.2.0 tags to converters
- use "get_supported_core_schema_versions" from asdf-standard to dynamically set the supported versions (in part based on the presence of the `ASDF_UNSTABLE_CORE_SCHEMAS` environment variable)
- set `ASDF_UNSTABLE_CORE_SCHEMAS` in devdeps to test unstable version of schemas
- update several tests that started breaking with the unstable schemas. Most expected tags only in 1.6.0 (such as ndarray-1.1.0). These were updated in a way that should be compatible with future updates by dynamically inspecting the currently used tag or by forcing a core schema version (where the test was not designed to test the schema/extension but …

support core-1.7.0
